//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerFindMyFriendsLinks : SDAirDropHandlerGenericLinks
{
}

- (void)updatePossibleActions;	// IMP=0x00000001000b6a6c
- (id)suitableContentsDescription;	// IMP=0x00000001000b69ac
- (id)suitableContentsTitle;	// IMP=0x00000001000b69a0
- (long long)transferTypes;	// IMP=0x00000001000b6968
- (_Bool)canHandleTransfer;	// IMP=0x00000001000b6948
- (id)initWithTransfer:(id)arg1;	// IMP=0x00000001000b6910

@end

