//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandler.h"

@class SDAirDropHandleriCloudDrive;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerUnsupportedType : SDAirDropHandler
{
    SDAirDropHandleriCloudDrive *_icloudDriveHandler;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003ecb4
- (void)triggerAppStoreSearch;	// IMP=0x000000010003ea70
- (void)updatePossibleActions;	// IMP=0x000000010003e760
- (id)suitableContentsDescription;	// IMP=0x000000010003e634
- (_Bool)canHandleTransfer;	// IMP=0x000000010003e5a4
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010003e4c0

@end

