//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"
#import "SDAirDropFileZipperDelegate-Protocol.h"
#import "SDBonjourResolverDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableData, NSMutableDictionary, NSMutableSet, NSNumber, NSProgress, NSString, NSURL, NSURLResponse, NSURLSession, NSURLSessionUploadTask, SDAirDropFileZipper, SDAirDropPeerMetric, SDBonjourResolver, SDStatusMonitor, SDXPCHelperConnection;
@protocol OS_dispatch_queue, OS_os_transaction, SDAirDropClientDelegate;

__attribute__((visibility("hidden")))
@interface SDAirDropClient : NSObject <SDAirDropFileZipperDelegate, SDBonjourResolverDelegate, NSURLSessionDataDelegate>
{
    NSURLResponse *_askResponse;	// 8 = 0x8
    NSURLSessionUploadTask *_askTask;	// 16 = 0x10
    _Bool _cancelled;	// 24 = 0x18
    NSString *_clientBundleID;	// 32 = 0x20
    NSString *_compressionType;	// 40 = 0x28
    NSString *_connectionKey;	// 48 = 0x30
    _Bool _conversionNotified;	// 56 = 0x38
    _Bool _conversionObserver;	// 57 = 0x39
    NSProgress *_conversionProgress;	// 64 = 0x40
    _Bool _discover;	// 72 = 0x48
    NSURLResponse *_discoverResponse;	// 80 = 0x50
    NSURLSessionUploadTask *_discoverTask;	// 88 = 0x58
    int _failCount;	// 96 = 0x60
    struct CGImage *_fileIcon;	// 104 = 0x68
    NSMutableArray *_fileURLs;	// 112 = 0x70
    NSMutableDictionary *_fileURLToConversionNeeded;	// 120 = 0x78
    NSMutableSet *_generatedFiles;	// 128 = 0x80
    struct __SecIdentity *_identity;	// 136 = 0x88
    NSArray *_items;	// 144 = 0x90
    long long _lastEvent;	// 152 = 0x98
    NSMutableArray *_mediaFormatConversionDestinations;	// 160 = 0xa0
    SDAirDropPeerMetric *_metric;	// 168 = 0xa8
    SDStatusMonitor *_monitor;	// 176 = 0xb0
    NSMutableArray *_otherStuff;	// 184 = 0xb8
    _Bool _p2pRetained;	// 192 = 0xc0
    struct __SFNode *_person;	// 200 = 0xc8
    _Bool _personAdded;	// 208 = 0xd0
    unsigned int _powerAssertionID;	// 212 = 0xd4
    NSProgress *_progress;	// 216 = 0xd8
    NSMutableDictionary *_properties;	// 224 = 0xe0
    _Bool _providedStream;	// 232 = 0xe8
    NSObject<OS_dispatch_queue> *_queue;	// 240 = 0xf0
    _Bool _queueSuspended;	// 248 = 0xf8
    NSMutableData *_receiverData;	// 256 = 0x100
    SDBonjourResolver *_resolver;	// 264 = 0x108
    NSNumber *_sendingLivePhotoJPEGs;	// 272 = 0x110
    struct __SecTrust *_serverTrust;	// 280 = 0x118
    NSURL *_serverURL;	// 288 = 0x120
    NSURLSession *_session;	// 296 = 0x128
    _Bool _shouldPublishProgress;	// 304 = 0x130
    struct CGImage *_smallFileIcon;	// 312 = 0x138
    double _startTime;	// 320 = 0x140
    NSURL *_tmpDirectoryToCleanUp;	// 328 = 0x148
    NSObject<OS_os_transaction> *_transaction;	// 336 = 0x150
    _Bool _transactionStarted;	// 344 = 0x158
    NSProgress *_transferProgress;	// 352 = 0x160
    _Bool _uploadFinished;	// 360 = 0x168
    NSURLResponse *_uploadResponse;	// 368 = 0x170
    NSURLSessionUploadTask *_uploadTask;	// 376 = 0x178
    NSMutableArray *_weblocURLs;	// 384 = 0x180
    SDXPCHelperConnection *_xpcHelperConnection;	// 392 = 0x188
    SDAirDropFileZipper *_zipper;	// 400 = 0x190
    _Bool _zipperFinished;	// 408 = 0x198
    int _clientPid;	// 412 = 0x19c
    id <SDAirDropClientDelegate> _delegate;	// 416 = 0x1a0
    CDStruct_4c969caf _auditToken;	// 424 = 0x1a8
}

- (void).cxx_destruct;	// IMP=0x0000000100079568
@property __weak id <SDAirDropClientDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldPublishProgress; // @synthesize shouldPublishProgress=_shouldPublishProgress;
@property(copy) NSString *clientBundleID; // @synthesize clientBundleID=_clientBundleID;
@property int clientPid; // @synthesize clientPid=_clientPid;
@property CDStruct_4c969caf auditToken; // @synthesize auditToken=_auditToken;
- (void)donateTransferInteractionToDuet;	// IMP=0x00000001000794dc
- (void)convertMediaItemsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000794d0
- (void)generatePreviewForFileURL:(id)arg1;	// IMP=0x00000001000794cc
- (void)invalidate;	// IMP=0x0000000100079088
@property(readonly) NSString *personID;
- (_Bool)send;	// IMP=0x0000000100078e88
- (void)resolve;	// IMP=0x0000000100078d6c
- (void)activate;	// IMP=0x0000000100078844
- (void)startSending;	// IMP=0x00000001000782c8
- (id)tmpDirectory;	// IMP=0x0000000100078130
- (void)cancelSendingClassroom;	// IMP=0x0000000100078078
- (void)startSendingClassroom;	// IMP=0x0000000100077e7c
- (void)startPublishingProgress;	// IMP=0x0000000100077c44
- (void)removeFileIconsFromProperties;	// IMP=0x0000000100077b70
- (void)appendFileURL:(id)arg1 withBase:(id)arg2 toItems:(id)arg3;	// IMP=0x00000001000777bc
- (void)validateAirDropItemsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000771e8
- (_Bool)replaceFileURLsWithRealPaths;	// IMP=0x0000000100077050
- (_Bool)splitOutFileURLs;	// IMP=0x0000000100076ca4
- (id)realPathURL:(struct __CFURL *)arg1;	// IMP=0x0000000100076afc
- (id)webURLFromInternetLocationFile:(id)arg1;	// IMP=0x0000000100076a30
- (id)internetLocationFile:(struct __CFURL *)arg1;	// IMP=0x00000001000768b4
- (id)temporaryWeblocURL:(struct __CFURL *)arg1;	// IMP=0x00000001000766d0
- (void)startZipping;	// IMP=0x00000001000765f4
- (void)sendRequest:(id)arg1;	// IMP=0x0000000100075f88
- (id)discoverBodyDataInFormat:(long long)arg1;	// IMP=0x0000000100075f0c
- (id)askBodyDataInFormat:(long long)arg1;	// IMP=0x0000000100075c30
- (void)addHashesAndValidationRecordToRequest:(id)arg1;	// IMP=0x0000000100075b70
- (void)bonjourResolverDidChange:(id)arg1;	// IMP=0x0000000100075728
- (void)fileZipper:(id)arg1 event:(long long)arg2 withProperty:(void *)arg3;	// IMP=0x0000000100075598
- (void)URLSession:(id)arg1 task:(id)arg2 needNewBodyStream:(CDUnknownBlockType)arg3;	// IMP=0x0000000100075464
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100074f54
- (void)URLSession:(id)arg1 task:(id)arg2 didFinishCollectingMetrics:(id)arg3;	// IMP=0x0000000100074b04
@property(readonly) struct __SecTrust *secTrustRef;
- (void)logInterfaceUsedForSending:(id)arg1;	// IMP=0x0000000100074aa0
- (void)releasePeerToPeerIfPossible:(id)arg1;	// IMP=0x0000000100074a20
- (_Bool)connectionOverP2P:(struct __CFData *)arg1;	// IMP=0x00000001000747f0
- (struct __SecKey *)copyReceiverPublicKey;	// IMP=0x00000001000746f0
- (void)evaluateReceiverTrust:(struct __SecTrust *)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100074558
- (void)didFail:(id)arg1;	// IMP=0x00000001000742b8
- (_Bool)shouldCancelTransferForError:(id)arg1;	// IMP=0x00000001000741bc
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x00000001000740f4
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;	// IMP=0x0000000100074074
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x0000000100073fd0
- (void)didFinishLoading;	// IMP=0x0000000100073e0c
- (void)retryRequestForError:(id)arg1;	// IMP=0x0000000100073c2c
- (void)finishOperation;	// IMP=0x00000001000738a0
- (void)notifyClientOfBytesCopied:(id)arg1 timeRemaining:(id)arg2;	// IMP=0x0000000100073744
- (_Bool)parseDiscoverResponse:(struct __CFError **)arg1;	// IMP=0x0000000100073570
- (_Bool)parseAskResponse:(struct __CFError **)arg1;	// IMP=0x00000001000733f0
- (void)storeStringValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0000000100073344
- (void)storeDataValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0000000100073298
- (void)storePropertyValue:(void *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0000000100073180
- (void)setProperty:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000100073130
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100072b68
- (void)setSpotlightMetadata:(id)arg1;	// IMP=0x0000000100072b64
- (id)whereFromInfo;	// IMP=0x0000000100072abc
- (void)didFinishSendingAskBodyData;	// IMP=0x0000000100072a74
- (void)didStartSendingAskBodyData;	// IMP=0x00000001000729e0
- (void)postNotificationForTransferStatus:(long long)arg1 progress:(double)arg2;	// IMP=0x00000001000729dc
- (void)notifyClientForEvent:(long long)arg1 withProperty:(void *)arg2;	// IMP=0x0000000100072290
- (void)releaseIdleSleepAssertion;	// IMP=0x0000000100072180
- (double)getTransferRate;	// IMP=0x00000001000720f8
- (void)createSession;	// IMP=0x0000000100071e08
- (_Bool)requireAWDL;	// IMP=0x0000000100071dbc
- (void)removeObservers;	// IMP=0x0000000100071d6c
- (void)addObservers;	// IMP=0x0000000100071cd0
- (void)wirelessPowerChanged:(id)arg1;	// IMP=0x0000000100071c60
- (void)systemWillSleep:(id)arg1;	// IMP=0x0000000100071c10
- (void)dealloc;	// IMP=0x0000000100071b24
- (id)initWithPerson:(struct __SFNode *)arg1 items:(id)arg2 forDiscovery:(_Bool)arg3;	// IMP=0x0000000100071730

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

