//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandleriCloudFamilyLinks : SDAirDropHandlerGenericLinks
{
}

- (id)cancelActionTitleToAccompanyActions:(id)arg1;	// IMP=0x00000001001048f0
- (id)singleItemActionTitle;	// IMP=0x00000001001048e4
- (id)suitableContentsDescription;	// IMP=0x0000000100104824
- (id)suitableContentsTitle;	// IMP=0x0000000100104818
- (long long)transferTypes;	// IMP=0x00000001001047e0
- (_Bool)canHandleTransfer;	// IMP=0x00000001001047d8
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010010479c

@end

