//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSMutableSet, SFRemoteTextInputClient;
@protocol OS_dispatch_queue, OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SDSharedRemoteTextInputClient : NSObject
{
    _Bool _activateCalled;	// 8 = 0x8
    NSMutableSet *_delegates;	// 16 = 0x10
    NSObject<OS_dispatch_source> *_overrunTimer;	// 24 = 0x18
    SFRemoteTextInputClient *_rtiClient;	// 32 = 0x20
    NSDate *_sessionClock;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 48 = 0x30
}

+ (id)sharedClient;	// IMP=0x00000001000d1f8c
- (void).cxx_destruct;	// IMP=0x00000001000d2e40
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void)_stopClock:(unsigned long long)arg1;	// IMP=0x00000001000d2e1c
- (void)_startClockWithResetIfNeeded;	// IMP=0x00000001000d2bf8
- (void)_logEvent:(unsigned long long)arg1 stopClock:(_Bool)arg2;	// IMP=0x00000001000d29b0
- (void)_rtiHandleInputDidEndWithFlags:(unsigned long long)arg1 sessionInfo:(id)arg2;	// IMP=0x00000001000d2850
- (void)_rtiHandleInputDidBeginWithFlags:(unsigned long long)arg1 sessionInfo:(id)arg2;	// IMP=0x00000001000d26f4
- (void)_rtiHandleEventWithData:(id)arg1;	// IMP=0x00000001000d2590
- (void)prefsChanged;	// IMP=0x00000001000d258c
- (void)handleUsername:(id)arg1 password:(id)arg2;	// IMP=0x00000001000d253c
- (void)handleTextInputData:(id)arg1;	// IMP=0x00000001000d252c
- (void)removeAllDelegates;	// IMP=0x00000001000d24f8
- (void)removeDelegate:(id)arg1;	// IMP=0x00000001000d245c
- (void)addDelegate:(id)arg1;	// IMP=0x00000001000d239c
- (void)invalidate;	// IMP=0x00000001000d2294
@property(readonly, copy, nonatomic) NSDictionary *currentPayload;
- (void)activate;	// IMP=0x00000001000d2210
- (void)_ensureStarted;	// IMP=0x00000001000d205c
- (id)init;	// IMP=0x00000001000d1ff8

@end

