//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData;

@interface SDUnlockSessionAuthToken : PBCodable <NSCopying>
{
    NSData *_authToken;	// 8 = 0x8
    unsigned int _errorCode;	// 16 = 0x10
    unsigned int _sessionID;	// 20 = 0x14
    unsigned int _version;	// 24 = 0x18
    CDStruct_e173124d _has;	// 28 = 0x1c
}

- (void).cxx_destruct;	// IMP=0x000000010019aa2c
@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) NSData *authToken; // @synthesize authToken=_authToken;
@property(nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010019a910
- (unsigned long long)hash;	// IMP=0x000000010019a85c
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010019a728
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010019a630
- (void)copyTo:(id)arg1;	// IMP=0x000000010019a568
- (void)writeTo:(id)arg1;	// IMP=0x000000010019a4b0
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010019a4a8
- (id)dictionaryRepresentation;	// IMP=0x0000000100199f74
- (id)description;	// IMP=0x0000000100199ec0
@property(nonatomic) _Bool hasErrorCode;
@property(readonly, nonatomic) _Bool hasAuthToken;
@property(nonatomic) _Bool hasSessionID;
@property(nonatomic) _Bool hasVersion;

@end

