//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@interface TVNPRoutingDestinationsCollectionViewLayout : UICollectionViewFlowLayout
{
    _Bool _enabled;	// 8 = 0x8
}

+ (Class)invalidationContextClass;	// IMP=0x000000010001a490
+ (Class)layoutAttributesClass;	// IMP=0x000000010001a484
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x000000010001a7d8
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x000000010001a698
- (struct CGPoint)targetContentOffsetForIndexPath:(id)arg1;	// IMP=0x000000010001a52c
- (void)invalidateLayoutWithContext:(id)arg1;	// IMP=0x000000010001a49c

@end

