//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SSPlaybackStateChanged-Protocol.h"

@class NSArray, NSDictionary, NSString, NSURL;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SSAssetManager : NSObject <SSPlaybackStateChanged>
{
    NSObject<OS_dispatch_queue> *_updateQueue;	// 8 = 0x8
    int _assetInstalledToken;	// 16 = 0x10
    int _metaDataUpdatedToken;	// 20 = 0x14
    unsigned long long _currentInstalledVersion;	// 24 = 0x18
    unsigned long long _catalogFailCount;	// 32 = 0x20
    unsigned long long _assetFailCount;	// 40 = 0x28
    unsigned long long _purgeFailCount;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_catalogDownloadTimer;	// 56 = 0x38
    NSObject<OS_dispatch_queue> *_catalogDownloadQueue;	// 64 = 0x40
    _Bool _isPendingAssetRefUpdate;	// 72 = 0x48
    NSURL *_downloadedAssetURL;	// 80 = 0x50
    NSString *_defaultAssetName;	// 88 = 0x58
    NSArray *_playbackSequence;	// 96 = 0x60
    NSDictionary *_deviceAssetInfoMap;	// 104 = 0x68
    NSDictionary *_assetNameForMediaName;	// 112 = 0x70
}

+ (id)sharedInstance;	// IMP=0x00000001000066d4
- (void).cxx_destruct;	// IMP=0x0000000100009d24
@property(retain, nonatomic) NSDictionary *assetNameForMediaName; // @synthesize assetNameForMediaName=_assetNameForMediaName;
@property(retain, nonatomic) NSDictionary *deviceAssetInfoMap; // @synthesize deviceAssetInfoMap=_deviceAssetInfoMap;
@property(readonly, nonatomic, getter=getPlaybackSequence) NSArray *playbackSequence; // @synthesize playbackSequence=_playbackSequence;
@property(readonly, nonatomic, getter=getDefaultAssetName) NSString *defaultAssetName; // @synthesize defaultAssetName=_defaultAssetName;
@property(readonly, nonatomic) NSURL *downloadedAssetURL; // @synthesize downloadedAssetURL=_downloadedAssetURL;
- (void)playbackStateChanged:(unsigned long long)arg1;	// IMP=0x0000000100009c08
- (void)stopCatalogUpdateTimer;	// IMP=0x0000000100009b74
- (void)startCatalogUpdateTimer;	// IMP=0x0000000100009924
- (id)getImageURLStringForAsset:(id)arg1;	// IMP=0x00000001000093b8
- (id)getAssetURL:(id)arg1;	// IMP=0x0000000100009020
- (id)getSongForType:(id)arg1;	// IMP=0x0000000100008ef4
- (id)getSongAttributes:(id)arg1;	// IMP=0x0000000100008ee4
- (_Bool)deviceContainsAsset:(id)arg1;	// IMP=0x0000000100008dec
- (id)deviceAssetNameForMediaName:(id)arg1;	// IMP=0x0000000100008d5c
- (void)assetsOnDevice;	// IMP=0x00000001000089f8
- (id)pathToAssetPlistOnDevice;	// IMP=0x0000000100008918
- (id)currentAssetStateToString:(long long)arg1;	// IMP=0x00000001000088a4
- (void)updateLocalReferences:(unsigned long long)arg1;	// IMP=0x0000000100008650
- (void)downloadAsset:(id)arg1;	// IMP=0x0000000100007efc
- (unsigned long long)getAssetVersion:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000100007dc8
- (void)purgeAssetIfNeedBe;	// IMP=0x0000000100007934
- (void)updateAssetMetaData;	// IMP=0x000000010000733c
- (void)downloadCatalog;	// IMP=0x0000000100006f30
- (void)handleAssetSuccessfullyInstalled;	// IMP=0x0000000100006e84
- (void)handleMetadataAssetUpdated;	// IMP=0x0000000100006c3c
- (void)setUpNotificationHandlers;	// IMP=0x0000000100006a34
- (void)dealloc;	// IMP=0x00000001000069b0
- (id)init;	// IMP=0x0000000100006778

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

