//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DataArk;

@interface MACollectionInterface : NSObject
{
    _Bool _collectionLibraryLoaded;	// 8 = 0x8
    struct __SecKey *_signingKey;	// 16 = 0x10
    DataArk *_dark;	// 24 = 0x18
}

+ (id)copyIngestURL;	// IMP=0x000000010000aeac
@property(readonly, nonatomic) DataArk *dark; // @synthesize dark=_dark;
@property(nonatomic) _Bool collectionLibraryLoaded; // @synthesize collectionLibraryLoaded=_collectionLibraryLoaded;
- (_Bool)processSUInfo:(id)arg1 withError:(id *)arg2;	// IMP=0x000000010000cf38
- (id)copyIngestData:(id *)arg1;	// IMP=0x000000010000bf3c
- (id)copyIngestHeaders:(id)arg1 withError:(id *)arg2;	// IMP=0x000000010000bbc4
- (id)signatureForData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010000bacc
- (id)signingKeyPublicKeyWithError:(id *)arg1;	// IMP=0x000000010000b9c4
- (id)collectPCRT:(id *)arg1;	// IMP=0x000000010000b7d0
- (id)collectSIK:(id *)arg1;	// IMP=0x000000010000b394
- (id)collectSigningAttestation:(id *)arg1;	// IMP=0x000000010000b234
@property(readonly) struct __SecKey *signingKey; // @synthesize signingKey=_signingKey;
- (void)dealloc;	// IMP=0x000000010000ae5c
- (id)initWithContext:(id)arg1;	// IMP=0x000000010000ade4

@end

