//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter, NSMutableArray, NSMutableDictionary, NSString, W5DiagnosticsManager, W5LogItemRequestInternal, W5StatusManager, WADeviceAnalyticsClient;
@protocol OS_dispatch_queue;

@interface W5LogManager : NSObject
{
    W5StatusManager *_status;	// 8 = 0x8
    W5DiagnosticsManager *_diagnostics;	// 16 = 0x10
    NSString *_model;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    NSMutableArray *_pendingRequests;	// 40 = 0x28
    W5LogItemRequestInternal *_activeRequest;	// 48 = 0x30
    NSDateFormatter *_dateFormatter;	// 56 = 0x38
    NSMutableDictionary *_taskUUIDMap;	// 64 = 0x40
    NSMutableDictionary *_urlUUIDMap;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_debugLogQueue;	// 80 = 0x50
    NSMutableDictionary *_debugLogMap;	// 88 = 0x58
    NSMutableDictionary *_missingLogItemMap;	// 96 = 0x60
    struct __IOReportSubscriptionCF *_ioReportSubscription;	// 104 = 0x68
    unsigned long long _ioReportBaseMachAbsoluteTime;	// 112 = 0x70
    unsigned long long _ioReportDeltaMachAbsoluteTime;	// 120 = 0x78
    struct __CFDictionary *_ioReportChannels;	// 128 = 0x80
    struct __CFDictionary *_ioReportBase;	// 136 = 0x88
    struct __CFDictionary *_ioReportDelta;	// 144 = 0x90
    NSMutableDictionary *_leewayUUIDMap;	// 152 = 0x98
    NSMutableDictionary *_timestampUUIDMap;	// 160 = 0xa0
    NSMutableDictionary *_cachedSysdiagnoseURLMap;	// 168 = 0xa8
    NSMutableDictionary *_cachedSysdiagnoseBTURLMap;	// 176 = 0xb0
    WADeviceAnalyticsClient *_waDeviceAnalyticsClient;	// 184 = 0xb8
    CDUnknownBlockType _collectedItemCallback;	// 192 = 0xc0
    CDUnknownBlockType _collectLogItemCallback;	// 200 = 0xc8
    CDUnknownBlockType _pingCallback;	// 208 = 0xd0
}

+ (id)__temporaryDirectory;	// IMP=0x0000000100060c0c
+ (void)__parsePingOutput:(id)arg1 result:(id)arg2;	// IMP=0x000000010005f854
+ (id)__logBluetoothStatus:(id)arg1;	// IMP=0x000000010005c7d8
+ (id)__logWiFiStatus:(id)arg1;	// IMP=0x000000010005b994
+ (id)__logNetworkStatus:(id)arg1;	// IMP=0x000000010005b4c8
+ (id)__logTxPower:(struct apple80211_per_chain_power_data_get)arg1;	// IMP=0x000000010005b3fc
+ (id)__logBTCProfile:(struct apple80211_btc_profile_osx)arg1;	// IMP=0x000000010005b074
+ (id)__logScanResults:(id)arg1;	// IMP=0x000000010005a70c
+ (id)__descriptionForNetwork:(id)arg1;	// IMP=0x000000010005a384
@property(copy, nonatomic) CDUnknownBlockType pingCallback; // @synthesize pingCallback=_pingCallback;
@property(copy, nonatomic) CDUnknownBlockType collectLogItemCallback; // @synthesize collectLogItemCallback=_collectLogItemCallback;
@property(copy, nonatomic) CDUnknownBlockType collectedItemCallback; // @synthesize collectedItemCallback=_collectedItemCallback;
- (void)__dumpCoreCaptureLogsWithReason:(id)arg1 component:(id)arg2;	// IMP=0x0000000100060950
- (_Bool)__wlCLIWithArguments:(id)arg1 outputFilePath:(id)arg2 outputData:(id)arg3;	// IMP=0x00000001000608a0
- (void)__wlCLIWithArguments:(id)arg1 outputFileHandle:(id)arg2 addCommand:(_Bool)arg3 addTimestamps:(_Bool)arg4;	// IMP=0x0000000100060594
- (void)__wlCLIWithArguments:(id)arg1 outputFileHandle:(id)arg2;	// IMP=0x0000000100060580
- (void)__runToolWithOutputFileHandle:(id)arg1 readFromStandardError:(_Bool)arg2 launchPath:(id)arg3 arguments:(id)arg4 addCommand:(_Bool)arg5 addTimestamps:(_Bool)arg6;	// IMP=0x000000010005fb88
- (void)__runToolWithOutputFileHandle:(id)arg1 launchPath:(id)arg2 arguments:(id)arg3;	// IMP=0x000000010005fb68
- (id)__pingUsingIMFoundationWithAddress:(id)arg1 timeout:(long long)arg2;	// IMP=0x000000010005f30c
- (id)__pingUsingCFNetworkWithAddress:(id)arg1 count:(long long)arg2 timeout:(long long)arg3 trafficClass:(id)arg4 networkServiceType:(id)arg5;	// IMP=0x000000010005ed30
- (id)__ping6WithAddress:(id)arg1 count:(long long)arg2 wait:(double)arg3 trafficClass:(id)arg4 interfaceName:(id)arg5 dataLength:(unsigned long long)arg6;	// IMP=0x000000010005e880
- (id)__pingWithAddress:(id)arg1 count:(long long)arg2 timeout:(double)arg3 wait:(double)arg4 interval:(double)arg5 trafficClass:(id)arg6 interfaceName:(id)arg7 dataLength:(unsigned long long)arg8;	// IMP=0x000000010005e304
- (id)__logAWDLStatus:(id)arg1;	// IMP=0x000000010005cefc
- (id)__logDiagnosticsTestResults:(id)arg1;	// IMP=0x000000010005ae30
- (id)__logDiagnosticsPingResults:(id)arg1;	// IMP=0x000000010005a9ec
- (id)__runDiagnosticsTests:(id)arg1 configuration:(id)arg2 timeout:(long long)arg3 error:(id *)arg4;	// IMP=0x0000000100059e00
- (id)__collectIndividual:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100058c60
- (id)__collectLogItem:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100057f60
- (id)__collectDatapathStats:(id)arg1;	// IMP=0x00000001000576cc
- (id)__collectDeviceAnalyticsStore:(id)arg1;	// IMP=0x0000000100056b58
- (id)__collect3barsCache:(id)arg1;	// IMP=0x0000000100056944
- (id)__collectWiFiPerfLogs:(id)arg1;	// IMP=0x00000001000566f0
- (id)__collectWiFiDeviceConfig:(id)arg1;	// IMP=0x00000001000558f4
- (id)__collectWiFiMemoryUsage:(id)arg1;	// IMP=0x0000000100055504
- (id)__collectPreviouslyCollected:(id)arg1;	// IMP=0x000000010005513c
- (id)__collectWiFiStatsCLI:(id)arg1;	// IMP=0x0000000100054e5c
- (id)__collectWiFiStatsPost:(id)arg1;	// IMP=0x0000000100054ad0
- (id)__collectWiFiStatsPre:(id)arg1;	// IMP=0x0000000100054a0c
- (void)__setupWiFiStats;	// IMP=0x00000001000544f4
- (void)__teardownWiFiStats;	// IMP=0x0000000100054494
- (void)__startWiFiStats;	// IMP=0x0000000100054444
- (void)__endWiFiStats;	// IMP=0x00000001000543c4
- (id)__collect_mobilewifitool:(id)arg1;	// IMP=0x000000010005418c
- (id)__collect_security:(id)arg1;	// IMP=0x0000000100053f30
- (id)__collectMultiple:(id)arg1;	// IMP=0x000000010005319c
- (id)__collectAdditionalLog:(id)arg1 url:(id)arg2;	// IMP=0x0000000100052fd0
- (id)__collectEventHistory:(id)arg1;	// IMP=0x00000001000520f0
- (id)__collectCrashesAndSpins24:(id)arg1;	// IMP=0x0000000100051bcc
- (id)__collectBluetoothLogs:(id)arg1;	// IMP=0x00000001000518f0
- (id)__collectSharingLogs:(id)arg1;	// IMP=0x0000000100051700
- (id)__collectWirelessProxLogs:(id)arg1;	// IMP=0x0000000100051568
- (id)__collectAirPlayLogs:(id)arg1;	// IMP=0x00000001000512b8
- (id)__collectSystemLogs24:(id)arg1;	// IMP=0x0000000100051210
- (id)__collectWiFiVelocityLog:(id)arg1;	// IMP=0x0000000100050eec
- (id)__collectSystemLogs:(id)arg1;	// IMP=0x0000000100050ad8
- (id)__collectIPConfigurationLogs:(id)arg1;	// IMP=0x0000000100050828
- (id)__collectEAP8021XLogs:(id)arg1;	// IMP=0x00000001000504ec
- (id)__collectWiFiLogsDump:(id)arg1;	// IMP=0x0000000100050448
- (id)__collectWiFiLogs:(id)arg1;	// IMP=0x000000010005002c
- (id)__collectWiFiLogs24:(id)arg1;	// IMP=0x000000010004fce0
- (id)__collectFilteredWiFiManagerLogArchiveWithOutputURL:(id)arg1 compress:(_Bool)arg2 age:(unsigned long long)arg3;	// IMP=0x000000010004fb14
- (void)__dumpWiFiLogs;	// IMP=0x000000010004fa98
- (id)__possibleTempWiFiLogPaths;	// IMP=0x000000010004fa8c
- (id)__collectNetworkPreferences:(id)arg1;	// IMP=0x000000010004f8f4
- (id)__collectWiFiPreferences:(id)arg1;	// IMP=0x000000010004f2c0
- (id)__collectCoreCapture24:(id)arg1;	// IMP=0x000000010004ee9c
- (id)__collectCoreCapture:(id)arg1;	// IMP=0x000000010004e9b4
- (id)__collectCoreCaptureDump:(id)arg1;	// IMP=0x000000010004e894
- (void)__filterCoreCaptureContent:(id)arg1;	// IMP=0x000000010004e5c0
- (id)__possibleCoreCapturePathsWithComponent:(id)arg1;	// IMP=0x000000010004e49c
- (id)__mostRecentInDirectories:(id)arg1 matchingPrefix:(id)arg2 matchingSuffix:(id)arg3 excludingPrefix:(id)arg4 excludingSuffix:(id)arg5 maxAge:(double)arg6;	// IMP=0x000000010004e018
- (id)__mostRecentInDirectories:(id)arg1 include:(id)arg2 exclude:(id)arg3 maxAge:(double)arg4;	// IMP=0x000000010004db9c
- (id)__collectFileAtURL:(id)arg1 outputDirectory:(id)arg2 maxAge:(double)arg3 maxSize:(unsigned long long)arg4 compress:(_Bool)arg5 remainingSize:(unsigned long long *)arg6;	// IMP=0x000000010004d2e4
- (id)__collectFilesInDirectories:(id)arg1 include:(id)arg2 exclude:(id)arg3 maxAge:(double)arg4 maxCount:(unsigned long long)arg5 maxSize:(unsigned long long)arg6 outputDirectory:(id)arg7 compress:(_Bool)arg8 remainingSize:(unsigned long long *)arg9 contentFilter:(CDUnknownBlockType)arg10;	// IMP=0x000000010004c878
- (unsigned long long)__calculateSizeAtPath:(id)arg1;	// IMP=0x000000010004c548
- (id)__collect_pmset:(id)arg1;	// IMP=0x000000010004c3bc
- (id)__collectTCPDump_POST:(id)arg1;	// IMP=0x000000010004c134
- (id)__collectTCPDump_PRE:(id)arg1;	// IMP=0x000000010004bad8
- (id)__collect_ndp:(id)arg1;	// IMP=0x000000010004b818
- (id)__collect_sysdiagnose:(id)arg1;	// IMP=0x000000010004b31c
- (id)__collect_hosts:(id)arg1;	// IMP=0x000000010004b188
- (id)__collect_darwinup:(id)arg1;	// IMP=0x000000010004affc
- (id)__collect_spindump:(id)arg1;	// IMP=0x000000010004adc4
- (id)__collect_wl_cca_get_stats:(id)arg1;	// IMP=0x000000010004ac3c
- (id)__collect_wl_curpower:(id)arg1;	// IMP=0x000000010004aab4
- (id)__collect_configd:(id)arg1;	// IMP=0x000000010004a91c
- (id)__collectSystemConfiguration:(id)arg1;	// IMP=0x000000010004a788
- (id)__collect_netstat:(id)arg1;	// IMP=0x000000010004a3f0
- (id)__collect_top:(id)arg1;	// IMP=0x000000010004a264
- (id)__collect_ioreg:(id)arg1;	// IMP=0x000000010004a0d8
- (id)__collect_kextstat:(id)arg1;	// IMP=0x0000000100049f50
- (id)__collect_traceroute:(id)arg1;	// IMP=0x0000000100049d14
- (id)__collect_ipconfig:(id)arg1;	// IMP=0x0000000100049b28
- (id)__collect_ifconfig:(id)arg1;	// IMP=0x0000000100049914
- (id)__collect_CFNetworkPing:(id)arg1;	// IMP=0x0000000100048c50
- (id)__collect_ping:(id)arg1;	// IMP=0x000000010004788c
- (id)__collect_IMFoundationPing:(id)arg1;	// IMP=0x0000000100047130
- (id)__collectLogItemCallout:(id)arg1 baseURL:(id *)arg2 error:(id *)arg3;	// IMP=0x0000000100046e5c
- (id)__collectSystemProfiler:(id)arg1;	// IMP=0x0000000100046c98
- (id)__collect_arp:(id)arg1;	// IMP=0x0000000100046a84
- (id)__collect_swvers:(id)arg1;	// IMP=0x00000001000468fc
- (id)__collectBluetoothStatus:(id)arg1;	// IMP=0x000000010004663c
- (id)__collectWiFiStatus:(id)arg1;	// IMP=0x000000010004637c
- (id)__collectNetworkStatus:(id)arg1;	// IMP=0x00000001000460bc
- (id)__collectAWDLStatus:(id)arg1;	// IMP=0x0000000100045d54
- (id)__collectBonjourRecords:(id)arg1;	// IMP=0x0000000100045894
- (id)__resolveBonjourInstance:(id)arg1 serviceType:(id)arg2 duration:(unsigned long long)arg3;	// IMP=0x0000000100045770
- (id)__browseBonjourInstancesWithServiceType:(id)arg1 duration:(unsigned long long)arg2;	// IMP=0x00000001000454c8
- (id)__collectLeakyAPStats:(id)arg1;	// IMP=0x0000000100045284
- (id)__collectPerSSIDDiagnosticsHistory:(id)arg1;	// IMP=0x0000000100044e78
- (id)__collectDiagnostics:(id)arg1;	// IMP=0x0000000100044af8
- (id)__collectWiFiScanResults:(id)arg1;	// IMP=0x0000000100044898
- (void)__runRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100042efc
- (id)__expandLogItems:(id)arg1 configuration:(id)arg2;	// IMP=0x0000000100042af0
- (id)__basicWiFiLogsWithFilteredContent:(_Bool)arg1 useMegaWiFiProfileLimits:(_Bool)arg2;	// IMP=0x0000000100042134
- (id)__model;	// IMP=0x0000000100042040
- (id)__logItemsForBTSysdiagnoseWithFilteredContent:(_Bool)arg1;	// IMP=0x0000000100041a38
- (id)__logItemsForSysdiagnoseWithNoTimeoutAndFilteredContent:(_Bool)arg1 useMegaWiFiProfileLimits:(_Bool)arg2;	// IMP=0x0000000100040f90
- (id)__logItemsForSysdiagnoseWithFilteredContent:(_Bool)arg1 useMegaWiFiProfileLimits:(_Bool)arg2;	// IMP=0x00000001000400e0
- (id)__fastConnectivityDiagnosticsLogItemWithTimeout:(double)arg1;	// IMP=0x000000010003ffc8
- (id)__connectivityDiagnosticsLogItemWithTimeout:(double)arg1;	// IMP=0x000000010003fb54
- (id)__environmentDiagnosticsLogItemWithTimeout:(double)arg1;	// IMP=0x000000010003f8b8
- (id)__configurationDiagnosticsLogItemWithTimeout:(double)arg1;	// IMP=0x000000010003f344
- (id)__concurrentConnectivityDiagnosticsTest;	// IMP=0x000000010003ef68
- (id)__logItemsForInternalWiFiSettings;	// IMP=0x000000010003ef5c
- (id)__logItemsForTapToRadar;	// IMP=0x000000010003ef50
- (id)__logItemsForFeedbackAssistant;	// IMP=0x000000010003ef44
- (id)__logItemsForWiFiDiagnosticsExtension;	// IMP=0x000000010003e510
- (id)__logItemsForWiFiDiagnosticsApp;	// IMP=0x000000010003e43c
- (id)__logItemsForDatapathStallEventWithFilteredContent:(_Bool)arg1;	// IMP=0x000000010003dca4
- (id)__logItemsForBackgroundEventWithReason:(id)arg1 filteredContent:(_Bool)arg2;	// IMP=0x000000010003d7b8
- (id)__logItemsForABCWithReason:(id)arg1 filteredContent:(_Bool)arg2;	// IMP=0x000000010003d7ac
- (id)__logItemsForDumpLogsEventWithReason:(id)arg1 filteredContent:(_Bool)arg2;	// IMP=0x000000010003d240
- (void)__nextRequest;	// IMP=0x000000010003c5b8
- (void)__purgeFilesInDirectory:(id)arg1 matching:(id)arg2 maxAge:(unsigned long long)arg3 maxCount:(unsigned long long)arg4;	// IMP=0x000000010003c020
- (id)__pendingRequestWithUUID:(id)arg1;	// IMP=0x000000010003bee0
- (void)teardownAndNotify:(CDUnknownBlockType)arg1;	// IMP=0x000000010003bd1c
- (void)cancelRequestWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010003baec
- (void)addRequest:(id)arg1;	// IMP=0x0000000100039f00
- (_Bool)__logItems:(id)arg1 containsID:(long long)arg2;	// IMP=0x0000000100039de0
- (void)__replyWithCachedSysdiagnoseContentForRequest:(id)arg1 temporaryURL:(id)arg2;	// IMP=0x0000000100039a5c
- (void)dealloc;	// IMP=0x00000001000396b8
- (id)initWithStatusManager:(id)arg1 diagnosticsManager:(id)arg2;	// IMP=0x00000001000394e4

@end

