//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary, NSString;

@interface MSDFileMetadata : NSObject
{
    NSDictionary *_dict;	// 8 = 0x8
}

+ (id)compareResultToNSString:(int)arg1;	// IMP=0x0000000100018bdc
+ (id)fileMetaDataWithMetadataDictionary:(id)arg1;	// IMP=0x0000000100016e98
+ (id)fileMetadatatWithPath:(id)arg1;	// IMP=0x0000000100016e44
+ (id)targetFileWithPath:(id)arg1;	// IMP=0x00000001000168b4
+ (id)extendedAttributesWithPath:(id)arg1;	// IMP=0x000000010001663c
+ (id)valueForExtendedAttributesKey:(id)arg1 forPath:(id)arg2;	// IMP=0x0000000100016418
+ (id)accessControlListWithPath:(id)arg1;	// IMP=0x0000000100016128
+ (id)extendedAttributeKeysWithPath:(id)arg1;	// IMP=0x0000000100015e24
+ (id)fileAttributesWithPath:(id)arg1;	// IMP=0x0000000100015c28
+ (id)fileHashWithPath:(id)arg1;	// IMP=0x0000000100015a34
- (void).cxx_destruct;	// IMP=0x0000000100018c5c
@property(readonly) NSDictionary *dict; // @synthesize dict=_dict;
@property(readonly, getter=getFileSize) long long fileSize;
@property(readonly, getter=getTargetFile) NSString *targetFile;
@property(readonly, getter=getFileType) NSString *fileType;
@property(readonly, getter=getAccessControlList) NSData *accessControlList;
@property(readonly, getter=getExtendedAttributes) NSDictionary *extendedAttributes;
@property(readonly, getter=getFileAttributes) NSDictionary *fileAttributes;
@property(readonly, getter=getHash) NSData *hash;
- (id)fileAttributesAllowSet:(id)arg1;	// IMP=0x00000001000186a4
- (int)compareWith:(id)arg1;	// IMP=0x0000000100017e14
- (_Bool)restoreAttribuesToPath:(id)arg1;	// IMP=0x000000010001713c
- (_Bool)removeAllExtendedAttributes:(id)arg1;	// IMP=0x0000000100016f38
- (void)dealloc;	// IMP=0x0000000100016eec
- (id)initWithPath:(id)arg1;	// IMP=0x0000000100016a9c
- (id)initWithDictionary:(id)arg1;	// IMP=0x0000000100016a24

@end

