//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SiriUINavigationTransitioning-Protocol.h"

@class NSString, UINavigationController;
@protocol UIViewControllerAnimatedTransitioning;

@interface SRBarSlideNavigationTransitionController : NSObject <SiriUINavigationTransitioning>
{
    long long _operation;	// 8 = 0x8
    UINavigationController *_navigationController;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100023ed8
@property(nonatomic, getter=_navigationController, setter=_setNavigationController:) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) long long operation; // @synthesize operation=_operation;
- (void)_performNavigationBarAnimations;	// IMP=0x0000000100023e30
- (void)coordinateAdditionalTransitionsWithTransitionCoordinator:(id)arg1;	// IMP=0x0000000100023c2c
- (void)configureWithNavigationController:(id)arg1;	// IMP=0x0000000100023ba8

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

