//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UIBezierPath, UIColor;

@interface SRCarPlayFocusView : UIView
{
    unsigned long long _style;	// 8 = 0x8
    CAShapeLayer *_maskPathShapeLayer;	// 16 = 0x10
    UIBezierPath *_maskingPath;	// 24 = 0x18
    UIColor *_focusedContentColor;	// 32 = 0x20
}

+ (id)systemView;	// IMP=0x0000000100002d64
+ (id)vibrantView;	// IMP=0x0000000100002d38
- (void).cxx_destruct;	// IMP=0x0000000100003470
@property(retain, nonatomic) UIColor *focusedContentColor; // @synthesize focusedContentColor=_focusedContentColor;
@property(retain, nonatomic) UIBezierPath *maskingPath; // @synthesize maskingPath=_maskingPath;
- (id)_dynamicFocusContentColorFromStyle:(unsigned long long)arg1;	// IMP=0x00000001000032e8
- (id)_inverseTraitCollectionForUserInterfaceStyle:(long long)arg1;	// IMP=0x00000001000032c8
- (void)_updateViewFromUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010000325c
- (id)_vibrancyCompositingFilterFromUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100003224
- (id)_focusColor;	// IMP=0x00000001000031d0
@property(readonly, nonatomic) double focusedContentAlpha;
- (double)maximumAlphaFromUserInterfaceStyle:(long long)arg1;	// IMP=0x00000001000031a8
- (void)layoutSubviews;	// IMP=0x000000010000303c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100002fb8
- (id)_initWithStyle:(unsigned long long)arg1;	// IMP=0x0000000100002d90

@end

