//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UINavigationBar.h>

@class SiriUIKeyline;

@interface SRKeylineNavigationBar : UINavigationBar
{
    SiriUIKeyline *_keyline;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100088e9c
- (id)backItem;	// IMP=0x0000000100088dcc
- (void)layoutSubviews;	// IMP=0x0000000100088ccc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100088bf4

@end

