//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITextView.h>

@interface SRSpeechRecognizedCorrectionTextView : UITextView
{
}

- (_Bool)keyboardInput:(id)arg1 shouldInsertText:(id)arg2 isMarkedText:(_Bool)arg3;	// IMP=0x0000000100035f0c
- (void)scrollRectToVisibleInContainingScrollView;	// IMP=0x0000000100035f08
- (_Bool)resignFirstResponder;	// IMP=0x0000000100035e68
- (_Bool)becomeFirstResponder;	// IMP=0x0000000100035de0
- (_Bool)canBecomeFirstResponder;	// IMP=0x0000000100035d90
- (id)undoManager;	// IMP=0x0000000100035d88
- (void)setText:(id)arg1;	// IMP=0x0000000100035ad4
- (void)clearDictationResults;	// IMP=0x0000000100035a88
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000358a4

@end

