//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AFConversationDelegate-Protocol.h"
#import "SRTranscriptStackViewControllerDataSource-Protocol.h"
#import "SRTranscriptStackViewControllerDelegate-Protocol.h"
#import "SiriUISuggestionsViewDelegate-Protocol.h"

@class AFConversation, NSString, SRTranscriptStackViewController, SiriUISuggestionsView;
@protocol SRSuggestionsViewControllerDelegate;

@interface SRSuggestionsViewController : UIViewController <SiriUISuggestionsViewDelegate, SRTranscriptStackViewControllerDelegate, SRTranscriptStackViewControllerDataSource, AFConversationDelegate>
{
    AFConversation *_conversation;	// 8 = 0x8
    SRTranscriptStackViewController *_guideController;	// 16 = 0x10
    id <SRSuggestionsViewControllerDelegate> _delegate;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010002c1d4
@property(nonatomic) __weak id <SRSuggestionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)_canShowWhileLocked;	// IMP=0x000000010002c19c
- (_Bool)suggestionsViewIsInTextInputMode:(id)arg1;	// IMP=0x000000010002c108
- (double)contentWidthForSuggestionsView:(id)arg1;	// IMP=0x000000010002c0ac
- (void)suggestionsView:(id)arg1 didHideVibrantView:(id)arg2;	// IMP=0x000000010002c014
- (double)statusViewHeightForSuggestionsView:(id)arg1;	// IMP=0x000000010002bfb8
- (double)statusBarHeightForSuggestionsView:(id)arg1;	// IMP=0x000000010002bf58
- (void)didShowSuggestionsForSuggestionsView:(id)arg1;	// IMP=0x000000010002bec4
- (void)conversation:(id)arg1 presentationStateDidChangeForItemsAtIndexPaths:(id)arg2;	// IMP=0x000000010002bea8
- (void)siriDidFinishActionsForConversationItemWithIdentifier:(id)arg1 inConversation:(id)arg2;	// IMP=0x000000010002be60
- (void)conversation:(id)arg1 didRemoveItemsWithIdentifiers:(id)arg2 atIndexPaths:(id)arg3 parentItemIdentifiers:(id)arg4;	// IMP=0x000000010002bdec
- (void)conversation:(id)arg1 didUpdateItemsAtIndexPaths:(id)arg2;	// IMP=0x000000010002bdd0
- (void)conversation:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2;	// IMP=0x000000010002bdb4
- (void)transcriptStackViewController:(id)arg1 setTypeToSiriViewHidden:(_Bool)arg2;	// IMP=0x000000010002bdb0
- (_Bool)inTextInputModeForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bd1c
- (void)transcriptStackViewController:(id)arg1 failTest:(id)arg2 withReason:(id)arg3;	// IMP=0x000000010002bd18
- (void)willSendStartRequestForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bd14
- (void)transcriptStackViewController:(id)arg1 didDelayPresentationOfItemsWithIdentifiers:(id)arg2;	// IMP=0x000000010002bd10
- (void)transcriptStackViewController:(id)arg1 willDiscardConversationItemsWithIdentifiers:(id)arg2;	// IMP=0x000000010002bd0c
- (void)transcriptStackViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010002bd08
- (void)transcriptStackViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2 animated:(_Bool)arg3;	// IMP=0x000000010002bd04
- (void)transcriptStackViewController:(id)arg1 didFinishTest:(id)arg2;	// IMP=0x000000010002bd00
- (void)transcriptStackViewController:(id)arg1 willStartTest:(id)arg2;	// IMP=0x000000010002bcfc
- (void)transcriptStackViewController:(id)arg1 viewDidSetContentSizeForTranscriptAtIndex:(long long)arg2;	// IMP=0x000000010002bcf8
- (void)transcriptStackViewController:(id)arg1 requestPasscodeUnlockWithCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002bcf4
- (void)transcriptStackViewController:(id)arg1 didShowGuideStartDate:(id)arg2 endDate:(id)arg3;	// IMP=0x000000010002bcf0
- (void)transcriptStackViewController:(id)arg1 didShowTipWithIdentifier:(id)arg2 startDate:(id)arg3 endDate:(id)arg4 flowID:(id)arg5;	// IMP=0x000000010002bcec
- (void)transcriptStackViewController:(id)arg1 didShowAceViewWithIdentifier:(id)arg2 aceViewClass:(Class)arg3 metricsContext:(id)arg4 forInterval:(double)arg5;	// IMP=0x000000010002bce8
- (void)transcriptStackViewController:(id)arg1 didScrollForInterval:(double)arg2 metricsContext:(id)arg3;	// IMP=0x000000010002bce4
- (void)transcriptStackViewController:(id)arg1 didEditSpeechRecognized:(id)arg2 forInterval:(double)arg3;	// IMP=0x000000010002bce0
- (void)transcriptStackViewController:(id)arg1 shouldPresentPicker:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010002bcdc
- (void)transcriptStackViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2;	// IMP=0x000000010002bcd8
- (void)transcriptStackViewController:(id)arg1 didRequestKeyboardWithVisibility:(_Bool)arg2;	// IMP=0x000000010002bcd4
- (void)transcriptStackViewController:(id)arg1 didDismissViewController:(id)arg2;	// IMP=0x000000010002bcd0
- (void)transcriptStackViewController:(id)arg1 willDismissViewController:(id)arg2;	// IMP=0x000000010002bccc
- (void)transcriptStackViewController:(id)arg1 didPresentViewController:(id)arg2;	// IMP=0x000000010002bcc8
- (void)transcriptStackViewController:(id)arg1 willPresentViewController:(id)arg2;	// IMP=0x000000010002bcc4
- (void)transcriptStackViewController:(id)arg1 setStatusViewHidden:(_Bool)arg2;	// IMP=0x000000010002bcc0
- (void)transcriptStackViewController:(id)arg1 openURL:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010002bcbc
- (void)transcriptStackViewController:(id)arg1 synthesizeSpeechWithPhoneticText:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010002bcb8
- (void)stopSpeakingForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bcb4
- (void)transcriptStackViewController:(id)arg1 speakText:(id)arg2 isPhonetic:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010002bcb0
- (void)cancelRequestForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bcac
- (void)transcriptStackViewController:(id)arg1 didCorrectRecognition:(id)arg2 correctionIdentifier:(id)arg3 forItemAtIndexPath:(id)arg4 userSelectionResults:(id)arg5;	// IMP=0x000000010002bca8
- (void)transcriptStackViewControllerDidResignFirstResponder:(id)arg1;	// IMP=0x000000010002bca4
- (void)transcriptStackViewControllerDidEndEditing:(id)arg1;	// IMP=0x000000010002bca0
- (void)transcriptStackViewControllerWillBeginEditing:(id)arg1;	// IMP=0x000000010002bc9c
- (void)transcriptStackViewControllerRequestKeyboardForTapToEditWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010002bc98
- (void)transcriptStackViewController:(id)arg1 didPresentConversationItemsWithIdentifiers:(id)arg2;	// IMP=0x000000010002bc94
- (void)transcriptStackViewController:(id)arg1 didHideVibrantView:(id)arg2;	// IMP=0x000000010002bc90
- (void)transcriptStackViewControllerDidShowSuggestions:(id)arg1;	// IMP=0x000000010002bc8c
- (void)transcriptStackViewControllerDidExitSiriland:(id)arg1;	// IMP=0x000000010002bc88
- (void)transcriptStackViewControllerWillEnterSiriland:(id)arg1;	// IMP=0x000000010002bc84
- (CDStruct_a82615c4)keyboardInfoForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bc14
- (unsigned long long)deviceLockStateForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bc0c
- (id)transcriptStackViewController:(id)arg1 updatedUserUtteranceForRefId:(id)arg2;	// IMP=0x000000010002bc04
- (id)transcriptStackViewController:(id)arg1 additionalSpeechInterpretationsForRefId:(id)arg2;	// IMP=0x000000010002bbfc
- (id)effectiveCoreLocationBundleForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bbf4
- (_Bool)transcriptStackViewControllerShouldPreventUserInteraction:(id)arg1;	// IMP=0x000000010002bbec
- (_Bool)transcriptStackViewControllerWillShowSuggestions:(id)arg1;	// IMP=0x000000010002bbe4
- (_Bool)transcriptStackViewControllerShouldDelaySuggestions:(id)arg1;	// IMP=0x000000010002bbdc
- (void)transcriptStackViewController:(id)arg1 performAceCommand:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010002bb2c
- (long long)initialDisplayTypeForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bb24
- (double)statusViewHeightForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002bac8
- (struct CGRect)statusBarFrameForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002ba4c
- (double)contentWidthForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002b9f0
- (id)siriEnabledAppListForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002b994
- (id)domainObjectStoreForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002b98c
- (id)conversationForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002b97c
- (long long)siriStateForTranscriptStackViewController:(id)arg1;	// IMP=0x000000010002b974
- (void)keyboardHeightDidChange;	// IMP=0x000000010002b95c
- (void)_createGuideController;	// IMP=0x000000010002b7b0
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010002b720
- (void)animateOut;	// IMP=0x000000010002b680
- (void)showRootGuide;	// IMP=0x000000010002b668
- (void)showGuideStart;	// IMP=0x000000010002b650
- (_Bool)isShowingGuide;	// IMP=0x000000010002b604
- (void)showGuideAnimated:(_Bool)arg1;	// IMP=0x000000010002b4c4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010002b3fc
- (void)hideAcousticIDSpinner;	// IMP=0x000000010002b3bc
- (void)showAcousticIDSpinner;	// IMP=0x000000010002b37c
- (void)_showHeaderText:(id)arg1 subheaderText:(id)arg2 largeSubheaderText:(id)arg3;	// IMP=0x000000010002b214
- (void)showEmptyView;	// IMP=0x000000010002b1b0
- (_Bool)isShowingUserNudge;	// IMP=0x000000010002b0c4
- (void)showUserNudge;	// IMP=0x000000010002b03c
- (void)showGreeting;	// IMP=0x000000010002af94
- (void)showUnavailable;	// IMP=0x000000010002ae28
- (id)_nudgeHeaderText;	// IMP=0x000000010002ad44
- (id)_initialHeaderText;	// IMP=0x000000010002ac60
- (void)loadView;	// IMP=0x000000010002aba8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SiriUISuggestionsView *view; // @dynamic view;

@end

