//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MSDSignedManifest.h"

@interface MSDSignedManifestV7 : MSDSignedManifest
{
}

+ (id)signedManifestFromManifestData:(id)arg1;	// IMP=0x0000000100004d10
- (id)getDataSectionKeys;	// IMP=0x0000000100007024
- (id)originServerForComponent:(id)arg1 andApp:(id)arg2;	// IMP=0x0000000100006f50
- (id)getUserDataList;	// IMP=0x0000000100006ef4
- (id)getSharedDataList;	// IMP=0x0000000100006e98
- (id)getSystemAppDataList;	// IMP=0x0000000100006e3c
- (id)getDataForApp:(id)arg1 fromDataSection:(id)arg2;	// IMP=0x0000000100006d68
- (id)getComponentDataList:(id)arg1;	// IMP=0x0000000100006c58
- (_Bool)checkPlatformTypeForAllComponents;	// IMP=0x00000001000066fc
- (id)getInstallationOrderSystemApps;	// IMP=0x00000001000066f0
- (id)getInstallationOrderAppsPrefix;	// IMP=0x00000001000066e4
- (id)getAppList;	// IMP=0x0000000100006688
- (id)getStandAlonePackageList;	// IMP=0x000000010000662c
- (id)getStandAlonePackageVersion:(id)arg1;	// IMP=0x000000010000639c
- (id)getComponentVersion:(id)arg1;	// IMP=0x000000010000610c
- (id)mergedBackupManifest:(struct _NSRange)arg1;	// IMP=0x0000000100005d60
- (long long)getAppType:(id)arg1;	// IMP=0x0000000100005b60
- (id)getSystemAppDependecies:(id)arg1;	// IMP=0x0000000100005a68
- (id)getAppDependecies:(id)arg1;	// IMP=0x0000000100005970
- (id)getBackupList;	// IMP=0x0000000100005914
- (id)standAlonePackageIdentifierFromOrderItem:(id)arg1;	// IMP=0x000000010000588c
- (id)appIdentifierFromOrderItem:(id)arg1;	// IMP=0x0000000100005804
- (_Bool)isItemStandAlonePackage:(id)arg1;	// IMP=0x00000001000057ec
- (_Bool)isItemApp:(id)arg1;	// IMP=0x00000001000057d4
- (_Bool)isItemSystemAppData:(id)arg1;	// IMP=0x00000001000057bc
- (_Bool)isItemConfigurationProfileBackup:(id)arg1;	// IMP=0x00000001000057a4
- (_Bool)isItemProvisioningProfileBackup:(id)arg1;	// IMP=0x000000010000578c
- (_Bool)isItemSystemContainerBackup:(id)arg1;	// IMP=0x0000000100005774
- (_Bool)isItemBaseBackup:(id)arg1;	// IMP=0x000000010000575c
- (_Bool)isItemBackup:(id)arg1;	// IMP=0x0000000100005744
- (id)initWithManifestData:(id)arg1;	// IMP=0x0000000100004d64

@end

