//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASBudgetPersisting-Protocol.h"

@class NSMutableDictionary, NSString;

@interface _DASSharedMemoryBudgetPersistence : NSObject <_DASBudgetPersisting>
{
    struct {
        unsigned char _field1;
        struct {
            char _field1[32];
            double _field2;
            double _field3;
            unsigned char _field4;
        } _field2[32];
        double _field3;
    } *_currentData;	// 8 = 0x8
    NSMutableDictionary *_budgetToIndex;	// 16 = 0x10
}

+ (id)persistence;	// IMP=0x00000001000079b8
+ (void)initialize;	// IMP=0x0000000100007608
+ (id)log;	// IMP=0x0000000100007594
- (void).cxx_destruct;	// IMP=0x0000000100008b14
@property(retain, nonatomic) NSMutableDictionary *budgetToIndex; // @synthesize budgetToIndex=_budgetToIndex;
- (id)lastModulationDate;	// IMP=0x0000000100008954
- (void)saveModulationDate:(id)arg1;	// IMP=0x00000001000087e0
- (id)loadBudgetsWithExpectedNames:(id)arg1;	// IMP=0x00000001000082c8
- (id)validatedStringFromStoredValue:(char *)arg1 withAllowedNames:(id)arg2;	// IMP=0x000000010000814c
- (void)saveBudgets:(id)arg1;	// IMP=0x0000000100007d28
- (void)updateBudget:(id)arg1;	// IMP=0x0000000100007aec
- (id)init;	// IMP=0x00000001000078c0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

