//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASBudgetManaging-Protocol.h"

@class NSDictionary, NSString, _DASSystemBudgetManager, _DASWidgetRefreshBudgetManager;
@protocol OS_dispatch_queue, OS_os_log;

@interface _DASBudgetManager : NSObject <_DASBudgetManaging>
{
    _DASSystemBudgetManager *_systemBudgetManager;	// 8 = 0x8
    _DASWidgetRefreshBudgetManager *_widgetRefreshBudgetManager;	// 16 = 0x10
    NSObject<OS_os_log> *_log;	// 24 = 0x18
    NSDictionary *_budgets;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_queue;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x0000000100035348
- (void).cxx_destruct;	// IMP=0x0000000100035a14
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSDictionary *budgets; // @synthesize budgets=_budgets;
@property(retain, nonatomic) NSObject<OS_os_log> *log; // @synthesize log=_log;
@property(retain, nonatomic) _DASWidgetRefreshBudgetManager *widgetRefreshBudgetManager; // @synthesize widgetRefreshBudgetManager=_widgetRefreshBudgetManager;
@property(retain, nonatomic) _DASSystemBudgetManager *systemBudgetManager; // @synthesize systemBudgetManager=_systemBudgetManager;
- (void)reportUpdateForActivity:(id)arg1 withDataConsumed:(id)arg2;	// IMP=0x000000010003590c
- (void)reportActivityNoLongerRunningWithParameters:(id)arg1;	// IMP=0x0000000100035890
- (void)reportActivityRunningWithParameters:(id)arg1;	// IMP=0x0000000100035814
- (void)reportActivityNoLongerRunning:(id)arg1;	// IMP=0x000000010003578c
- (void)reportActivityRunning:(id)arg1;	// IMP=0x0000000100035704
- (_Bool)isWidgetRefreshBudget:(id)arg1;	// IMP=0x00000001000356b4
- (void)setCapacity:(double)arg1 forBudgetWithName:(id)arg2;	// IMP=0x0000000100035630
- (void)setBalance:(double)arg1 forBudgetWithName:(id)arg2;	// IMP=0x00000001000355ac
- (void)reinstantiateConfiguredBudgets;	// IMP=0x0000000100035540
- (double)remainingBalanceForBudgetWithName:(id)arg1;	// IMP=0x00000001000354b8
- (id)allBudgets;	// IMP=0x00000001000353f8
- (id)budgetKeyPathForBudgetName:(id)arg1;	// IMP=0x00000001000353e8
- (id)init;	// IMP=0x00000001000352d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

