//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@class UIWebClip;

@interface MCNewWebClipPayloadHandler : MCNewPayloadHandler
{
    UIWebClip *_setAsideClip;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000267f8
- (void)unsetAside;	// IMP=0x0000000100026734
- (void)setAside;	// IMP=0x00000001000265cc
- (_Bool)isInstalled;	// IMP=0x00000001000264dc
- (void)remove;	// IMP=0x0000000100026350
- (id)_findInstalledClipWithIdentifier:(id)arg1;	// IMP=0x00000001000261b0
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100025bd4
- (id)savedWebClipIdentifier;	// IMP=0x0000000100025af0

@end

