//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@class NSMutableSet;

@interface MCNewDefaultsPayloadHandler : MCNewPayloadHandler
{
    NSMutableSet *_changedDomains;	// 32 = 0x20
}

+ (void)removeDefaults:(id)arg1 forDomain:(id)arg2;	// IMP=0x0000000100052768
+ (void)removeDefaults:(id)arg1 forManagedDomain:(id)arg2;	// IMP=0x00000001000525b8
+ (_Bool)addDefaults:(id)arg1 toManagedDomain:(id)arg2;	// IMP=0x00000001000524d0
+ (_Bool)setDefaults:(id)arg1 forManagedDomain:(id)arg2;	// IMP=0x0000000100052374
+ (id)defaultsForManagedDomain:(id)arg1;	// IMP=0x0000000100052298
+ (id)_managedSettingsFolder;	// IMP=0x0000000100052294
- (void).cxx_destruct;	// IMP=0x000000010005316c
- (void)didRemoveOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0000000100053160
- (void)didInstallOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0000000100053154
- (void)_sendCFPreferenceNotification;	// IMP=0x00000001000530e4
- (void)migrateDefaults;	// IMP=0x0000000100052f0c
- (void)unsetAside;	// IMP=0x0000000100052f00
- (void)setAside;	// IMP=0x0000000100052ef4
- (void)remove;	// IMP=0x0000000100052e80
- (void)_remove;	// IMP=0x0000000100052bf0
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100052b08
- (_Bool)_install;	// IMP=0x00000001000527f4
- (id)initWithPayload:(id)arg1 profileHandler:(id)arg2;	// IMP=0x00000001000521fc

@end

