//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ManagedConfiguration/MCRestrictionManager.h>

@class NSDictionary, NSMutableSet, NSNumber;

@interface MCRestrictionManagerWriter : MCRestrictionManager
{
    int _senderPID;	// 8 = 0x8
    NSDictionary *_clientTypeLoaders;	// 16 = 0x10
    NSNumber *_memberQueuePasscodeCompliesWithRestrictions;	// 24 = 0x18
    NSNumber *_memberQueuePasscodeCompliesWithProfileRestrictions;	// 32 = 0x20
    NSMutableSet *_memberQueueRecomputePasscodeComplianceForClientUUID;	// 40 = 0x28
}

+ (id)enforcedAppWhitelistRestrictions;	// IMP=0x000000010005fc5c
+ (id)sharedManager;	// IMP=0x000000010005fc20
- (void).cxx_destruct;	// IMP=0x0000000100067cdc
@property(retain, nonatomic) NSMutableSet *memberQueueRecomputePasscodeComplianceForClientUUID; // @synthesize memberQueueRecomputePasscodeComplianceForClientUUID=_memberQueueRecomputePasscodeComplianceForClientUUID;
@property(retain, nonatomic) NSNumber *memberQueuePasscodeCompliesWithProfileRestrictions; // @synthesize memberQueuePasscodeCompliesWithProfileRestrictions=_memberQueuePasscodeCompliesWithProfileRestrictions;
@property(retain, nonatomic) NSNumber *memberQueuePasscodeCompliesWithRestrictions; // @synthesize memberQueuePasscodeCompliesWithRestrictions=_memberQueuePasscodeCompliesWithRestrictions;
@property(readonly, nonatomic) NSDictionary *clientTypeLoaders; // @synthesize clientTypeLoaders=_clientTypeLoaders;
@property(nonatomic) int senderPID; // @synthesize senderPID=_senderPID;
- (void)recomputeUserRestrictionsAndEffectiveUserSettings;	// IMP=0x00000001000678c8
- (void)recomputeEffectiveUserSettingsPasscode:(id)arg1;	// IMP=0x00000001000677fc
- (void)resetAllSettingsToDefaultsSender:(id)arg1;	// IMP=0x00000001000676b8
- (void)removeValueSetting:(id)arg1 sender:(id)arg2;	// IMP=0x00000001000674ac
- (void)removeBoolSetting:(id)arg1 sender:(id)arg2;	// IMP=0x0000000100067270
- (void)setUnionValues:(id)arg1 forSetting:(id)arg2 sender:(id)arg3;	// IMP=0x0000000100067048
- (void)setIntersectionValues:(id)arg1 forSetting:(id)arg2 sender:(id)arg3;	// IMP=0x0000000100066e20
- (void)setValue:(id)arg1 forSetting:(id)arg2 sender:(id)arg3;	// IMP=0x0000000100066c9c
- (void)setBoolValue:(_Bool)arg1 ask:(_Bool)arg2 forSetting:(id)arg3 sender:(id)arg4;	// IMP=0x0000000100066a78
- (void)setBoolValue:(_Bool)arg1 forSetting:(id)arg2 sender:(id)arg3;	// IMP=0x0000000100066a1c
- (_Bool)setParametersForSettingsByType:(id)arg1 configurationUUID:(id)arg2 toSystem:(_Bool)arg3 user:(_Bool)arg4 passcode:(id)arg5 credentialSet:(id)arg6 sender:(id)arg7;	// IMP=0x0000000100066710
- (_Bool)setParametersForSettingsByType:(id)arg1 sender:(id)arg2;	// IMP=0x0000000100066698
- (_Bool)memberQueueSetParametersForSettingsByType:(id)arg1 configurationUUID:(id)arg2 toSystem:(_Bool)arg3 user:(_Bool)arg4 passcode:(id)arg5 credentialSet:(id)arg6 sender:(id)arg7;	// IMP=0x000000010006639c
- (id)_memberQueueNewUserSettingsWithParametersForSettingsByType:(id)arg1 currentUserSettings:(id)arg2;	// IMP=0x0000000100065f90
- (_Bool)memberQueueRecomputeEffectiveUserSettingsPasscode:(id)arg1 credentialSet:(id)arg2;	// IMP=0x0000000100065210
- (void)memberQueueCommitEffectiveUserSettingsToDiskOldEffectiveUserSettings:(id)arg1;	// IMP=0x0000000100064fa0
- (void)memberQueueCommitUserSettingsToDisk;	// IMP=0x0000000100064da8
- (void)notifyHaveSeenComplianceMessageWithLastLockDate:(id)arg1;	// IMP=0x0000000100064c44
- (void)setShowNagMessage;	// IMP=0x0000000100064b5c
- (void)clearAllPasscodeComplianceCaches;	// IMP=0x0000000100064ad0
- (void)memberQueueClearAllPasscodeComplianceCaches;	// IMP=0x0000000100064a2c
- (void)memberQueueClearProfileRestrictionPasscodeComplianceCache;	// IMP=0x00000001000649b0
- (void)memberQueueClearRestrictionPasscodeComplianceCache;	// IMP=0x0000000100064934
- (void)memberQueueCacheClientRestrictionPasscodeCompliance;	// IMP=0x0000000100064324
- (void)memberQueueMarkToClearPasscodeComplianceCacheWithOldSystemClientRestrictions:(id)arg1 newSystemClientRestrictions:(id)arg2;	// IMP=0x0000000100063e10
- (_Bool)recomputeNagMetadata;	// IMP=0x00000001000630ec
- (_Bool)removeOrphanedClientRestrictions;	// IMP=0x0000000100062cfc
- (id)orphanedClientUUIDsForClientRestrictionDictionary:(id)arg1;	// IMP=0x000000010006274c
- (void)notifyClientsToRecomputeCompliance;	// IMP=0x000000010006256c
- (id)_liveClientUUIDsForClientType:(id)arg1 outLoaderMissing:(_Bool *)arg2;	// IMP=0x00000001000623c4
- (id)orphanCheckUnexemptClientTypes;	// IMP=0x00000001000622f4
- (id)orphanCheckExemptClientTypes;	// IMP=0x00000001000622b4
- (_Bool)setClientRestrictions:(id)arg1 appsAndOptions:(id)arg2 system:(_Bool)arg3 clientType:(id)arg4 clientUUID:(id)arg5 sender:(id)arg6 localizedClientDescription:(id)arg7 localizedWarning:(id)arg8 shouldRecomputeNag:(_Bool)arg9 outRestrictionsChanged:(_Bool *)arg10 outEffectiveSettingsChanged:(_Bool *)arg11 outRecomputedNag:(_Bool *)arg12 outError:(id *)arg13;	// IMP=0x0000000100061a04
- (_Bool)setClientRestrictions:(id)arg1 system:(_Bool)arg2 clientType:(id)arg3 clientUUID:(id)arg4 sender:(id)arg5 localizedClientDescription:(id)arg6 localizedWarning:(id)arg7 shouldRecomputeNag:(_Bool)arg8 outRestrictionsChanged:(_Bool *)arg9 outEffectiveSettingsChanged:(_Bool *)arg10 outRecomputedNag:(_Bool *)arg11 outError:(id *)arg12;	// IMP=0x00000001000618f0
- (_Bool)setClientRestrictions:(id)arg1 clientType:(id)arg2 clientUUID:(id)arg3 sender:(id)arg4 localizedClientDescription:(id)arg5 localizedWarning:(id)arg6 shouldRecomputeNag:(_Bool)arg7 outRestrictionsChanged:(_Bool *)arg8 outEffectiveSettingsChanged:(_Bool *)arg9 outRecomputedNag:(_Bool *)arg10 outError:(id *)arg11;	// IMP=0x00000001000617e0
- (_Bool)setClientRestrictions:(id)arg1 system:(_Bool)arg2 clientType:(id)arg3 clientUUID:(id)arg4 sender:(id)arg5 localizedClientDescription:(id)arg6 localizedWarning:(id)arg7 outRestrictionsChanged:(_Bool *)arg8 outEffectiveSettingsChanged:(_Bool *)arg9 outRecomputedNag:(_Bool *)arg10 outError:(id *)arg11;	// IMP=0x00000001000616cc
- (_Bool)setClientRestrictions:(id)arg1 appsAndOptions:(id)arg2 clientType:(id)arg3 clientUUID:(id)arg4 sender:(id)arg5 localizedClientDescription:(id)arg6 localizedWarning:(id)arg7 outRestrictionsChanged:(_Bool *)arg8 outEffectiveSettingsChanged:(_Bool *)arg9 outRecomputedNag:(_Bool *)arg10 outError:(id *)arg11;	// IMP=0x00000001000615a4
- (_Bool)setClientRestrictions:(id)arg1 clientType:(id)arg2 clientUUID:(id)arg3 sender:(id)arg4 localizedClientDescription:(id)arg5 localizedWarning:(id)arg6 outRestrictionsChanged:(_Bool *)arg7 outEffectiveSettingsChanged:(_Bool *)arg8 outRecomputedNag:(_Bool *)arg9 outError:(id *)arg10;	// IMP=0x0000000100061494
- (_Bool)setAllClientRestrictions:(id)arg1 sender:(id)arg2 outRestrictionsChanged:(_Bool *)arg3 outEffectiveSettingsChanged:(_Bool *)arg4 outRecomputedNag:(_Bool *)arg5 outError:(id *)arg6;	// IMP=0x00000001000611a0
- (_Bool)memberQueueSetSystemClientRestrictions:(id)arg1 userClientRestrictions:(id)arg2 sender:(id)arg3 outRestrictionsChanged:(_Bool *)arg4 outEffectiveSettingsChanged:(_Bool *)arg5 outError:(id *)arg6;	// IMP=0x0000000100060db4
- (_Bool)memberQueueSetAllClientRestrictions:(id)arg1 sender:(id)arg2 outRestrictionsChanged:(_Bool *)arg3 outEffectiveSettingsChanged:(_Bool *)arg4 outError:(id *)arg5;	// IMP=0x0000000100060cf0
- (void)setUserInfo:(id)arg1 forClientUUID:(id)arg2 sender:(id)arg3;	// IMP=0x0000000100060a50
- (void)setUserInfo:(id)arg1 forClientUUID:(id)arg2;	// IMP=0x00000001000609fc
- (void)memberQueueCommitClientRestrictionsToDisk;	// IMP=0x00000001000608a0
- (_Bool)setSystemProfileRestrictions:(id)arg1 userProfileRestrictions:(id)arg2 sender:(id)arg3 outRestrictionsChanged:(_Bool *)arg4 outEffectiveSettingsChanged:(_Bool *)arg5 outAppWhitelistSettingsChanged:(_Bool *)arg6 outRecomputedNag:(_Bool *)arg7 outError:(id *)arg8;	// IMP=0x000000010005fed0
- (void)memberQueueCommitRestrictionsToDisk;	// IMP=0x000000010005fdc0
- (id)_init;	// IMP=0x000000010005fd68

@end

