//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@interface MCSetupAssistantPayloadHandler : MCNewPayloadHandler
{
}

- (void)_removeSetupAssistantSettings;	// IMP=0x0000000100010fdc
- (void)_saveSetupAssistantSettings;	// IMP=0x0000000100010f54
- (void)unsetAside;	// IMP=0x0000000100010f48
- (void)setAside;	// IMP=0x0000000100010f3c
- (void)remove;	// IMP=0x0000000100010ec8
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100010bac

@end

