//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCMContainerClassPath.h"

@interface MCMContainerClassTransientPath : MCMContainerClassPath
{
}

+ (id)_temporaryComponent;	// IMP=0x000000010003dff4
+ (id)_globalTemporaryComponent;	// IMP=0x000000010003dfe8
+ (id)transientURLWithUserIdentity:(id)arg1;	// IMP=0x000000010003df58
+ (id)transientGlobalURL;	// IMP=0x000000010003de74
+ (id)transientGlobalBundleURL;	// IMP=0x000000010003ddd4
+ (id)containerPathForUserIdentity:(id)arg1 containerClass:(unsigned long long)arg2;	// IMP=0x000000010003db30

@end

