//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore29StoreCollectionViewController.h"

#import "UICollectionViewDataSourcePrefetching-Protocol.h"

@class MISSING_TYPE;

@interface _TtC8AppStore27SearchResultsViewController : _TtC8AppStore29StoreCollectionViewController <UICollectionViewDataSourcePrefetching>
{
    MISSING_TYPE *delegate;	// 112 = 0x70
    MISSING_TYPE *presenter;	// 128 = 0x80
    MISSING_TYPE *objectGraph;	// 136 = 0x88
    MISSING_TYPE *appStateController;	// 144 = 0x90
    MISSING_TYPE *artworkLoader;	// 152 = 0x98
    MISSING_TYPE *storeDataProvider;	// 160 = 0xa0
    MISSING_TYPE *artworkIconFetcher;	// 176 = 0xb0
    MISSING_TYPE *searchResultsCollectionViewDataSource;	// 184 = 0xb8
    MISSING_TYPE *noResultsView;	// 192 = 0xc0
    MISSING_TYPE *isLoading;	// 200 = 0xc8
    MISSING_TYPE *isAutoPlayEnabled;	// 201 = 0xc9
    MISSING_TYPE *allowsResultFiltering;	// 202 = 0xca
}

- (void).cxx_destruct;	// IMP=0x0000000100085b08
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100085be4
- (id)initWithCollectionViewLayout:(id)arg1;	// IMP=0x0000000100085bb0
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;	// IMP=0x00000001000859a4
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000858c8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100084f20
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100084dd8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100084c20
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100084a74
- (void)viewDidLoad;	// IMP=0x000000010008474c
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010008420c

@end

