//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore30ArcadeComingSoonViewController : UIViewController
{
    MISSING_TYPE *presenter;	// 8 = 0x8
    MISSING_TYPE *objectGraph;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 24 = 0x18
    MISSING_TYPE *activeComingSoonView;	// 32 = 0x20
    MISSING_TYPE *hasAnimatedBefore;	// 40 = 0x28
    MISSING_TYPE *shouldBePlayingVideo;	// 41 = 0x29
    MISSING_TYPE *overlayView;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000105c4
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010001062c
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100010288
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100010128
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000fff8
- (void)viewDidLoad;	// IMP=0x000000010000fc54
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010000f888

@end

