//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class MISSING_TYPE;

@interface _TtC8AppStore25ShelfDisplayingFlowLayout : UICollectionViewFlowLayout
{
    MISSING_TYPE *multiColumnMinYBySection;	// 8 = 0x8
    MISSING_TYPE *multiColumnOrigins;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100038d68
- (id)invalidationContextForBoundsChange:(struct CGRect)arg1;	// IMP=0x00000001000380a0
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x0000000100037e70
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100037ca4
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100037bf4
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x0000000100037a10
- (void)prepareLayout;	// IMP=0x000000010003736c
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010003727c
- (id)init;	// IMP=0x000000010003725c

@end

