//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore11DividerView : UICollectionReusableView
{
    MISSING_TYPE *separatorView;	// 8 = 0x8
    MISSING_TYPE *separatorInset;	// 16 = 0x10
    MISSING_TYPE *style;	// 4177527432 = 0xf9000288
}

- (void).cxx_destruct;	// IMP=0x000000010018df10
- (void)layoutSubviews;	// IMP=0x000000010018deb0
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010018dca4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010018dafc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010018dadc

@end

