//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSXPCListener.h>

#import "NSXPCListenerDelegate-Protocol.h"
#import "_DKDaemonInterface-Protocol.h"

@class NSString, _DKDataProtectionStateMonitor, _DKKnowledgeStorage, _DKPrivacyPolicyEnforcer, _DKRateLimitPolicyEnforcer;
@protocol _DKSyncCoordinator;

@interface CDKnowledgeDaemon : NSXPCListener <NSXPCListenerDelegate, _DKDaemonInterface>
{
    _DKDataProtectionStateMonitor *_dataProtection;	// 8 = 0x8
    _DKRateLimitPolicyEnforcer *_rateLimitEnforcer;	// 16 = 0x10
    _DKPrivacyPolicyEnforcer *_privacyEnforcer;	// 24 = 0x18
    _DKKnowledgeStorage *_storage;	// 32 = 0x20
    id <_DKSyncCoordinator> _syncCoordinator;	// 40 = 0x28
}

+ (id)defaultUserDaemon;	// IMP=0x000000010001f4e0
+ (id)defaultDaemon;	// IMP=0x000000010001f1f0
- (void).cxx_destruct;	// IMP=0x0000000100021c94
@property(retain, nonatomic) id <_DKSyncCoordinator> syncCoordinator; // @synthesize syncCoordinator=_syncCoordinator;
@property(readonly, nonatomic) _DKKnowledgeStorage *storage; // @synthesize storage=_storage;
- (void)deviceUUIDWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021b4c
- (void)sourceDeviceIdentityWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021a38
- (void)deleteRemoteState:(CDUnknownBlockType)arg1;	// IMP=0x00000001000218c0
- (void)synchronizeWithUrgency:(unsigned long long)arg1 client:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010002171c
- (void)synchronizeWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021594
- (void)registerARPHomeControlNotificationTask;	// IMP=0x0000000100021590
- (void)registerCloudFamilyPredictionTask;	// IMP=0x000000010002158c
- (void)macSleepModelingDataCollectionTasks;	// IMP=0x0000000100021588
- (void)registerCloudPETDataCollectionTask;	// IMP=0x0000000100021584
- (void)registerAirPlayTasks;	// IMP=0x0000000100021580
- (void)registerHomeControlDataCollectionTask;	// IMP=0x000000010002157c
- (void)registerCDInteractionDataCollectionTask;	// IMP=0x0000000100021578
- (void)registerDataCollectionTasks;	// IMP=0x0000000100021534
- (void)confirmDatabaseConnectionWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021418
- (id)confirmDatabaseConnectionError;	// IMP=0x0000000100021348
- (void)reportEventStatistics;	// IMP=0x0000000100021054
- (void)logSizeOfStorage:(id)arg1;	// IMP=0x0000000100020ba0
- (void)maintainPrivacyWithActivity:(id)arg1;	// IMP=0x00000001000208ec
- (void)executeQuery:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100020774
- (void)deleteAllEventsMatchingPredicate:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100020664
- (void)deleteAllEventsInEventStreamNamed:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000205c4
- (void)deleteObjects:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000203c8
- (void)saveObjects:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100020180
- (id)classCError;	// IMP=0x00000001000200b0
- (void)handleError:(id)arg1;	// IMP=0x000000010001ffdc
- (_Bool)isClassCLocked;	// IMP=0x000000010001ffa4
- (id)initWithMachServiceName:(id)arg1 storePath:(id)arg2;	// IMP=0x000000010001faac
- (id)initWithMachServiceName:(id)arg1;	// IMP=0x000000010001fa24
- (id)init;	// IMP=0x000000010001fa0c
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010001f7a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

