//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol OS_dispatch_queue;

@interface MIFreeProfileValidatedAppTracker : NSObject
{
    NSMutableSet *_refs;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_q;	// 16 = 0x10
}

+ (id)sharedTracker;	// IMP=0x0000000100040838
- (void).cxx_destruct;	// IMP=0x0000000100041c5c
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *q; // @synthesize q=_q;
@property(retain, nonatomic) NSMutableSet *refs; // @synthesize refs=_refs;
- (_Bool)removeReferenceForBundle:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100041a48
- (_Bool)_onQueue_removeReferenceForBundle:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000416d0
- (_Bool)addReferenceForApplicationIdentifier:(id)arg1 bundle:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100041404
- (_Bool)_onQueue_addReferenceForApplicationIdentifier:(id)arg1 bundle:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100040fe4
- (_Bool)_onQueue_discoverReferencesWithError:(id *)arg1;	// IMP=0x0000000100040e40
- (_Bool)_onQueue_addAppIdentifierIfCachedOnContainer:(struct container_object_s *)arg1 error:(id *)arg2;	// IMP=0x0000000100040a48
- (void)invalidateCache;	// IMP=0x00000001000409b8
- (id)init;	// IMP=0x00000001000408d8

@end

