//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (nsurlsessiond_Additions)
- (id)_errorDictionaryForPowerlog;	// IMP=0x00000001000089e4
- (id)_cancelledReasonForError;	// IMP=0x000000010000890c
- (_Bool)_errorShouldBeRewritten;	// IMP=0x00000001000088a0
- (_Bool)_errorShouldSuppressWake;	// IMP=0x00000001000087b0
- (_Bool)_shouldRemoveCacheFileForError;	// IMP=0x0000000100008620
- (_Bool)_isPriorityChangedError;	// IMP=0x0000000100008584
- (_Bool)_isRecoverableErrorForBackgroundTask;	// IMP=0x0000000100008268
@end

