//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyAuthChallenge, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyDidReceiveChallenge : PBCodable <NSCopying>
{
    PDURLSessionProxyAuthChallenge *_challenge;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100044a34
@property(retain, nonatomic) PDURLSessionProxyAuthChallenge *challenge; // @synthesize challenge=_challenge;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100044950
- (unsigned long long)hash;	// IMP=0x00000001000448f4
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100044820
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100044770
- (void)copyTo:(id)arg1;	// IMP=0x0000000100044704
- (void)writeTo:(id)arg1;	// IMP=0x00000001000446a0
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100044468
- (id)dictionaryRepresentation;	// IMP=0x0000000100044388
- (id)description;	// IMP=0x00000001000442d4
@property(readonly, nonatomic) _Bool hasChallenge;
@property(readonly, nonatomic) _Bool hasTask;

@end

