//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyCancelTask : PBCodable <NSCopying>
{
    PDURLSessionProxyTaskMessage *_task;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100041d28
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100041ca0
- (unsigned long long)hash;	// IMP=0x0000000100041c88
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100041be8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100041b6c
- (void)copyTo:(id)arg1;	// IMP=0x0000000100041b44
- (void)writeTo:(id)arg1;	// IMP=0x0000000100041b24
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010004193c
- (id)dictionaryRepresentation;	// IMP=0x00000001000418b0
- (id)description;	// IMP=0x00000001000417fc
@property(readonly, nonatomic) _Bool hasTask;

@end

