/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:18:47 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSSet;

@interface RTEventLocationIdentifierMO : NSManagedObject

@property (nonatomic,retain) NSString * name; 
@property (nonatomic,retain) NSNumber * source; 
@property (nonatomic,retain) NSString * calendarIdentifier; 
@property (nonatomic,retain) NSSet * loiHistogramItems; 
+(id)managedObjectWithEventLocationIdentifier:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

