//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVMusicMPRequestViewController.h"

@interface TVMusicLibraryVideosViewController : TVMusicMPRequestViewController
{
}

- (id)_musicVideoAtIndexPath:(id)arg1;	// IMP=0x0000000100036fb4
- (void)_playFromItemAtIndexPath:(id)arg1;	// IMP=0x0000000100036e98
- (void)handlePlayPauseCommand;	// IMP=0x0000000100036cc0
- (id)placeholderImage;	// IMP=0x0000000100036c5c
- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x000000010003697c
- (id)additionalHeaderControls;	// IMP=0x0000000100036870
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100036820
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100036818
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100036808
- (void)_selectedShuffleButton;	// IMP=0x0000000100036758
- (void)_selectedPlayButton;	// IMP=0x00000001000366ac
- (struct CGSize)artworkSize;	// IMP=0x0000000100036698
- (struct CGSize)cellSize;	// IMP=0x0000000100036684
- (struct CGPoint)cellSpacing;	// IMP=0x0000000100036670
- (id)init;	// IMP=0x00000001000365e4

@end

