//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVApplicationControllerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, NSURL, TVApplicationController;

@interface TVMusicJSAppController : NSObject <TVApplicationControllerDelegate, UIViewControllerTransitioningDelegate>
{
    NSURL *_applicationURL;	// 8 = 0x8
    TVApplicationController *_appController;	// 16 = 0x10
}

+ (id)_urlForBagKey:(id)arg1 bagSubkey:(id)arg2;	// IMP=0x000000010000c88c
+ (id)_manageSubscriptionsURL;	// IMP=0x000000010000c768
+ (id)subscriptionsAppController;	// IMP=0x000000010000bdd8
+ (void)initialize;	// IMP=0x000000010000bda4
- (void).cxx_destruct;	// IMP=0x000000010000ca94
@property(retain, nonatomic) TVApplicationController *appController; // @synthesize appController=_appController;
@property(retain, nonatomic) NSURL *applicationURL; // @synthesize applicationURL=_applicationURL;
- (void)_closeApp;	// IMP=0x000000010000c710
- (id)animationControllerForDismissedController:(id)arg1;	// IMP=0x000000010000c5fc
- (void)appController:(id)arg1 evaluateAppJavaScriptInContext:(id)arg2;	// IMP=0x000000010000c554
- (void)appController:(id)arg1 didStopWithOptions:(id)arg2;	// IMP=0x000000010000c474
- (void)appController:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x000000010000c394
- (void)launchApplicationWithNavigationController:(id)arg1 launchOptions:(id)arg2;	// IMP=0x000000010000beb4
- (id)initWithApplicationURL:(id)arg1;	// IMP=0x000000010000be3c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

