//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVPreviewTableViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class MPModelLibraryRequest, MPModelResponse, MPSectionedCollection, NSString, TVInteractionGestureRecognizer, UILabel, UIView;
@protocol MPLazySectionedCollectionDataSource;

@interface TVMusicTableViewController : TVPreviewTableViewController <UIGestureRecognizerDelegate>
{
    MPModelResponse *_lastReceivedResponse;	// 8 = 0x8
    _Bool _visibleOnScreen;	// 16 = 0x10
    _Bool _shouldUpdateOnViewDidAppear;	// 17 = 0x11
    double _headingVerticalOffset;	// 24 = 0x18
    UILabel *_tableHeaderLabel;	// 32 = 0x20
    TVInteractionGestureRecognizer *_playPauseRecognizer;	// 40 = 0x28
    UIView *_tableHeaderView;	// 48 = 0x30
    MPModelLibraryRequest *_libraryRequest;	// 56 = 0x38
    MPSectionedCollection *_mpResults;	// 64 = 0x40
    id <MPLazySectionedCollectionDataSource> _sectionedCollectionDataSource;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x00000001000c7b00
@property(retain, nonatomic) id <MPLazySectionedCollectionDataSource> sectionedCollectionDataSource; // @synthesize sectionedCollectionDataSource=_sectionedCollectionDataSource;
@property(retain, nonatomic) MPSectionedCollection *mpResults; // @synthesize mpResults=_mpResults;
@property(retain, nonatomic) MPModelLibraryRequest *libraryRequest; // @synthesize libraryRequest=_libraryRequest;
@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) TVInteractionGestureRecognizer *playPauseRecognizer; // @synthesize playPauseRecognizer=_playPauseRecognizer;
@property(retain, nonatomic) UILabel *tableHeaderLabel; // @synthesize tableHeaderLabel=_tableHeaderLabel;
@property(nonatomic) double headingVerticalOffset; // @synthesize headingVerticalOffset=_headingVerticalOffset;
- (id)_playbackViewController;	// IMP=0x00000001000c7a00
- (id)_previewViewControllerForIndexPath:(id)arg1;	// IMP=0x00000001000c79f8
- (void)_modelResponseDidInvalidate:(id)arg1;	// IMP=0x00000001000c791c
- (void)_configureTableHeaderView;	// IMP=0x00000001000c7760
- (id)_tableHeaderLabel;	// IMP=0x00000001000c75f8
- (id)tableHeaderTitleAttributedText;	// IMP=0x00000001000c7588
- (void)setTableHeaderTitleAttributedText:(id)arg1;	// IMP=0x00000001000c7504
- (id)tableHeaderTitle;	// IMP=0x00000001000c74b0
- (void)setTableHeaderTitle:(id)arg1;	// IMP=0x00000001000c7444
- (void)_startMusicPlayback;	// IMP=0x00000001000c73d0
- (void)_processResponse:(id)arg1 error:(id)arg2;	// IMP=0x00000001000c7190
- (void)_performRequest;	// IMP=0x00000001000c7058
- (void)_handlePlayPauseButton;	// IMP=0x00000001000c6f7c
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000c6f70
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x00000001000c6ea8
- (id)sectionIndexTitlesForTableView:(id)arg1;	// IMP=0x00000001000c6e54
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000c6dfc
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000c6da8
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000c6d5c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000c6c80
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000c6c20
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000c6bac
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000c6b60
- (void)viewDidLoad;	// IMP=0x00000001000c6a10
- (id)init;	// IMP=0x00000001000c6a00
- (id)initWithLibraryRequest:(id)arg1;	// IMP=0x00000001000c6840

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

