//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVMusicJSDocumentViewController.h"

@class MPModelAlbum, MPModelObject;

@interface TVMusicJSAlbumDetailViewController : TVMusicJSDocumentViewController
{
    MPModelAlbum *_album;	// 8 = 0x8
    MPModelObject *_filterObject;	// 16 = 0x10
}

+ (_Bool)_loadSongPopularityForAlbum:(id)arg1;	// IMP=0x000000010000ecb8
+ (id)_contextDictionaryForAlbumDictionary:(id)arg1;	// IMP=0x000000010000e0b4
+ (id)dictionaryForAlbum:(id)arg1 trackCount:(long long)arg2;	// IMP=0x000000010000d950
+ (void)getDictionaryForAlbum:(id)arg1 filterObject:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000d73c
+ (void)getViewControllerForAlbum:(id)arg1 optionalGenreOrComposer:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000d4d8
+ (id)songsRequestForAlbum:(id)arg1 filterObject:(id)arg2;	// IMP=0x000000010000cda0
- (void).cxx_destruct;	// IMP=0x000000010000f3f0
@property(retain, nonatomic) MPModelObject *filterObject; // @synthesize filterObject=_filterObject;
@property(retain, nonatomic) MPModelAlbum *album; // @synthesize album=_album;
- (_Bool)_handleCommand:(id)arg1;	// IMP=0x000000010000ead4
- (_Bool)_getSongForViewElement:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000e51c
- (_Bool)_handlePlayForViewElement:(id)arg1;	// IMP=0x000000010000e31c
- (_Bool)_handleLongPressForViewElement:(id)arg1;	// IMP=0x000000010000e234
- (_Bool)_handleActionForViewElement:(id)arg1;	// IMP=0x000000010000e180
- (id)representedObject;	// IMP=0x000000010000d474
- (void)reloadData;	// IMP=0x000000010000d074
- (_Bool)handleEvent:(id)arg1 targetResponder:(id)arg2 viewElement:(id)arg3 extraInfo:(id *)arg4;	// IMP=0x000000010000cfa8
- (id)songsRequest;	// IMP=0x000000010000cf10
- (id)initWithAlbumDictionary:(id)arg1 albumModel:(id)arg2 optionalGenreOrComposer:(id)arg3;	// IMP=0x000000010000cc4c
- (id)initWithAlbumDictionary:(id)arg1 albumModel:(id)arg2;	// IMP=0x000000010000cad0

@end

