//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface TVMusicBarsView : UIView
{
    NSArray *_barViews;	// 8 = 0x8
    float _repeatCount;	// 16 = 0x10
    unsigned long long _musicBarsStyle;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010007ca60
- (void)_applicationDidBecomeActive:(id)arg1;	// IMP=0x000000010007ca34
- (void)_addAnimationsWithRepeatCount:(float)arg1;	// IMP=0x000000010007c6b4
- (void)_removeAnimations;	// IMP=0x000000010007c570
- (void)_addAnimations;	// IMP=0x000000010007c55c
- (id)_createBarViews;	// IMP=0x000000010007c394
- (void)_setBarHeights:(double)arg1;	// IMP=0x000000010007c220
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010007c158
@property(nonatomic) unsigned long long musicBarsStyle;
- (void)_updateMusicBarsStyle;	// IMP=0x000000010007bdc4
- (void)resumeAnimating;	// IMP=0x000000010007bd2c
- (void)stopAnimating;	// IMP=0x000000010007bca0
- (void)willMoveToWindow:(id)arg1;	// IMP=0x000000010007bc4c
- (void)layoutSubviews;	// IMP=0x000000010007ba98
- (void)dealloc;	// IMP=0x000000010007ba20
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010007b8c4

@end

