//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class _TSKSplitViewController;

@interface TransitionTester : NSObject
{
    long long _animationCount;	// 8 = 0x8
    long long _testsRun;	// 16 = 0x10
    long long _totalTestsToRun;	// 24 = 0x18
    _TSKSplitViewController *_mainViewController;	// 32 = 0x20
}

+ (id)sharedTransitionTester;	// IMP=0x000000010005d3c8
- (void).cxx_destruct;	// IMP=0x000000010005d96c
@property __weak _TSKSplitViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
@property(nonatomic) long long totalTestsToRun; // @synthesize totalTestsToRun=_totalTestsToRun;
@property(nonatomic) long long testsRun; // @synthesize testsRun=_testsRun;
@property(nonatomic) long long animationCount; // @synthesize animationCount=_animationCount;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010005d654
- (void)startPopTransition;	// IMP=0x000000010005d5f4
- (void)startPushTransition;	// IMP=0x000000010005d4b8
- (void)runTest;	// IMP=0x000000010005d40c

@end

