//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "TVSettingsTapToAddUserManagerDelegate-Protocol.h"

@class NSString, TVSettingsTapToAddUserManager, TVSettingsTapToSetupView, UIImageView, UIView;
@protocol TVSettingsTapToAddNewUserViewControllerDelegate;

@interface TVSettingsTapToAddNewUserViewController : TSKViewController <TVSettingsTapToAddUserManagerDelegate>
{
    long long _profileType;	// 8 = 0x8
    id <TVSettingsTapToAddNewUserViewControllerDelegate> _delegate;	// 16 = 0x10
    TVSettingsTapToSetupView *_tapToSetupView;	// 24 = 0x18
    UIView *_initialOptionsContainerView;	// 32 = 0x20
    UIImageView *_imageView;	// 40 = 0x28
    TVSettingsTapToAddUserManager *_tapToAddUserManager;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000de588
@property(retain, nonatomic) TVSettingsTapToAddUserManager *tapToAddUserManager; // @synthesize tapToAddUserManager=_tapToAddUserManager;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *initialOptionsContainerView; // @synthesize initialOptionsContainerView=_initialOptionsContainerView;
@property(retain, nonatomic) TVSettingsTapToSetupView *tapToSetupView; // @synthesize tapToSetupView=_tapToSetupView;
@property(nonatomic) __weak id <TVSettingsTapToAddNewUserViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long profileType; // @synthesize profileType=_profileType;
- (void)_menuPressed:(id)arg1;	// IMP=0x00000001000de470
- (void)_signInManually:(id)arg1;	// IMP=0x00000001000de414
- (void)_showTapToSetupView;	// IMP=0x00000001000ddf4c
- (void)tapToAddUserManager:(id)arg1 didFinishWithError:(id)arg2;	// IMP=0x00000001000ddc9c
- (void)tapToAddUserManagerDidFinish:(id)arg1;	// IMP=0x00000001000ddc88
- (void)tapToAddUserManagerDidStart:(id)arg1;	// IMP=0x00000001000ddbc8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000ddacc
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000dda74
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000dda1c
- (void)viewDidLoad;	// IMP=0x00000001000dcc68
- (void)dealloc;	// IMP=0x00000001000dcbfc
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000dcbb8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

