//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TVSettingsIPEntryViewDelegate-Protocol.h"

@class NSString, TVSettingsIPEntryView, UILabel;
@protocol TVSettingsIPEntryViewControllerDelegate;

@interface TVSettingsIPEntryViewController : UIViewController <TVSettingsIPEntryViewDelegate>
{
    UILabel *_titleLabel;	// 8 = 0x8
    UILabel *_promptLabel;	// 16 = 0x10
    TVSettingsIPEntryView *_ipEntryView;	// 24 = 0x18
    NSString *_prompt;	// 32 = 0x20
    id <TVSettingsIPEntryViewControllerDelegate> _delegate;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001000d9ef0
@property(nonatomic) __weak id <TVSettingsIPEntryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *prompt; // @synthesize prompt=_prompt;
- (id)_ipEntryView;	// IMP=0x00000001000d9e3c
- (void)ipEntryViewDidFinishEditing:(id)arg1;	// IMP=0x00000001000d9d98
@property(copy, nonatomic) NSString *ipAddress;
- (void)setTitle:(id)arg1;	// IMP=0x00000001000d9c10
- (id)preferredFocusEnvironments;	// IMP=0x00000001000d9b58
- (_Bool)becomeFirstResponder;	// IMP=0x00000001000d9b40
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000d9950
- (void)loadView;	// IMP=0x00000001000d95ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

