//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVOutputDeviceDiscoverySession, NSArray, NSMutableArray, NSString;
@protocol HMMediaDestination, OS_dispatch_semaphore;

@interface TVSettingsHDMIEnforcer : NSObject
{
    _Bool _didDiscoverHDMI;	// 8 = 0x8
    _Bool _setHDMICancelled;	// 9 = 0x9
    AVOutputDeviceDiscoverySession *_discoverySession;	// 16 = 0x10
    NSArray *_preferredOutputDevices;	// 24 = 0x18
    NSMutableArray *_availablePreferredOutputDevices;	// 32 = 0x20
    id <HMMediaDestination> _preferredMediaDestination;	// 40 = 0x28
    NSString *_mediaDestinationDeviceID;	// 48 = 0x30
    NSObject<OS_dispatch_semaphore> *_waitForHDMI;	// 56 = 0x38
    CDUnknownBlockType _completion;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000ba388
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool setHDMICancelled; // @synthesize setHDMICancelled=_setHDMICancelled;
@property(nonatomic) _Bool didDiscoverHDMI; // @synthesize didDiscoverHDMI=_didDiscoverHDMI;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *waitForHDMI; // @synthesize waitForHDMI=_waitForHDMI;
@property(retain, nonatomic) NSString *mediaDestinationDeviceID; // @synthesize mediaDestinationDeviceID=_mediaDestinationDeviceID;
@property(retain, nonatomic) id <HMMediaDestination> preferredMediaDestination; // @synthesize preferredMediaDestination=_preferredMediaDestination;
@property(copy, nonatomic) NSMutableArray *availablePreferredOutputDevices; // @synthesize availablePreferredOutputDevices=_availablePreferredOutputDevices;
@property(copy, nonatomic) NSArray *preferredOutputDevices; // @synthesize preferredOutputDevices=_preferredOutputDevices;
@property(retain, nonatomic) AVOutputDeviceDiscoverySession *discoverySession; // @synthesize discoverySession=_discoverySession;
- (void)relinquishHDMIEnforcement;	// IMP=0x00000001000b9f48
- (void)outputDevicesDidChange;	// IMP=0x00000001000b9e14
- (void)discoverySessionDidChangeAvailableOutputDevices;	// IMP=0x00000001000b97b0
- (void)completeWithError:(id)arg1;	// IMP=0x00000001000b96dc
- (void)cancel;	// IMP=0x00000001000b9634
- (void)startWaitingForHDMI;	// IMP=0x00000001000b94f0
- (void)enforceHDMIOutput;	// IMP=0x00000001000b8e4c
- (_Bool)isCurrentOutputDeviceHDMI;	// IMP=0x00000001000b8d74
- (double)enforcementTimeout;	// IMP=0x00000001000b8d30
- (id)currentOutputDevices;	// IMP=0x00000001000b8cd4
- (id)initWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b8bd0

@end

