//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@class NSTimer, TVSBluetoothDevice;

@interface TVSettingsBluetoothRecognizer : UIGestureRecognizer
{
    struct __IOHIDEventSystemClient *_hidSystemClient;	// 8 = 0x8
    unsigned long long _matchingSenderID;	// 16 = 0x10
    NSTimer *_continousTimer;	// 24 = 0x18
    unsigned int _touchCount;	// 32 = 0x20
    _Bool _continuous;	// 36 = 0x24
    TVSBluetoothDevice *_matchingPhysicalDevice;	// 40 = 0x28
}

+ (_Bool)_shouldDefaultToTouches;	// IMP=0x000000010008e0e4
- (void).cxx_destruct;	// IMP=0x000000010008ec3c
@property(copy, nonatomic) TVSBluetoothDevice *matchingPhysicalDevice; // @synthesize matchingPhysicalDevice=_matchingPhysicalDevice;
@property(nonatomic, getter=isContinuous) _Bool continuous; // @synthesize continuous=_continuous;
- (void)_continuousEvent;	// IMP=0x000000010008ebfc
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010008eb54
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010008eaac
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010008e9dc
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010008e8c8
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010008e7b4
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010008e6a8
- (_Bool)_matchesDeviceOfEvent:(id)arg1;	// IMP=0x000000010008e158
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x000000010008e0ec

@end

