//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsHomeKitTCCViewController : TSKViewController
{
}

- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000b7e68
- (id)loadSettingGroups;	// IMP=0x00000001000b7c24
- (id)facade;	// IMP=0x00000001000b7c10

@end

