//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKAppIconPreviewViewController, TSKSettingItem, TVSettingsAppsFacade;

@interface TVSettingsAppsViewController : TSKViewController
{
    TVSettingsAppsFacade *_appsFacade;	// 8 = 0x8
    TSKSettingItem *_lastFocusedItem;	// 16 = 0x10
    TSKAppIconPreviewViewController *_appIconPreviewViewController;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100096344
@property(retain, nonatomic) TSKAppIconPreviewViewController *appIconPreviewViewController; // @synthesize appIconPreviewViewController=_appIconPreviewViewController;
@property(retain, nonatomic) TSKSettingItem *lastFocusedItem; // @synthesize lastFocusedItem=_lastFocusedItem;
@property(retain, nonatomic) TVSettingsAppsFacade *appsFacade; // @synthesize appsFacade=_appsFacade;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100095eb0
- (void)tableView:(id)arg1 didReceivePhysicalPlayForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100095df4
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100095bb4
- (id)loadSettingGroups;	// IMP=0x0000000100094de0
- (void)dealloc;	// IMP=0x0000000100094d74
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100094ce0

@end

