//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, TVSettingsUser, TVSettingsUserProfileFacade;

@interface TVSettingsUserAppleIDServiceViewController : TSKViewController <UIGestureRecognizerDelegate>
{
    TVSettingsUser *_user;	// 8 = 0x8
    long long _serviceType;	// 16 = 0x10
    TVSettingsUserProfileFacade *_profileFacade;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010004173c
@property(retain, nonatomic) TVSettingsUserProfileFacade *profileFacade; // @synthesize profileFacade=_profileFacade;
@property(nonatomic) long long serviceType; // @synthesize serviceType=_serviceType;
@property(retain, nonatomic) TVSettingsUser *user; // @synthesize user=_user;
- (void)_menuPressed:(id)arg1;	// IMP=0x0000000100041688
- (void)_presentGameCenterAboutFriends:(id)arg1;	// IMP=0x0000000100041504
- (id)_gameCenterOptions;	// IMP=0x0000000100040f1c
- (void)_signOut:(id)arg1;	// IMP=0x0000000100040a70
- (void)_signIn:(id)arg1;	// IMP=0x0000000100040a48
- (id)_appleIdOptions;	// IMP=0x0000000100040114
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x00000001000400c0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010003ffd8
- (id)loadSettingGroups;	// IMP=0x000000010003ff08
- (void)viewDidLoad;	// IMP=0x000000010003fe3c
- (void)dealloc;	// IMP=0x000000010003fdd0
- (id)initWithUser:(id)arg1 serviceType:(long long)arg2;	// IMP=0x000000010003fce0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

