//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface UITableView (TVSettingsAdditions)
- (void)tv_updateSectionsWithChanges:(id)arg1;	// IMP=0x0000000100028898
- (void)tv_updateItemsInSection:(unsigned long long)arg1 withChanges:(id)arg2;	// IMP=0x0000000100028770
- (void)tv_updateSectionsWithChange:(id)arg1;	// IMP=0x000000010002862c
- (void)tv_updateItemsInSection:(unsigned long long)arg1 withChange:(id)arg2;	// IMP=0x00000001000283cc
- (id)tv_indexPathsForIndexSet:(id)arg1 withOptions:(unsigned long long)arg2 prefix:(id)arg3;	// IMP=0x0000000100028258
@end

