//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKAccelerometerClient.h"

@interface BKAccelerometerClientUIApp : BKAccelerometerClient
{
    long long _lastOrientation;	// 16 = 0x10
}

- (void)handleOrientationEvent:(long long)arg1 orientationLocked:(_Bool)arg2;	// IMP=0x000000010004ab64
- (void)handleAccelerometerEventWithTimestamp:(double)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4 samplingInterval:(double)arg5;	// IMP=0x000000010004aa48
- (void)_queue_invalidate;	// IMP=0x000000010004aa14
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x000000010004a99c
- (id)initWithPid:(int)arg1 sendRight:(id)arg2 queue:(id)arg3;	// IMP=0x000000010004a900

@end

