//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BKDisplayBrightnessController;
@protocol BSInvalidatable;

@interface BKDisplayBrightnessUpdateTransactionManager : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    int _numPendingTransactions;	// 12 = 0xc
    float _systemDisplayBrightness;	// 16 = 0x10
    id <BSInvalidatable> _suppressBrightnessNotifications;	// 24 = 0x18
    BKDisplayBrightnessController *_brightnessController;	// 32 = 0x20
    _Bool _commitPending;	// 40 = 0x28
    _Bool _shouldRestoreSystemBrightness;	// 41 = 0x29
}

+ (id)sharedInstance;	// IMP=0x000000010004917c
- (void).cxx_destruct;	// IMP=0x000000010004914c
- (void)_lock_commitDisplayBrightness;	// IMP=0x000000010004906c
- (void)_endUpdateTransaction:(id)arg1;	// IMP=0x0000000100048ed0
- (void)_beginUpdateTransaction:(id)arg1;	// IMP=0x0000000100048da0
- (void)restoreSystemDisplayBrightness;	// IMP=0x0000000100048d00
- (float)systemDisplayBrightness;	// IMP=0x0000000100048cb8
- (void)setDisplayBrightness:(float)arg1 permanently:(_Bool)arg2;	// IMP=0x0000000100048bf0
- (void)synchronizeALSPreferencesAndSystemDisplayBrightness;	// IMP=0x0000000100048b80
- (id)_initWithBrightnessController:(id)arg1;	// IMP=0x0000000100048aa0

@end

