//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKSystemApplicationServerDelegate-Protocol.h"

@class BKSystemAppHeartbeat, BKSystemApplication, BKSystemApplicationServer, NSLock, NSMapTable, NSMutableOrderedSet, NSString;

@interface BKSystemAppSentinel : NSObject <BKSystemApplicationServerDelegate>
{
    NSLock *_lock;	// 8 = 0x8
    BKSystemApplicationServer *_server;	// 16 = 0x10
    BKSystemApplication *_systemApp;	// 24 = 0x18
    NSMutableOrderedSet *_connectedSystemApps;	// 32 = 0x20
    NSMapTable *_checkinCompletionsBySystemApp;	// 40 = 0x28
    _Bool _readyForSystemApp;	// 48 = 0x30
    _Bool _systemAppBlocked;	// 49 = 0x31
    BKSystemAppHeartbeat *_heartbeat;	// 56 = 0x38
    NSString *_activeAlternateSystemAppBundleIdentifier;	// 64 = 0x40
    unsigned int _enableIdleSleepAssertionID;	// 72 = 0x48
}

+ (id)sharedInstance;	// IMP=0x00000001000482b4
- (void).cxx_destruct;	// IMP=0x0000000100047d78
- (void)server:(id)arg1 systemApp:(id)arg2 hasActions:(id)arg3;	// IMP=0x0000000100047c08
- (void)server:(id)arg1 systemAppFinishBooting:(id)arg2;	// IMP=0x00000001000478ec
- (void)server:(id)arg1 systemAppDisconnected:(id)arg2;	// IMP=0x00000001000476f4
- (void)server:(id)arg1 systemAppCheckedIn:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100047460
- (void)server:(id)arg1 systemAppConnected:(id)arg2;	// IMP=0x0000000100047334
- (_Bool)lock_unblockSystemApp;	// IMP=0x000000010004729c
- (_Bool)lock_blockSystemApp;	// IMP=0x00000001000471a8
- (void)_handleRelaunchRequestFromSystemApp:(id)arg1 withOptions:(unsigned long long)arg2;	// IMP=0x00000001000470bc
- (void)lock_updatePrimarySystemApp;	// IMP=0x00000001000469fc
- (void)lock_bootstrapSystemApp;	// IMP=0x000000010004689c
- (_Bool)unblockSystemApp;	// IMP=0x0000000100046848
- (_Bool)blockSystemApp;	// IMP=0x00000001000467f4
- (_Bool)ping;	// IMP=0x0000000100046684
- (void)allowSystemAppCheckIn;	// IMP=0x0000000100046634
- (void)startSystemAppCheckInServer;	// IMP=0x0000000100046624
- (id)systemShellState;	// IMP=0x0000000100046570
- (id)systemApplications;	// IMP=0x00000001000464f4
- (id)systemApp;	// IMP=0x00000001000464a8
@property(copy) NSString *activeAlternateSystemAppBundleIdentifier;
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x000000010004624c
- (id)init;	// IMP=0x0000000100046138

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

