//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKHIDEventDispatcher-Protocol.h"

@class BKHIDSystemInterface, NSMutableDictionary, NSString;

@interface BKTouchDeliveryGenericGestureFocusObserver : NSObject <BKHIDEventDispatcher>
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    NSMutableDictionary *_lock_destinationPerDisplayUUID;	// 16 = 0x10
    BKHIDSystemInterface *_HIDSystem;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010003f488
- (void).cxx_destruct;	// IMP=0x000000010003f458
@property(retain, nonatomic) BKHIDSystemInterface *HIDSystem; // @synthesize HIDSystem=_HIDSystem;
- (void)postEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;	// IMP=0x000000010003f310
- (void)postEvent:(struct __IOHIDEvent *)arg1 toDestination:(id)arg2;	// IMP=0x000000010003f300
- (id)destinationsForEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;	// IMP=0x000000010003f0cc
- (void)setEventDestination:(id)arg1 forDisplayUUID:(id)arg2;	// IMP=0x000000010003ef74
- (id)eventDestinationForDisplayUUID:(id)arg1;	// IMP=0x000000010003eea8
- (id)initWithHIDSystem:(id)arg1;	// IMP=0x000000010003ee10

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

