//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBInstanceDependable-Protocol.h"
#import "PBSystemOverlayControllerDelegate-Protocol.h"
#import "PBSystemUIManaging-Protocol.h"

@class NSHashTable, NSMutableDictionary, NSString, PBSystemOverlayController, UIApplicationSceneDeactivationAssertion;
@protocol BSInvalidatable, OS_dispatch_source;

@interface PBBulletinManager : NSObject <PBSystemOverlayControllerDelegate, PBSystemUIManaging, PBInstanceDependable>
{
    _Bool _currentBulletinActive;	// 8 = 0x8
    NSMutableDictionary *_identifiersToBulletinInfos;	// 16 = 0x10
    PBSystemOverlayController *_overlayController;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_bulletinDismissalTimer;	// 32 = 0x20
    NSHashTable *_observers;	// 40 = 0x28
    UIApplicationSceneDeactivationAssertion *_interactiveBulletinSceneDeactivationAssertion;	// 48 = 0x30
    id <BSInvalidatable> _idleTimerAssertion;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x0000000100084a00
+ (id)dependencyDescription;	// IMP=0x0000000100084858
- (void).cxx_destruct;	// IMP=0x0000000100087d7c
@property(retain, nonatomic) id <BSInvalidatable> idleTimerAssertion; // @synthesize idleTimerAssertion=_idleTimerAssertion;
@property(retain, nonatomic) UIApplicationSceneDeactivationAssertion *interactiveBulletinSceneDeactivationAssertion; // @synthesize interactiveBulletinSceneDeactivationAssertion=_interactiveBulletinSceneDeactivationAssertion;
@property(readonly, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *bulletinDismissalTimer; // @synthesize bulletinDismissalTimer=_bulletinDismissalTimer;
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
@property(readonly, nonatomic) NSMutableDictionary *identifiersToBulletinInfos; // @synthesize identifiersToBulletinInfos=_identifiersToBulletinInfos;
@property(nonatomic, getter=isCurrentBulletinActive) _Bool currentBulletinActive; // @synthesize currentBulletinActive=_currentBulletinActive;
- (void)_notifyObserversDidEndFocusOnBulletinViewController:(id)arg1;	// IMP=0x0000000100087a94
- (void)_notifyObserversDidBeginFocusOnBulletinViewController:(id)arg1;	// IMP=0x00000001000878d0
- (void)_notifyObserversDidDismissBulletinViewController:(id)arg1;	// IMP=0x000000010008770c
- (void)_notifyObserversWillPresentBulletinViewController:(id)arg1;	// IMP=0x0000000100087520
- (void)_invalidateIdleTimerAssertion;	// IMP=0x00000001000874c8
- (void)_createIdleTimerAssertion;	// IMP=0x0000000100087274
- (void)_setAcceptsEventFocus:(_Bool)arg1 forViewController:(id)arg2;	// IMP=0x0000000100086f10
- (void)_cancelTimer;	// IMP=0x0000000100086ec4
- (void)_startTimerForViewController:(id)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100086c98
- (void)dismissBulletinViewController:(id)arg1;	// IMP=0x00000001000867f8
- (void)updateBulletinViewControllerTimeout:(id)arg1 timeoutInSeconds:(double)arg2;	// IMP=0x00000001000863f4
- (void)presentBulletinViewController:(id)arg1 withTimeoutInSeconds:(double)arg2;	// IMP=0x0000000100085e6c
- (void)overlayController:(id)arg1 didCancelSession:(id)arg2 withContext:(id)arg3;	// IMP=0x0000000100085c80
- (void)overlayController:(id)arg1 didDismissSession:(id)arg2;	// IMP=0x00000001000859f4
- (void)overlayController:(id)arg1 didPresentSession:(id)arg2;	// IMP=0x0000000100085758
- (void)removeObserver:(id)arg1;	// IMP=0x00000001000856f0
- (void)addObserver:(id)arg1;	// IMP=0x0000000100085688
- (_Bool)dismissOrShrinkCurrentBulletin;	// IMP=0x000000010008530c
- (void)activateCurrentBulletin;	// IMP=0x0000000100085150
- (_Bool)shouldActivateCurrentBulletinForAction:(unsigned long long)arg1;	// IMP=0x000000010008500c
@property(readonly, nonatomic, getter=isPresenting) _Bool presenting;
- (id)init;	// IMP=0x0000000100084b00

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

