//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBInstanceDependable-Protocol.h"
#import "PBOpenAppTransitionObserver-Protocol.h"
#import "PBOpenAppTransitioner-Protocol.h"
#import "TVSSerialTransactionManagerObserver-Protocol.h"

@class NSHashTable, NSMutableArray, NSMutableOrderedSet, NSString, PBOpenAppTransition, TVSConcurrentTransactionManager, TVSSerialTransactionManager;

@interface PBDefaultOpenAppTransitioner : NSObject <PBOpenAppTransitionObserver, TVSSerialTransactionManagerObserver, PBOpenAppTransitioner, PBInstanceDependable>
{
    TVSSerialTransactionManager *_foregroundOpenAppTransactionManager;	// 8 = 0x8
    TVSConcurrentTransactionManager *_backgroundOpenAppTransactionManager;	// 16 = 0x10
    NSHashTable *_openAppObservers;	// 24 = 0x18
    NSMutableArray *_coldBootQueuedTransitions;	// 32 = 0x20
    NSMutableOrderedSet *_deepLinkingAppHistory;	// 40 = 0x28
    PBOpenAppTransition *_activeTransition;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x0000000100091704
+ (id)dependencyDescription;	// IMP=0x000000010009164c
- (void).cxx_destruct;	// IMP=0x0000000100094704
@property(retain, nonatomic) PBOpenAppTransition *activeTransition; // @synthesize activeTransition=_activeTransition;
@property(readonly, nonatomic) NSMutableOrderedSet *deepLinkingAppHistory; // @synthesize deepLinkingAppHistory=_deepLinkingAppHistory;
@property(readonly, nonatomic) NSMutableArray *coldBootQueuedTransitions; // @synthesize coldBootQueuedTransitions=_coldBootQueuedTransitions;
@property(readonly, nonatomic) NSHashTable *openAppObservers; // @synthesize openAppObservers=_openAppObservers;
@property(readonly, nonatomic) TVSConcurrentTransactionManager *backgroundOpenAppTransactionManager; // @synthesize backgroundOpenAppTransactionManager=_backgroundOpenAppTransactionManager;
@property(readonly, nonatomic) TVSSerialTransactionManager *foregroundOpenAppTransactionManager; // @synthesize foregroundOpenAppTransactionManager=_foregroundOpenAppTransactionManager;
- (void)transactionManager:(id)arg1 didInterruptTransaction:(id)arg2 forTransaction:(id)arg3;	// IMP=0x0000000100094444
- (void)transactionManager:(id)arg1 willInterruptTransaction:(id)arg2 forTransaction:(id)arg3;	// IMP=0x00000001000941bc
- (void)transactionManager:(id)arg1 didCompleteTransaction:(id)arg2;	// IMP=0x0000000100093c98
- (void)transactionManager:(id)arg1 willBeginTransaction:(id)arg2;	// IMP=0x0000000100093a64
- (void)openAppTransition:(id)arg1 willReportSystemCompletionWithError:(id)arg2;	// IMP=0x0000000100093990
- (void)openAppTransitionWillStartAnimation:(id)arg1;	// IMP=0x00000001000937cc
- (void)openAppTransition:(id)arg1 willLaunchProcess:(id)arg2;	// IMP=0x00000001000935dc
- (void)_handleDeepLinkingForTransaction:(id)arg1;	// IMP=0x0000000100092ef8
- (void)_deactivateSceneHandle:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000929a0
- (void)_deactivateFocusedAppWithOptions:(id)arg1;	// IMP=0x0000000100092550
- (void)_addOpenAppTransitionIfPossible:(id)arg1;	// IMP=0x0000000100091de0
- (void)removeObserver:(id)arg1;	// IMP=0x0000000100091d78
- (void)addObserver:(id)arg1;	// IMP=0x0000000100091d10
- (void)handleFocusedAppRequestDeactivationFromFailure:(_Bool)arg1;	// IMP=0x0000000100091bd4
- (void)addOpenAppTransition:(id)arg1;	// IMP=0x0000000100091b6c
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
- (id)init;	// IMP=0x0000000100091804

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

