//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "XBSnapshotDataProvider-Protocol.h"

@class NSString, UIImage, XBSnapshotDataProviderContext;

@interface PBDefaultLaunchImageDataProvider : NSObject <XBSnapshotDataProvider>
{
    _Bool _imageNotFound;	// 8 = 0x8
    XBSnapshotDataProviderContext *_context;	// 16 = 0x10
    UIImage *_cachedImage;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100165054
@property(readonly, nonatomic) _Bool imageNotFound; // @synthesize imageNotFound=_imageNotFound;
@property(readonly, nonatomic) UIImage *cachedImage; // @synthesize cachedImage=_cachedImage;
@property(readonly, retain, nonatomic) XBSnapshotDataProviderContext *context; // @synthesize context=_context;
- (void)invalidateImage;	// IMP=0x0000000100164f9c
- (id)fetchImage;	// IMP=0x0000000100164734
- (id)initWithBundleIdentifier:(id)arg1 scaleFactor:(double)arg2;	// IMP=0x00000001001645c8
- (id)init;	// IMP=0x0000000100164590

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

