//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBSDisplayManagerServiceInterface-Protocol.h"

@class NSString, PBSystemServiceConnection;

@interface PBDisplayManagerService : NSObject <PBSDisplayManagerServiceInterface>
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000a4204
@property(readonly, nonatomic) __weak PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void)enableAtmos:(_Bool)arg1;	// IMP=0x00000001000a3ff0
- (void)enableModeSwitchingForFrameRate:(_Bool)arg1;	// IMP=0x00000001000a3e0c
- (void)enableModeSwitchingForDynamicRange:(_Bool)arg1;	// IMP=0x00000001000a3c28
- (void)fetchCurrentDisplayStateWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a3a14
- (void)displayAssistantDidCompleteForKind:(id)arg1;	// IMP=0x00000001000a37d0
- (void)setAudioLatency:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001000a3540
- (void)displayAssistantDidStartForKind:(id)arg1;	// IMP=0x00000001000a3304
- (void)removeCableCheckHistory;	// IMP=0x00000001000a3174
- (void)forgetDisplaysForDisplayAssistant;	// IMP=0x00000001000a2fe4
- (void)presentDisplayAssistantWithRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a2d58
- (void)handleRegionChangeWithNewCountryCode:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a2acc
- (void)wakeDisplayWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a2898
- (void)sleepDisplayWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a2664
- (void)updateDisplayManagerWithRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a23d8
- (_Bool)ensuredValidEntitlementWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a2144
- (void)invalidate;	// IMP=0x00000001000a2070
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x00000001000a1f88
- (id)init;	// IMP=0x00000001000a1f50

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

