//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBInstanceDependable-Protocol.h"
#import "PBOpenAppTransitionerObserver-Protocol.h"
#import "PBPowerManagementImplementor-Protocol.h"

@class NSMutableArray, NSString;
@protocol PBPowerManagementImplementor;

@interface PBPowerManager : NSObject <PBPowerManagementImplementor, PBOpenAppTransitionerObserver, PBInstanceDependable>
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    id <PBPowerManagementImplementor> _implementor;	// 16 = 0x10
    NSMutableArray *_observerWrappers;	// 24 = 0x18
    NSMutableArray *_liveObservers;	// 32 = 0x20
    unsigned long long _reason;	// 40 = 0x28
    long long _powerState;	// 48 = 0x30
}

+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100007814
+ (id)sharedInstance;	// IMP=0x0000000100007520
+ (id)dependencyDescription;	// IMP=0x0000000100007354
- (void).cxx_destruct;	// IMP=0x000000010000bbc0
- (void)powerManagerDidWakeSystem:(id)arg1;	// IMP=0x000000010000baac
- (void)powerManager:(id)arg1 willWakeSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000b608
- (void)powerManagerDidSleepSystem:(id)arg1;	// IMP=0x000000010000b314
- (void)powerManager:(id)arg1 willSleepSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000af00
- (void)finishInitialization;	// IMP=0x000000010000ab84
- (void)_locked_changeStateWithReason:(unsigned long long)arg1;	// IMP=0x0000000100009ba4
- (void)_automaticSleepDevice:(CDUnknownBlockType)arg1;	// IMP=0x000000010000917c
- (id)_stringFromReason:(unsigned long long)arg1;	// IMP=0x000000010000907c
- (id)_stringFromWakeReason:(long long)arg1;	// IMP=0x0000000100008f68
- (id)_stringFromSleepReason:(long long)arg1;	// IMP=0x0000000100008e6c
- (id)_locked_extractObserverList;	// IMP=0x0000000100008d20
- (void)appTransitioner:(id)arg1 willBeginAppTransition:(id)arg2;	// IMP=0x0000000100008acc
- (void)wakeSystemWithReason:(long long)arg1;	// IMP=0x00000001000086c0
- (void)sleepSystemWithReason:(long long)arg1;	// IMP=0x000000010000821c
- (void)__dumpObservers;	// IMP=0x0000000100007e44
- (void)removeObserver:(id)arg1;	// IMP=0x0000000100007c1c
- (void)addObserver:(id)arg1;	// IMP=0x000000010000792c
- (long long)powerState;	// IMP=0x0000000100007910
- (id)init;	// IMP=0x00000001000078b8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

