//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class BKSProcessAssertion, NSMutableSet, NSString, NSXPCListener, PBSystemServiceConnection;
@protocol OS_dispatch_queue;

@interface PBSystemService : NSObject <NSXPCListenerDelegate>
{
    NSObject<OS_dispatch_queue> *_acceptSerialQueue;	// 8 = 0x8
    NSXPCListener *_serviceListener;	// 16 = 0x10
    NSMutableSet *_activeConnections;	// 24 = 0x18
    BKSProcessAssertion *_processAssertion;	// 32 = 0x20
    PBSystemServiceConnection *_defaultKioskConnection;	// 40 = 0x28
}

+ (id)activeConnections;	// IMP=0x000000010011503c
+ (void)notifyDefaultKioskAppPurgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x0000000100114fb0
+ (void)start;	// IMP=0x0000000100114ea8
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100114c98
+ (id)_singleton;	// IMP=0x0000000100114b88
- (void).cxx_destruct;	// IMP=0x0000000100115954
@property(nonatomic) __weak PBSystemServiceConnection *defaultKioskConnection; // @synthesize defaultKioskConnection=_defaultKioskConnection;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010011549c
- (void)_handleInvalidationForConnection:(id)arg1;	// IMP=0x0000000100115350
- (void)_startServices;	// IMP=0x0000000100115274
- (void)_notifyDefaultKioskAppPurgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x000000010011511c
- (id)_activeConnections;	// IMP=0x00000001001150f0
- (id)init;	// IMP=0x0000000100114e70
- (id)_init;	// IMP=0x0000000100114dd0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

