//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBDialogManagerObserver-Protocol.h"
#import "PBUserNotificationDelegate-Protocol.h"
#import "PBUserNotificationViewControllerDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

@interface PBUserNotificationHandler : NSObject <PBUserNotificationViewControllerDelegate, PBDialogManagerObserver, PBUserNotificationDelegate>
{
    NSMutableDictionary *_displayedViewControllers;	// 8 = 0x8
    NSMutableDictionary *_dialogContextsByToken;	// 16 = 0x10
    CDUnknownBlockType _notificationFilter;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000350f0
@property(copy, nonatomic) CDUnknownBlockType notificationFilter; // @synthesize notificationFilter=_notificationFilter;
- (void)_dismissViewController:(id)arg1;	// IMP=0x0000000100034e50
- (void)dialogManager:(id)arg1 willDismissDialogWithContext:(id)arg2 dismissalContext:(id)arg3;	// IMP=0x00000001000349d0
- (void)didCancelUserNotificationViewController:(id)arg1;	// IMP=0x0000000100034930
- (void)userNotificationViewController:(id)arg1 didSelectButtonIndex:(unsigned long long)arg2;	// IMP=0x0000000100034880
- (id)_newViewControllerForNotification:(id)arg1;	// IMP=0x00000001000346e4
- (void)userNotificationCenterDidCancelCFNotification:(id)arg1;	// IMP=0x00000001000345e0
- (void)userNotificationCenterDidReceiveCFNotification:(id)arg1;	// IMP=0x0000000100033d68
- (id)init;	// IMP=0x0000000100033c2c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

