//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE, _TtC6Arcade17DynamicTypeButton;

@interface _TtC6Arcade33ProductPageLinkCollectionViewCell : UICollectionViewCell
{
    MISSING_TYPE *button;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000a7010
@property(nonatomic, readonly) _TtC6Arcade17DynamicTypeButton *accessibilityButton;
@property(nonatomic, readonly) _Bool canBecomeFocused;
- (void)layoutSubviews;	// IMP=0x00000001000a6e9c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000a6ddc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000a6dbc

@end

