//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade22ProductLockupBadgeView : UIView
{
    MISSING_TYPE *captionView;	// 8 = 0x8
    MISSING_TYPE *contentView;	// 16 = 0x10
    MISSING_TYPE *contentViewShouldBaselineAlignWithCaption;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000d98d8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000d9910
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x00000001000d985c
- (void)layoutSubviews;	// IMP=0x00000001000d9830
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000d9538

@end

