//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade22BaseCollectionViewCell.h"

@class MISSING_TYPE, _TtC6Arcade19PrivacyCategoryView;

@interface _TtC6Arcade33PrivacyCategoryCollectionViewCell : _TtC6Arcade22BaseCollectionViewCell
{
    MISSING_TYPE *privacyCategoryView;	// 176 = 0xb0
    MISSING_TYPE *privacyCategory;	// 184 = 0xb8
}

- (void).cxx_destruct;	// IMP=0x00000001001882b8
@property(nonatomic, readonly) _TtC6Arcade19PrivacyCategoryView *accessibilityCategoryView;
- (void)prepareForReuse;	// IMP=0x000000010018821c
@property(nonatomic, readonly) _Bool canBecomeFocused;
- (void)layoutSubviews;	// IMP=0x0000000100188078
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100188058

@end

