//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class BackendXPC;

@interface DiskImageParamsXPC : NSObject <NSSecureCoding, NSCoding>
{
    BackendXPC *_backendXPC;	// 8 = 0x8
    unsigned long long _blockSize;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001000200c0
+ (id)newWithUnlockedBackendXPC:(id)arg1 error:(id *)arg2;	// IMP=0x000000010001f7ec
+ (id)newWithURL:(id)arg1 fileOpenMode:(unsigned short)arg2 error:(id *)arg3;	// IMP=0x000000010001f358
- (void).cxx_destruct;	// IMP=0x000000010002026c
@property(nonatomic) unsigned long long blockSize; // @synthesize blockSize=_blockSize;
@property(retain, nonatomic) BackendXPC *backendXPC; // @synthesize backendXPC=_backendXPC;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100020180
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000200c8
- (id)description;	// IMP=0x000000010001ffc8
@property(readonly, nonatomic) unsigned long long numBlocks;
@property(readonly, nonatomic) _Bool isWritableFormat;
- (unique_ptr_13efee05)createDiskImage;	// IMP=0x000000010001ff50
- (id)initWithBackendXPC:(id)arg1;	// IMP=0x000000010001feb8

@end

