//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface _SATVChoiceButtonContainerView : UIView
{
    UIButton *_preferredButton;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010006d790
@property(nonatomic) __weak UIButton *preferredButton; // @synthesize preferredButton=_preferredButton;
- (id)preferredFocusEnvironments;	// IMP=0x000000010006d6b0
- (_Bool)canBecomeFocused;	// IMP=0x000000010006d62c

@end

