//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVSKStep-Protocol.h"

@class NSString, SATVAirplay2ViewController;
@protocol TVSKStepDelegate;

@interface SATVAirplay2Step : NSObject <TVSKStep>
{
    id <TVSKStepDelegate> stepDelegate;	// 8 = 0x8
    SATVAirplay2ViewController *_airplay2ViewController;	// 16 = 0x10
}

+ (_Bool)_isSupportedForUpgradeWithContext:(id)arg1;	// IMP=0x0000000100004820
+ (_Bool)_isSupportedWithSetupSession:(id)arg1;	// IMP=0x00000001000047cc
+ (id)stableIdentifier;	// IMP=0x0000000100004280
- (void).cxx_destruct;	// IMP=0x0000000100004d3c
@property(retain, nonatomic) SATVAirplay2ViewController *airplay2ViewController; // @synthesize airplay2ViewController=_airplay2ViewController;
@property(nonatomic) __weak id <TVSKStepDelegate> stepDelegate; // @synthesize stepDelegate;
- (void)_completeStepWithDidSetupHomeTheater:(_Bool)arg1;	// IMP=0x0000000100004bc0
- (void)_showAirplay2ViewControllerWithHomeKitInfo:(id)arg1 isUpdateFlow:(_Bool)arg2;	// IMP=0x000000010000494c
- (void)autoAdvance;	// IMP=0x0000000100004748
- (id)executeStepForContext:(id)arg1;	// IMP=0x000000010000428c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

