//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, SATVLoginView, TVSKActivityIndicatorViewController, TVSStateMachine, UISystemInputViewController;

@interface SATVCloudLoginViewController : UIViewController
{
    NSString *_organizationName;	// 8 = 0x8
    NSString *_username;	// 16 = 0x10
    NSString *_password;	// 24 = 0x18
    NSString *_customPrompt;	// 32 = 0x20
    TVSStateMachine *_loginStateMachine;	// 40 = 0x28
    UISystemInputViewController *_systemInputViewController;	// 48 = 0x30
    SATVLoginView *_loginView;	// 56 = 0x38
    TVSKActivityIndicatorViewController *_activityIndicatorViewController;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000828a4
@property(retain, nonatomic) TVSKActivityIndicatorViewController *activityIndicatorViewController; // @synthesize activityIndicatorViewController=_activityIndicatorViewController;
@property(retain, nonatomic) SATVLoginView *loginView; // @synthesize loginView=_loginView;
@property(retain, nonatomic) UISystemInputViewController *systemInputViewController; // @synthesize systemInputViewController=_systemInputViewController;
@property(retain, nonatomic) TVSStateMachine *loginStateMachine; // @synthesize loginStateMachine=_loginStateMachine;
@property(retain, nonatomic) NSString *customPrompt; // @synthesize customPrompt=_customPrompt;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *organizationName; // @synthesize organizationName=_organizationName;
- (void)_authenticateWithUsername:(id)arg1 password:(id)arg2;	// IMP=0x0000000100082738
- (void)_crossFadeLoginViewWithChanges:(CDUnknownBlockType)arg1;	// IMP=0x000000010008255c
- (void)_setUsernamePlaceholder;	// IMP=0x000000010008247c
- (void)_setPasswordPlaceholder;	// IMP=0x000000010008239c
- (void)_showPasswordScreen;	// IMP=0x0000000100081fb4
- (void)_showUsernameScreen;	// IMP=0x0000000100081aac
- (void)_reloadForStateChange;	// IMP=0x0000000100081948
- (void)_setTextFieldText:(id)arg1;	// IMP=0x00000001000818b8
- (void)_clearTextField;	// IMP=0x0000000100081850
- (id)_textFieldText;	// IMP=0x00000001000817bc
- (void)_hideLoginView;	// IMP=0x0000000100081708
- (void)_hideActivityIndicator;	// IMP=0x0000000100081584
- (void)_showActivityIndicator;	// IMP=0x0000000100081470
- (void)_updatePreferredFocusedViewForGridLayoutGuide;	// IMP=0x00000001000812b4
- (void)_textDidChange;	// IMP=0x00000001000811ac
- (void)_menuSelected;	// IMP=0x0000000100081164
- (void)_continueButtonSelected;	// IMP=0x000000010008111c
- (void)_setControlTargets;	// IMP=0x00000001000810a0
- (void)_setViewsForInitialState;	// IMP=0x0000000100080b40
- (void)_registerStateMachineEvents;	// IMP=0x0000000100080690
- (void)_setupSystemInputViewController;	// IMP=0x00000001000804dc
- (void)_doneButtonPressed:(id)arg1;	// IMP=0x000000010008042c
- (_Bool)_enableAutomaticKeyboardPressDone;	// IMP=0x0000000100080424
- (_Bool)_disableAutomaticKeyboardUI;	// IMP=0x000000010008041c
- (id)preferredFocusEnvironments;	// IMP=0x00000001000803a8
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000802b0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000801fc
- (void)viewDidLoad;	// IMP=0x0000000100080024
- (void)loadView;	// IMP=0x000000010007fe7c
- (_Bool)shouldUpdateFocusInContext:(id)arg1;	// IMP=0x000000010007fdec
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010007fcf0

@end

