//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SATVAirplay2DataSource-Protocol.h"
#import "SATVAirplay2DataSourceUpdating-Protocol.h"

@class NSArray, NSHashTable, NSString;
@protocol SATVAirplay2DataSourceObject;

@interface SATVAirplay2HomeKitDataSource : NSObject <SATVAirplay2DataSource, SATVAirplay2DataSourceUpdating>
{
    _Bool _ready;	// 8 = 0x8
    NSArray *_homes;	// 16 = 0x10
    id <SATVAirplay2DataSourceObject> _preferredHome;	// 24 = 0x18
    NSHashTable *_observers;	// 32 = 0x20
}

+ (id)_errorWithCode:(long long)arg1 underlyingError:(id)arg2;	// IMP=0x000000010001e318
+ (void)_moveOrAddLocalAccessoryToRoom:(id)arg1 inHome:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001e034
+ (void)_moveOrAddLocalAccessoryToRoomWithName:(id)arg1 inHome:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001dcbc
+ (_Bool)isHomeKitAvailable;	// IMP=0x000000010001bd20
- (void).cxx_destruct;	// IMP=0x000000010001e47c
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(nonatomic, getter=isReady) _Bool ready; // @synthesize ready=_ready;
@property(copy, nonatomic) id <SATVAirplay2DataSourceObject> preferredHome; // @synthesize preferredHome=_preferredHome;
@property(copy, nonatomic) NSArray *homes; // @synthesize homes=_homes;
- (void)_updateReadyStateAndNotify:(_Bool)arg1;	// IMP=0x000000010001da64
- (void)_notifyDataSourceDidUpdate;	// IMP=0x000000010001d9b4
- (void)_notifyObserversWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010001d84c
- (void)_resetCachedState;	// IMP=0x000000010001d810
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010001d614
@property(readonly, copy) NSString *description;
- (void)updateLocalAccessoryAudioDestinationWithHomeTheaterSpeaker:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001d118
- (void)moveOrAddLocalAccessoryToRoomNamed:(id)arg1 inHome:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001cc30
@property(readonly, nonatomic) _Bool isUpdatingAvailable;
- (void)removeObserver:(id)arg1;	// IMP=0x000000010001cba8
- (void)addObserver:(id)arg1;	// IMP=0x000000010001cb3c
- (id)homeTheaterSpeakersInRoom:(id)arg1 inHome:(id)arg2;	// IMP=0x000000010001c35c
- (id)roomWithName:(id)arg1 inHome:(id)arg2;	// IMP=0x000000010001c1b0
- (id)roomsForHome:(id)arg1;	// IMP=0x000000010001c03c
- (void)dealloc;	// IMP=0x000000010001bc44
- (id)init;	// IMP=0x000000010001bb70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

