/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:06:37 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /usr/lib/libobjc.A.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface Object : _UKNOWN_SUPERCLASS_ {

	Class isa;

}
+(id)initialize;
+(id)retain;
+(void)release;
+(id)class;
+(id)autorelease;
-(id)retain;
-(void)release;
-(id)autorelease;
@end

