//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"

@class NSMapTable, NSOperationQueue, NSString, NSURLSession;
@protocol SWCDownloaderDelegate;

@interface SWCDownloader : NSObject <NSURLSessionDataDelegate>
{
    NSOperationQueue *_queue;	// 8 = 0x8
    NSURLSession *_sessions[4];	// 16 = 0x10
    NSMapTable *_allTaskStates;	// 48 = 0x30
    id <SWCDownloaderDelegate> _delegate;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000100006d80
@property __weak id <SWCDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x00000001000068ec
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x00000001000067a0
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100005c4c
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010000580c
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001000051ac
- (void)enumerateActiveAASAFileDownloadsWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100004e7c
- (void)updateAASAFileForDomain:(id)arg1 downloadRoute:(unsigned char)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100004d28
- (void)updateAASAFileForDomain:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100004c98
- (void)downloadAASAFileForDomain:(id)arg1 downloadRoute:(unsigned char)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100004b44
- (void)downloadAASAFileForDomain:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100004ab4
- (void)receiveSIGTERMSignal;	// IMP=0x000000010000496c
- (id)init;	// IMP=0x00000001000047d0
- (void)_invokeCompletionHandlerForState:(id)arg1 JSONObject:(id)arg2 error:(id)arg3;	// IMP=0x0000000100009b50
- (void)_processDownloadedDataForState:(id)arg1;	// IMP=0x000000010000965c
- (id)_replaceTaskState:(id)arg1;	// IMP=0x0000000100009330
- (void)_resumePendingTasks;	// IMP=0x0000000100008dd8
- (void)_enumerateTaskStatesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100008c10
- (id)_URLRequestWithDomain:(id)arg1 downloadRoute:(unsigned char)arg2;	// IMP=0x00000001000086e0
- (void)_downloadAASAFileForDomain:(id)arg1 downloadRoute:(unsigned char)arg2 discretionary:(_Bool)arg3 completionHandlers:(id)arg4;	// IMP=0x0000000100007de4
- (id)_taskStateForDomain:(id)arg1 downloadRoute:(unsigned char)arg2;	// IMP=0x0000000100007b28
- (unsigned long long)_maximumActiveTaskCountForSessionID:(unsigned char)arg1;	// IMP=0x0000000100007b04
- (id)_sessionForTaskState:(id)arg1;	// IMP=0x00000001000078f8
- (unsigned char)_sessionIDForTaskState:(id)arg1;	// IMP=0x0000000100007878

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

