//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SWCSecurityGuard : NSObject
{
}

+ (id)new;	// IMP=0x00000001000211a8
+ (id)sharedSecurityGuard;	// IMP=0x0000000100021130
- (_Bool)verifyTrust:(struct __SecTrust *)arg1 allowInstalledRootCertificates:(_Bool)arg2 error:(id *)arg3;	// IMP=0x00000001000215a8
- (_Bool)verifyTrust:(struct __SecTrust *)arg1 error:(id *)arg2;	// IMP=0x0000000100021594
- (id)JSONObjectWithSignedJSONData:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000211e4
- (id)init;	// IMP=0x00000001000211b4
- (_Bool)_verifyExtendedValidationOfTrust:(struct __SecTrust *)arg1 error:(id *)arg2;	// IMP=0x00000001000223e0
- (id)_errorForUntrustedRootCertificateOfTrust:(struct __SecTrust *)arg1;	// IMP=0x0000000100022164
- (optional_252cd4e3)_evaluateTrust:(struct __SecTrust *)arg1 allowingKeychains:(_Bool)arg2 error:(id *)arg3;	// IMP=0x0000000100021d80
- (optional_252cd4e3)_evaluateTrust:(struct __SecTrust *)arg1 error:(id *)arg2;	// IMP=0x0000000100021880
- (id)_init;	// IMP=0x000000010002184c

@end

