//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKSpecialPlayerInternal.h"

@interface GKAnonymousPlayerInternal : GKSpecialPlayerInternal
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100133f58
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100133fb0
- (_Bool)isAnonymousPlayer;	// IMP=0x0000000100133fa8
- (id)alias;	// IMP=0x0000000100133f84
- (id)teamPlayerID;	// IMP=0x0000000100133f78
- (id)gamePlayerID;	// IMP=0x0000000100133f6c
- (id)playerID;	// IMP=0x0000000100133f60

@end

