//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKDataDetectorsService : NSObject
{
}

+ (void)loadStoreGamesListWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100126ecc
+ (id)loadLocalGamesList;	// IMP=0x0000000100126d70
+ (void)clearData;	// IMP=0x0000000100126d6c
+ (void)updateData;	// IMP=0x0000000100126bd4
+ (void)pushDataToDataDetectors:(id)arg1;	// IMP=0x0000000100126bd0
+ (id)dataDetectorsEntitiesForDictionary:(id)arg1;	// IMP=0x0000000100126a28
+ (id)dataDetectorsKeywords;	// IMP=0x0000000100126834
+ (id)dataDetectorsStorageFilePath;	// IMP=0x00000001001266ec

@end

