//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface GKIDSRequestManager : NSObject
{
    NSMutableDictionary *_idsRequests;	// 8 = 0x8
}

+ (id)sharedManager;	// IMP=0x00000001001aeda0
@property(retain) NSMutableDictionary *idsRequests; // @synthesize idsRequests=_idsRequests;
- (void)processResponseForiCloudID:(id)arg1 withPlayerID:(id)arg2;	// IMP=0x00000001001af6b0
- (void)requestGKPlayerIDForiCloudIDs:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001af10c
- (void)cancellRequestsforiCloudIDs:(id)arg1;	// IMP=0x00000001001af0ac
- (id)responseDictionaryQueue;	// IMP=0x00000001001aef24
- (void)dealloc;	// IMP=0x00000001001aec64
- (id)init;	// IMP=0x00000001001aec0c

@end

