//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKFriendPlayerInternal.h"

@class NSArray, NSNumber, NSString;

@interface GKLocalPlayerInternal : GKFriendPlayerInternal
{
    NSString *_accountName;	// 232 = 0xe8
    NSArray *_emailAddresses;	// 240 = 0xf0
    NSString *_facebookUserID;	// 248 = 0xf8
    NSNumber *_iCloudUserID;	// 256 = 0x100
    unsigned short _numberOfRequests;	// 264 = 0x108
    unsigned short _numberOfTurns;	// 266 = 0x10a
    unsigned short _numberOfChallenges;	// 268 = 0x10c
    unsigned long long _loginStatus;	// 272 = 0x110
}

+ (id)secureCodedPropertyKeys;	// IMP=0x0000000100132fdc
+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100132f54
+ (id)propertiesToFetch;	// IMP=0x0000000100144e88
+ (id)archivedProfileForEnvironment:(long long)arg1;	// IMP=0x00000001001603f0
+ (void)archiveProfile:(id)arg1 environment:(long long)arg2;	// IMP=0x0000000100160284
+ (id)_profileArchiveURLForEnvironment:(long long)arg1;	// IMP=0x0000000100160230
@property unsigned long long loginStatus; // @synthesize loginStatus=_loginStatus;
- (void)setNumberOfChallenges:(unsigned short)arg1;	// IMP=0x000000010013376c
- (unsigned short)numberOfChallenges;	// IMP=0x000000010013375c
- (void)setNumberOfTurns:(unsigned short)arg1;	// IMP=0x000000010013374c
- (unsigned short)numberOfTurns;	// IMP=0x000000010013373c
- (void)setNumberOfRequests:(unsigned short)arg1;	// IMP=0x000000010013372c
- (unsigned short)numberOfRequests;	// IMP=0x000000010013371c
- (id)iCloudUserID;	// IMP=0x000000010013370c
- (void)setFacebookUserID:(id)arg1;	// IMP=0x0000000100133700
- (id)facebookUserID;	// IMP=0x00000001001336f0
- (void)setEmailAddresses:(id)arg1;	// IMP=0x00000001001336e4
- (id)emailAddresses;	// IMP=0x00000001001336d4
- (void)setAccountName:(id)arg1;	// IMP=0x00000001001336c8
- (id)accountName;	// IMP=0x00000001001336b8
- (int)defaultFamiliarity;	// IMP=0x00000001001336b0
- (void)setICloudUserID:(id)arg1;	// IMP=0x0000000100133648
- (_Bool)isFriend;	// IMP=0x0000000100133640
- (_Bool)isLocalPlayer;	// IMP=0x0000000100133638
- (void)setPhotoPending:(_Bool)arg1;	// IMP=0x0000000100133610
- (_Bool)isPhotoPending;	// IMP=0x00000001001335f8
- (void)setFindable:(_Bool)arg1;	// IMP=0x00000001001335d0
- (_Bool)isFindable;	// IMP=0x00000001001335b8
- (void)setUnderage:(_Bool)arg1;	// IMP=0x0000000100133590
- (_Bool)isUnderage;	// IMP=0x0000000100133534
- (void)setDefaultPrivacyVisibility:(_Bool)arg1;	// IMP=0x000000010013350c
- (_Bool)isDefaultPrivacyVisibility;	// IMP=0x00000001001334f4
- (void)setDefaultNickname:(_Bool)arg1;	// IMP=0x00000001001334cc
- (_Bool)isDefaultNickname;	// IMP=0x00000001001334b4
- (void)setPurpleBuddyAccount:(_Bool)arg1;	// IMP=0x000000010013348c
- (_Bool)isPurpleBuddyAccount;	// IMP=0x0000000100133474
- (id)minimalInternal;	// IMP=0x0000000100133290
- (void)dealloc;	// IMP=0x0000000100132f5c
- (void)updateWithProperties:(id)arg1;	// IMP=0x0000000100145180
- (void)updateWithCacheObject:(id)arg1;	// IMP=0x0000000100144adc

@end

