//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GKDataReader-Protocol.h"

@class GKDataTransport, NSString;

@interface GKPlayerProfileNetworkReader : NSObject <GKDataReader>
{
    int _familiarity;	// 8 = 0x8
    GKDataTransport *_transport;	// 16 = 0x10
}

+ (id)readerWithFamiliarity:(int)arg1 transport:(id)arg2;	// IMP=0x000000010013a27c
@property(nonatomic) int familiarity; // @synthesize familiarity=_familiarity;
@property(retain, nonatomic) GKDataTransport *transport; // @synthesize transport=_transport;
- (id)playerForServerRepresentation:(id)arg1;	// IMP=0x000000010013ad70
- (void)readResources:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000010013a4c0
- (id)poolName;	// IMP=0x000000010013a480
- (id)profileRequestForPlayerIDs:(id)arg1;	// IMP=0x000000010013a374
- (void)dealloc;	// IMP=0x000000010013a32c
- (id)initWithFamiliarity:(int)arg1 transport:(id)arg2;	// IMP=0x000000010013a2bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

