//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKPlayerInternal.h"

@interface GKSpecialPlayerInternal : GKPlayerInternal
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100133f04
- (id)compositeName;	// IMP=0x0000000100133f50
- (_Bool)isLoaded;	// IMP=0x0000000100133f48
- (void)setPhotos:(id)arg1;	// IMP=0x0000000100133f44
- (id)photos;	// IMP=0x0000000100133f3c
- (void)setAlias:(id)arg1;	// IMP=0x0000000100133f38
- (id)alias;	// IMP=0x0000000100133f30
- (void)setTeamPlayerID:(id)arg1;	// IMP=0x0000000100133f2c
- (void)setGamePlayerID:(id)arg1;	// IMP=0x0000000100133f28
- (void)setPlayerID:(id)arg1;	// IMP=0x0000000100133f24
- (id)teamPlayerID;	// IMP=0x0000000100133f1c
- (id)gamePlayerID;	// IMP=0x0000000100133f14
- (id)playerID;	// IMP=0x0000000100133f0c

@end

