//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKMultiplayerBulletin.h"

@class NSDictionary, NSNumber, NSString;

@interface GKTurnBasedMultiplayerBulletin : GKMultiplayerBulletin
{
    _Bool _userTapped;	// 16 = 0x10
    NSString *_matchID;	// 24 = 0x18
    NSNumber *_turnCount;	// 32 = 0x20
    NSDictionary *_localizableMessage;	// 40 = 0x28
    NSString *_exchangeID;	// 48 = 0x30
    NSString *_guestID;	// 56 = 0x38
    NSString *_aggregateDictionaryKey;	// 64 = 0x40
}

+ (_Bool)displayNotification;	// IMP=0x00000001000d593c
+ (_Bool)shouldExpirePlayerList;	// IMP=0x00000001000d5934
+ (_Bool)shouldLoadCacheDetails;	// IMP=0x00000001000d592c
+ (_Bool)shouldLoadCacheList;	// IMP=0x00000001000d5924
+ (_Bool)shouldLoadCacheData;	// IMP=0x00000001000d591c
+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d4df4
+ (_Bool)supportsSecureCoding;	// IMP=0x00000001000d4d5c
@property(readonly) NSString *aggregateDictionaryKey; // @synthesize aggregateDictionaryKey=_aggregateDictionaryKey;
@property(retain) NSString *guestID; // @synthesize guestID=_guestID;
@property(retain) NSString *exchangeID; // @synthesize exchangeID=_exchangeID;
@property(retain) NSDictionary *localizableMessage; // @synthesize localizableMessage=_localizableMessage;
@property _Bool userTapped; // @synthesize userTapped=_userTapped;
@property(retain) NSNumber *turnCount; // @synthesize turnCount=_turnCount;
@property(retain) NSString *matchID; // @synthesize matchID=_matchID;
- (id)description;	// IMP=0x00000001000d8b98
- (void)handleAction:(id)arg1;	// IMP=0x00000001000d8910
- (void)handleAcceptAction;	// IMP=0x00000001000d87e0
- (void)expireAndLoadCaches;	// IMP=0x00000001000d8224
- (void)assembleBulletin;	// IMP=0x00000001000d7d20
- (id)bulletinMessage;	// IMP=0x00000001000d7b5c
- (void *)removePreviousTurnBulletins;	// IMP=0x00000001000d78bc
- (void)declineTurnBasedInviteWithReason:(int)arg1;	// IMP=0x00000001000d74ac
- (void)acceptTurnBasedTurn;	// IMP=0x00000001000d71f8
- (void)invalidateTurnCache;	// IMP=0x00000001000d6ed8
- (void)saveTurnBasedEvent;	// IMP=0x00000001000d6d74
- (void)updateBadgeCount;	// IMP=0x00000001000d6bb8
- (void)loadDataWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000d6230
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000d5fbc
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000d5d0c
- (id)initWithPushNotification:(id)arg1;	// IMP=0x00000001000d5a98
- (void)update;	// IMP=0x00000001000d5944
- (void)dealloc;	// IMP=0x00000001000d4d64

@end

