//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOrderedSet.h>

@interface NSOrderedSet (GKAdditions)
- (id)_gkFilteredOrderedSetUsingPredicate:(id)arg1;	// IMP=0x000000010007afb0
- (id)_gkSortedOrderedSetUsingDescriptors:(id)arg1;	// IMP=0x000000010007af00
- (id)_gkDescriptionWithChildren:(long long)arg1;	// IMP=0x000000010007c57c
- (_Bool)_gkIsEqualToOrderedSet:(id)arg1;	// IMP=0x00000001000ccf80
- (id)_gkFirstObject;	// IMP=0x00000001000ccf74
- (id)_gkDistinctValuesForKeyPath:(id)arg1;	// IMP=0x00000001000cce14
- (id)_gkValuesForKeyPath:(id)arg1;	// IMP=0x00000001000cccb4
- (id)_gkMapDictionaryWithKeyPath:(id)arg1 valueKeyPath:(id)arg2;	// IMP=0x00000001000ccadc
- (id)_gkMapDictionaryWithKeyPath:(id)arg1;	// IMP=0x00000001000ccacc
@end

