//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber;
@protocol OS_dispatch_queue;

@interface PRSystemSettingsMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    _Bool _monitoring;	// 16 = 0x10
    CDUnknownBlockType _airplaneModeChangedHandler;	// 24 = 0x18
    struct __SCPreferences *_radioPrefs;	// 32 = 0x20
    NSNumber *_airplaneModeStatusInternal;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100193af8
@property _Bool monitoring; // @synthesize monitoring=_monitoring;
@property(retain) NSNumber *airplaneModeStatusInternal; // @synthesize airplaneModeStatusInternal=_airplaneModeStatusInternal;
@property struct __SCPreferences *radioPrefs; // @synthesize radioPrefs=_radioPrefs;
@property(copy) CDUnknownBlockType airplaneModeChangedHandler; // @synthesize airplaneModeChangedHandler=_airplaneModeChangedHandler;
@property(readonly) unsigned long long airplaneModeStatus;
- (void)fetchAndUpdateAirplaneModeStatus;	// IMP=0x00000001001939b8
- (void)airplaneModeStatusChanged;	// IMP=0x00000001001937f0
- (_Bool)startMonitoring;	// IMP=0x000000010019363c
- (void)initRadioSCPreferencesRef;	// IMP=0x00000001001935c8
- (void)dealloc;	// IMP=0x000000010019354c
- (id)initWithQueue:(id)arg1;	// IMP=0x00000001001934a8

@end

