//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SystemDiagnosticLogAgent.h"

@interface SystemDiagnosticLogAgentiOS : SystemDiagnosticLogAgent
{
}

- (void)processMessage:(id)arg1 replyWith:(id)arg2;	// IMP=0x0000000100003fac
- (_Bool)getAccessibilityPreferences:(const char *)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100003c08
- (_Bool)getKeyboardPreferences:(const char *)arg1 withTimeout:(double)arg2;	// IMP=0x00000001000036fc
- (_Bool)ASPToolTrace:(const char *)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100003564
- (_Bool)_BTPHYTaskWithTimeout:(long long)arg1;	// IMP=0x00000001000032f8
- (id)_AWDTaskWithTimeout:(long long)arg1;	// IMP=0x0000000100002e40
- (id)_coreMediaTaskWithTimeout:(long long)arg1;	// IMP=0x0000000100002c24

@end

