//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSHashTable, NSOperation, NSOperationQueue;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface CKKSLockStateTracker : NSObject
{
    _Bool _queueIsLocked;	// 8 = 0x8
    int _notify_token;	// 12 = 0xc
    NSOperation *_unlockDependency;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    NSOperationQueue *_operationQueue;	// 32 = 0x20
    NSHashTable *_observers;	// 40 = 0x28
    NSDate *_lastUnlockedTime;	// 48 = 0x30
}

+ (id)globalTracker;	// IMP=0x000000010013d250
+ (_Bool)queryAKSLocked;	// IMP=0x000000010013d14c
- (void).cxx_destruct;	// IMP=0x000000010013cdec
@property(retain) NSDate *lastUnlockedTime; // @synthesize lastUnlockedTime=_lastUnlockedTime;
@property int notify_token; // @synthesize notify_token=_notify_token;
@property(retain) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property _Bool queueIsLocked; // @synthesize queueIsLocked=_queueIsLocked;
@property(retain) NSOperation *unlockDependency; // @synthesize unlockDependency=_unlockDependency;
- (void)addLockStateObserver:(id)arg1;	// IMP=0x000000010013ccb0
- (_Bool)isLockedError:(id)arg1;	// IMP=0x000000010013cc10
- (_Bool)checkErrorChainForLockState:(id)arg1;	// IMP=0x000000010013cb2c
- (_Bool)lockedError:(id)arg1;	// IMP=0x000000010013ca48
- (void)recheck;	// IMP=0x000000010013c9cc
- (void)_onqueueRecheck;	// IMP=0x000000010013c6d4
- (void)resetUnlockDependency;	// IMP=0x000000010013c5e4
- (id)description;	// IMP=0x000000010013c520
@property(readonly) NSDate *lastUnlockTime;
@property(readonly) _Bool isLocked;
- (void)dealloc;	// IMP=0x000000010013c348
- (id)init;	// IMP=0x000000010013c154

@end

