//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSDate, NSDictionary, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface CKKSRateLimiter : NSObject <NSSecureCoding>
{
    NSDictionary *_config;	// 8 = 0x8
    NSMutableDictionary *_buckets;	// 16 = 0x10
    NSDate *_overloadUntil;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010003237c
- (void).cxx_destruct;	// IMP=0x000000010003226c
@property(retain) NSDate *overloadUntil; // @synthesize overloadUntil=_overloadUntil;
@property(retain) NSMutableDictionary *buckets; // @synthesize buckets=_buckets;
@property(retain) NSDictionary *config; // @synthesize config=_config;
- (id)topOffendingAccessGroups:(unsigned long long)arg1;	// IMP=0x0000000100031f60
- (id)diagnostics;	// IMP=0x0000000100031c48
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100031bd0
- (void)trim:(id)arg1;	// IMP=0x0000000100031884
- (void)reset;	// IMP=0x000000010003182c
- (unsigned long long)stateSize;	// IMP=0x00000001000317e0
- (int)judge:(id)arg1 at:(id)arg2 limitTime:(id *)arg3;	// IMP=0x000000010003123c
- (id)consumeTokenFromBucket:(id)arg1 type:(int)arg2 at:(id)arg3;	// IMP=0x0000000100031034
- (int)capacity:(int)arg1;	// IMP=0x0000000100030f50
- (int)rate:(int)arg1;	// IMP=0x0000000100030e6c
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100030c44
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010003088c
- (id)init;	// IMP=0x000000010003087c

@end

