//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface CKKSSQLResult : NSObject
{
    NSString *_stringValue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010002cb24
@property(retain) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (id)asBase64DecodedData;	// IMP=0x000000010002ca70
- (id)asISO8601Date;	// IMP=0x000000010002c9c4
- (id)asNSNumberInteger;	// IMP=0x000000010002c91c
- (id)asString;	// IMP=0x000000010002c910
- (long long)asNSInteger;	// IMP=0x000000010002c8c4
- (_Bool)asBOOL;	// IMP=0x000000010002c878
- (id)init:(id)arg1;	// IMP=0x000000010002c800

@end

