//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UIWindowSceneDelegate-Protocol.h"

@interface _TtC8Podcasts13SceneDelegate : UIResponder <UIWindowSceneDelegate>
{
}

- (id)init;	// IMP=0x0000000100181a1c
- (void)windowScene:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100181960
- (void)scene:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;	// IMP=0x0000000100181888
- (void)scene:(id)arg1 willContinueUserActivityWithType:(id)arg2;	// IMP=0x00000001001817f8
- (void)scene:(id)arg1 continueUserActivity:(id)arg2;	// IMP=0x0000000100181798
- (void)scene:(id)arg1 openURLContexts:(id)arg2;	// IMP=0x0000000100181678
- (void)sceneDidEnterBackground:(id)arg1;	// IMP=0x000000010018165c
- (void)sceneWillEnterForeground:(id)arg1;	// IMP=0x0000000100181640
- (void)sceneWillResignActive:(id)arg1;	// IMP=0x0000000100181624
- (void)sceneDidBecomeActive:(id)arg1;	// IMP=0x0000000100181608
- (void)sceneDidDisconnect:(id)arg1;	// IMP=0x0000000100181604
- (void)scene:(id)arg1 willConnectToSession:(id)arg2 options:(id)arg3;	// IMP=0x0000000100181584

@end

