//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIVisualEffectView;

@interface IMTVBlurredModalViewController : UIViewController
{
    long long _blurEffectStyle;	// 8 = 0x8
    UIVisualEffectView *_blurredBackground;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010016037c
@property(retain, nonatomic) UIVisualEffectView *blurredBackground; // @synthesize blurredBackground=_blurredBackground;
@property(nonatomic) long long blurEffectStyle; // @synthesize blurEffectStyle=_blurEffectStyle;
- (void)loadView;	// IMP=0x00000001001600b8
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100160090
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100160078
- (id)initWithBlurEffectStyle:(long long)arg1;	// IMP=0x0000000100160040
- (id)init;	// IMP=0x000000010015ffcc

@end

