//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface KeychainWrapper : NSObject
{
    NSMutableDictionary *keychainData;	// 8 = 0x8
    NSMutableDictionary *genericPasswordQuery;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000fc230
@property(retain, nonatomic) NSMutableDictionary *genericPasswordQuery; // @synthesize genericPasswordQuery;
@property(retain, nonatomic) NSMutableDictionary *keychainData; // @synthesize keychainData;
- (void)writeToKeychain;	// IMP=0x00000001000fbff4
- (id)secItemFormatToDictionary:(id)arg1;	// IMP=0x00000001000fbe84
- (id)dictionaryToSecItemFormat:(id)arg1;	// IMP=0x00000001000fbd0c
- (void)resetKeychainItem;	// IMP=0x00000001000fbb18
@property(retain, nonatomic) NSString *personId;
- (id)myObjectForKey:(id)arg1;	// IMP=0x00000001000fba90
- (void)mySetObject:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001000fb9dc
- (id)init;	// IMP=0x00000001000fb804

@end

