//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTAnalyticsIdentifier : NSObject
{
}

+ (id)_generateIdentifier;	// IMP=0x000000010005355c
+ (_Bool)resetIdentifiersFromCloudIfNeeded;	// IMP=0x00000001000532e4
+ (_Bool)isCloudAccountChanged;	// IMP=0x000000010005322c
+ (void)resetIdentifiersFromSettings;	// IMP=0x0000000100053104
+ (_Bool)resetIdentifiersIfNeeded;	// IMP=0x0000000100052fdc
+ (void)updateCloudKeychainEnabled;	// IMP=0x0000000100052f20
+ (_Bool)isCloudKeychainEnabled;	// IMP=0x0000000100052eac
+ (void)setCloudPersonId:(id)arg1;	// IMP=0x0000000100052e1c
+ (id)cloudPersonId;	// IMP=0x0000000100052dd0
+ (id)currentAccountId;	// IMP=0x0000000100052d5c
+ (id)localPersonIdAccountId;	// IMP=0x0000000100052cf8
+ (void)setResetNeeded:(_Bool)arg1;	// IMP=0x0000000100052c90
+ (_Bool)isResetNeeded;	// IMP=0x0000000100052c34
+ (void)setLocalPersonIdAccountId:(id)arg1;	// IMP=0x0000000100052bbc
+ (void)setLocalPersonId:(id)arg1;	// IMP=0x0000000100052b0c
+ (id)localPersonId;	// IMP=0x0000000100052a8c
+ (void)resetDeviceId;	// IMP=0x0000000100052a18
+ (id)deviceId;	// IMP=0x00000001000529b4

@end

