//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTDemoUtility : NSObject
{
}

+ (id)_dataArrayStringsForString:(id)arg1;	// IMP=0x00000001000c2820
+ (id)_dataArrayForString:(id)arg1;	// IMP=0x00000001000c25e8
+ (id)demoSortDescriptorsForRecentlyPlayed;	// IMP=0x00000001000c2534
+ (id)demoSortDescriptorsForListenNow;	// IMP=0x00000001000c2480
+ (id)demoRecentlyPlayedContent;	// IMP=0x00000001000c1fec
+ (id)demoListenNowData;	// IMP=0x00000001000c1a7c
+ (unsigned long long)demoListenNowReasonForEpisodeStoreTrackId:(long long)arg1;	// IMP=0x00000001000c1938
+ (_Bool)hasDemoRecentlyPlayedContent;	// IMP=0x00000001000c18e8
+ (_Bool)hasDemoListenNowData;	// IMP=0x00000001000c1898

@end

