//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTPodcastManifest.h"

@interface MTListenNowManifest : MTPodcastManifest
{
}

+ (id)activityTypeSuffix;	// IMP=0x0000000100136d0c
+ (void)createManifestForActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100136b3c
- (void)nextManifest:(CDUnknownBlockType)arg1;	// IMP=0x0000000100136484

@end

