//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PodcastsFoundation/MTPlaylist.h>

#import "IMMetricsDataSource-Protocol.h"

@class MTEpisode, NSString;

@interface MTPlaylist (DB) <IMMetricsDataSource>
+ (id)predicateForMediaLibraryId:(long long)arg1;	// IMP=0x00000001000c70a8
+ (id)predicateForVisiblePlaylistWithUUID:(id)arg1;	// IMP=0x00000001000c7054
+ (id)predicateForFlag:(int)arg1 isTrue:(_Bool)arg2;	// IMP=0x00000001000c6fec
+ (id)topLevelPlaylistsExcludingFoldersPredicate;	// IMP=0x00000001000c6f58
+ (id)containerOrderOptionValues;	// IMP=0x00000001000c6f3c
+ (id)containerOrderOptionArray:(_Bool)arg1;	// IMP=0x00000001000c6dc4
+ (id)stringForContainerOrder:(int)arg1 short:(_Bool)arg2;	// IMP=0x00000001000c6c3c
+ (long long)getITunesPlaylistsCount;	// IMP=0x00000001000c6a20
+ (void)prepareForPlatform:(id)arg1;	// IMP=0x00000001000c4ef4
+ (id)insertNewPlaylistInManagedObjectContext:(id)arg1 uuid:(id)arg2 defaultSettings:(id)arg3;	// IMP=0x00000001000c4d20
+ (id)insertNewPlaylistInManagedObjectContext:(id)arg1;	// IMP=0x00000001000c4c60
+ (id)topLevelPlaylistsPredicate;	// IMP=0x000000010014ded0
+ (id)sortDescriptors;	// IMP=0x0000000100169994
- (_Bool)needsUpdate;	// IMP=0x0000000100030158
- (void)setNeedsUpdate:(_Bool)arg1;	// IMP=0x00000001000300f4
- (id)metricsAdditionalData;	// IMP=0x00000001000c718c
- (id)metricsContentIdentifier;	// IMP=0x00000001000c7138
- (long long)getFolderSubPlaylistsCount;	// IMP=0x00000001000c67e4
@property(readonly, nonatomic) MTEpisode *nextEpisode;
@property(readonly, nonatomic) double totalDuration;
- (void)removeEpisode:(id)arg1 inBulkTransaction:(_Bool)arg2;	// IMP=0x00000001000c6490
- (void)removeEpisode:(id)arg1;	// IMP=0x00000001000c6480
- (void)removeEpisodes:(id)arg1;	// IMP=0x00000001000c62c0
- (void)removePodcastEpisodes:(id)arg1 shouldSave:(_Bool)arg2;	// IMP=0x00000001000c5f08
- (void)removePodcast:(id)arg1;	// IMP=0x00000001000c5c38
- (void)recalculateEpisodeCounts;	// IMP=0x00000001000c5ae8
@property(nonatomic) _Bool hasBeenSynced;
- (_Bool)updateUnplayedCount;	// IMP=0x00000001000c5890
@property(readonly, nonatomic) _Bool isEditable;
- (void)forceUpdate;	// IMP=0x00000001000c5828
@property(nonatomic) _Bool isUngroupedList;
@property(nonatomic) _Bool isItunesSmartPlaylist;
@property(nonatomic) _Bool includesAllPodcasts;
@property(nonatomic) _Bool isBuiltIn;
@property(nonatomic) _Bool isItunesPlaylist;
@property(nonatomic) _Bool isFolder;
- (id)podcasts;	// IMP=0x00000001000c54b0
- (void)setEpisodes:(id)arg1;	// IMP=0x00000001000c53f0
- (void)setPodcasts:(id)arg1;	// IMP=0x00000001000c4ef8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

