//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTRemoteSetPlaybackQueueUtil : NSObject
{
}

+ (id)_entityForFetchRequest:(id)arg1;	// IMP=0x00000001000712d4
+ (void)_destinationForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100071134
+ (long long)requestStatusForMediaRemoteStatus:(unsigned int)arg1;	// IMP=0x00000001000710d8
+ (void)insertPlayerItems:(id)arg1 intoPlaybackQueueAtPosition:(int)arg2;	// IMP=0x0000000100070e28
+ (void)insertEpisodeUuids:(id)arg1 intoPlaybackQueueAtPosition:(int)arg2;	// IMP=0x0000000100070c68
+ (void)decodeAndSetPlaybackQueueFromIdentifiers:(id)arg1 enqueuer:(id)arg2 accountLookupFailed:(_Bool)arg3 startPlayback:(_Bool)arg4 upNextQueueIntent:(unsigned long long)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x00000001000705f8
+ (void)pickRouteAndSwitchToLocalCard:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100070424
+ (void)convertActiveEndpointToBufferedAirPlayWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100070360
+ (void)performRequestAsBufferedAirPlay:(id)arg1;	// IMP=0x00000001000700c8
+ (void)promptBeforePerformingRequestAsBufferedAirPlay:(id)arg1 queueStatus:(unsigned long long)arg2;	// IMP=0x000000010006f110
+ (void)sendPlaybackQueueToLocalDestination:(struct _MRSystemAppPlaybackQueue *)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010006ee48
+ (void)setRemotePlaybackQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010006e7dc

@end

