//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MZKeyValueStoreTransactionProcessing-Protocol.h"

@class MTSubscriptionSyncProcessorConfig, NSMutableArray, NSMutableSet, NSString;

@interface MTSubscriptionSyncProcessor : NSObject <MZKeyValueStoreTransactionProcessing>
{
    NSMutableArray *_podcastKeysToRequest;	// 8 = 0x8
    NSMutableSet *_addedSubscriptions;	// 16 = 0x10
    MTSubscriptionSyncProcessorConfig *_config;	// 24 = 0x18
}

+ (id)subscriptionSyncProcessorSyncKeys;	// IMP=0x0000000100160a64
- (void).cxx_destruct;	// IMP=0x000000010016468c
@property(retain, nonatomic) MTSubscriptionSyncProcessorConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) NSMutableSet *addedSubscriptions; // @synthesize addedSubscriptions=_addedSubscriptions;
@property(retain, nonatomic) NSMutableArray *podcastKeysToRequest; // @synthesize podcastKeysToRequest=_podcastKeysToRequest;
- (void)updateSettingsForPodcast:(id)arg1 podcastDict:(id)arg2 ctx:(id)arg3;	// IMP=0x00000001001641d8
- (void)subscribeFromCloudToPodcasts:(id)arg1;	// IMP=0x0000000100163c54
- (void)transaction:(id)arg1 didProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x0000000100163c3c
- (void)transaction:(id)arg1 willProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x0000000100163c38
- (id)_podcastSubscriptions;	// IMP=0x00000001001637b8
- (void)markAddedSubscriptionsAsSynced;	// IMP=0x00000001001634bc
- (id)_addedSubscriptions;	// IMP=0x00000001001631d8
- (id)syncDictionaryToMetricsDictionary:(id)arg1;	// IMP=0x0000000100163154
- (void)transaction:(id)arg1 mergeData:(id)arg2 forKey:(id)arg3 domainVersion:(id)arg4 version:(id)arg5 mismatch:(_Bool)arg6 finishedBlock:(CDUnknownBlockType)arg7;	// IMP=0x00000001001611c0
- (id)dataForSetTransaction:(id)arg1 key:(id)arg2 version:(id *)arg3;	// IMP=0x0000000100160d68
- (id)versionForGetTransaction:(id)arg1 key:(id)arg2;	// IMP=0x0000000100160c24
- (id)context;	// IMP=0x0000000100160bc8
- (id)init;	// IMP=0x00000001001609dc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

