//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTSubscribeUtil : NSObject
{
}

+ (id)identifierForDictionary:(id)arg1;	// IMP=0x0000000100017304
+ (_Bool)isSubscribedToPodcastWithStorePlatformDictionary:(id)arg1;	// IMP=0x0000000100017098
+ (void)unsubscribeToPodcastWithStorePlatformDictionary:(id)arg1;	// IMP=0x0000000100016e5c
+ (void)subscribeToPodcastWithStorePlatformDictionary:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100016824
+ (void)subscribeToPodcastWithFeedUrl:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000162b0

@end

