//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSDate, UIImageView, UIView;

@interface MTSwitch : UIControl
{
    UIImageView *_backgroundImageView;	// 8 = 0x8
    UIImageView *_thumbImageView;	// 16 = 0x10
    UIView *_thumbView;	// 24 = 0x18
    double _trackingOffset;	// 32 = 0x20
    double _trackingStartLocation;	// 40 = 0x28
    struct CGRect _startThumbRect;	// 48 = 0x30
    NSDate *_trackingStartTime;	// 80 = 0x50
    _Bool _on;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x000000010003d0d0
@property(nonatomic, getter=isOn) _Bool on; // @synthesize on=_on;
- (struct CGRect)thumbRectForOn:(_Bool)arg1;	// IMP=0x000000010003d028
- (struct CGRect)thumbRectForOffset:(double)arg1;	// IMP=0x000000010003cf58
- (void)swiped:(id)arg1;	// IMP=0x000000010003cec8
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x000000010003ce88
- (void)cancelTrackingWithEvent:(id)arg1;	// IMP=0x000000010003cce0
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003caf0
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003ca3c
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003c958
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010003c8f0
- (void)setOn:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010003c828
- (void)layoutSubviews;	// IMP=0x000000010003c798
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003c4f4

@end

