//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIToolbar.h>

@class UIColor, UIView;

@interface MTToolbar : UIToolbar
{
    UIView *_separatorView;	// 8 = 0x8
    UIColor *_separatorColor;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010003e45c
@property(retain, nonatomic) UIColor *separatorColor; // @synthesize separatorColor=_separatorColor;
- (void)layoutSubviews;	// IMP=0x000000010003e354
- (id)_separatorColor;	// IMP=0x000000010003e2e8
@property(nonatomic, getter=isSeparatorHidden) _Bool separatorHidden;
- (void)setupView;	// IMP=0x000000010003e0ac
- (id)init;	// IMP=0x000000010003e054

@end

