//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTActionController.h"

@protocol MTTVPodcastActionController;

@interface MTTVPodcastActionController : MTActionController
{
}

- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000100031314
- (id)allActions;	// IMP=0x00000001000311e8

// Remaining properties
@property(nonatomic) __weak id <MTTVPodcastActionController> delegate; // @dynamic delegate;

@end

