//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTGenericSettingsViewController.h"

@interface MTTVGenericSettingsViewController : MTGenericSettingsViewController
{
}

+ (id)cellClassForSettingType:(long long)arg1 inGroupWithIdentifier:(id)arg2;	// IMP=0x00000001001201f0
+ (id)footerFont;	// IMP=0x000000010011fe68
- (_Bool)_radioButtonTintsTextColorOnSelection;	// IMP=0x0000000100120a74
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;	// IMP=0x0000000100120a18
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100120820
- (id)optionsTableViewControllerWithOption:(id)arg1;	// IMP=0x00000001001207cc
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2 withDescription:(id)arg3 inGroupWithIdentifier:(id)arg4;	// IMP=0x00000001001203f4
- (id)newCellForDescriptionType:(long long)arg1 inGroupWithIdentifier:(id)arg2;	// IMP=0x0000000100120294
- (void)viewWillLayoutSubviews;	// IMP=0x000000010011ff38
- (void)viewDidLoad;	// IMP=0x000000010011fe88

@end

