//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTTVFetchedCollectionWithSectionsViewController.h"

#import "MTTVCreateStationButtonCollectionViewCellDelegate-Protocol.h"
#import "MTTVPodcastActionController-Protocol.h"
#import "MTTVStationActionControllerDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class MTTVPodcastActionController, MTTVStationActionController, NSString, UITextField;

@interface MTTVPodcastsAndStationsViewController : MTTVFetchedCollectionWithSectionsViewController <UITextFieldDelegate, UICollectionViewDelegateFlowLayout, MTTVPodcastActionController, MTTVStationActionControllerDelegate, MTTVCreateStationButtonCollectionViewCellDelegate>
{
    _Bool _hasStations;	// 8 = 0x8
    UITextField *_hiddenTextField;	// 16 = 0x10
    MTTVPodcastActionController *_podcastActionController;	// 24 = 0x18
    MTTVStationActionController *_stationActionController;	// 32 = 0x20
}

+ (id)notSubscribedPodcastResultsController;	// IMP=0x00000001000b4a8c
+ (id)subscribedPodcastResultsController;	// IMP=0x00000001000b496c
+ (id)predicateForStations;	// IMP=0x00000001000b4958
+ (id)createFirstStationResultsController;	// IMP=0x00000001000b4894
+ (id)stationResultsController;	// IMP=0x00000001000b4758
+ (id)resultsController;	// IMP=0x00000001000b45fc
- (void).cxx_destruct;	// IMP=0x00000001000b7508
@property(nonatomic) _Bool hasStations; // @synthesize hasStations=_hasStations;
@property(retain, nonatomic) MTTVStationActionController *stationActionController; // @synthesize stationActionController=_stationActionController;
@property(retain, nonatomic) MTTVPodcastActionController *podcastActionController; // @synthesize podcastActionController=_podcastActionController;
@property(retain, nonatomic) UITextField *hiddenTextField; // @synthesize hiddenTextField=_hiddenTextField;
- (void)buttonCell:(id)arg1 didSelectButton:(id)arg2;	// IMP=0x00000001000b7480
- (void)_updateFocusabilityForCreateStationButtonFooter;	// IMP=0x00000001000b7288
- (void)_updateSectionHeaderVisbilityForSubscribedPodcasts;	// IMP=0x00000001000b7194
- (void)_didUpdateCollectionView:(id)arg1;	// IMP=0x00000001000b7108
- (id)_indexPathForPodcastUuid:(id)arg1;	// IMP=0x00000001000b7034
- (void)_showCreateStationUI;	// IMP=0x00000001000b6f4c
- (_Bool)_hasOnePodcast;	// IMP=0x00000001000b6ea8
- (_Bool)_hasUnsubscribedPodcasts;	// IMP=0x00000001000b6e54
- (_Bool)_hasSubscribedPodcasts;	// IMP=0x00000001000b6e00
- (_Bool)_hasStations;	// IMP=0x00000001000b6dac
- (_Bool)_isIndexPathForCreateNewStation:(id)arg1;	// IMP=0x00000001000b6cfc
- (void)textFieldDidEndEditing:(id)arg1;	// IMP=0x00000001000b6acc
- (void)performDeleteStation:(id)arg1;	// IMP=0x00000001000b69fc
- (void)performShowSettingsForStation:(id)arg1;	// IMP=0x00000001000b6938
- (void)performDeletePodcast:(id)arg1;	// IMP=0x00000001000b67e0
- (void)performShowSettingsForPodcast:(id)arg1;	// IMP=0x00000001000b671c
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000b6688
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000b64a4
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x00000001000b6380
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;	// IMP=0x00000001000b6370
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x00000001000b62b0
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x00000001000b6260
- (id)collectionView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x00000001000b61c4
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x00000001000b6124
- (id)reuseIdentifierForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000b605c
- (void)tearDownEmptyContentViewController;	// IMP=0x00000001000b5fe8
- (void)standupEmptyContentViewController;	// IMP=0x00000001000b5f74
- (void)updateListState;	// IMP=0x00000001000b5e7c
- (void)collectionView:(id)arg1 configureCell:(id)arg2 withPodcast:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x00000001000b5d4c
- (void)collectionView:(id)arg1 configureCell:(id)arg2 withStation:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x00000001000b5b2c
- (void)collectionView:(id)arg1 configureCell:(id)arg2 withObject:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x00000001000b5a30
- (void)collectionView:(id)arg1 didLongPressItemAtIndexPath:(id)arg2;	// IMP=0x00000001000b5864
- (void)playItemAtIndexPath:(id)arg1;	// IMP=0x00000001000b5674
- (void)artworkDidChange:(id)arg1;	// IMP=0x00000001000b549c
- (void)unregisterForArtworkChangeNotifications;	// IMP=0x00000001000b543c
- (void)registerForArtworkChangeNotifications;	// IMP=0x00000001000b53d4
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000b535c
- (void)registerCollectionViewClasses;	// IMP=0x00000001000b515c
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000b5128
- (void)viewDidLoad;	// IMP=0x00000001000b4d74
- (void)dealloc;	// IMP=0x00000001000b4d28
- (id)init;	// IMP=0x00000001000b4bac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

