//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTTVEpisodeListViewController.h"

@interface MTTVListenNowEpisodeListViewController : MTTVEpisodeListViewController
{
}

+ (id)resultsController;	// IMP=0x000000010012a798
+ (Class)episodeCellClass;	// IMP=0x000000010012a78c
- (void)playEpisodeAtIndexPath:(id)arg1;	// IMP=0x000000010012ad88
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x000000010012acdc
- (id)preferredFocusedView;	// IMP=0x000000010012acd0
- (id)deleteEpisodeAction;	// IMP=0x000000010012ab20
- (void)viewDidLoad;	// IMP=0x000000010012aa20
- (id)init;	// IMP=0x000000010012a8dc

@end

