//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class TVMTMusicBarsView, UIColor, UIImage, UIImageView;

@interface MTTVEpisodePlayStatusView : UIView
{
    _Bool _currentPlayerItem;	// 8 = 0x8
    _Bool _barsFillBounds;	// 9 = 0x9
    UIColor *_barsTintColor;	// 16 = 0x10
    UIImageView *_dotView;	// 24 = 0x18
    TVMTMusicBarsView *_barsView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010014f15c
@property(retain, nonatomic) TVMTMusicBarsView *barsView; // @synthesize barsView=_barsView;
@property(retain, nonatomic) UIImageView *dotView; // @synthesize dotView=_dotView;
@property(nonatomic) _Bool barsFillBounds; // @synthesize barsFillBounds=_barsFillBounds;
@property(retain, nonatomic) UIColor *barsTintColor; // @synthesize barsTintColor=_barsTintColor;
@property(nonatomic, getter=isCurrentPlayerItem) _Bool currentPlayerItem; // @synthesize currentPlayerItem=_currentPlayerItem;
- (void)didMoveToWindow;	// IMP=0x000000010014ef6c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010014ef60
- (void)layoutSubviews;	// IMP=0x000000010014edc8
- (void)updatePlaybackState;	// IMP=0x000000010014ec34
- (void)_unregisterForNotifications;	// IMP=0x000000010014eb44
- (void)_registerForNotifications;	// IMP=0x000000010014ea40
@property(nonatomic) unsigned long long barsStyle;
@property(nonatomic) UIImage *image;
- (void)dealloc;	// IMP=0x000000010014e4e0
- (id)init;	// IMP=0x000000010014e460

@end

