//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTPredicateManifest.h"

@interface MTUnplayedManifest : MTPredicateManifest
{
}

+ (id)activityTypeSuffix;	// IMP=0x00000001000f29a4
+ (void)createManifestForActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000f2874
- (id)initWithInitialEpisodeUuid:(id)arg1 newestToOldest:(_Bool)arg2;	// IMP=0x00000001000f24e0
- (id)initWithInitialEpisodeUuid:(id)arg1;	// IMP=0x00000001000f24d0

@end

