//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTManifestResultsController.h"

@interface MTUpNextResultsController : MTManifestResultsController
{
}

+ (id)numberFormatter;	// IMP=0x00000001000bb8b8
- (unsigned long long)startingIndexForDisplay;	// IMP=0x00000001000bb96c
- (id)title;	// IMP=0x00000001000bb748
- (id)init;	// IMP=0x00000001000bb69c

@end

