//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTURLResolver : NSObject
{
}

+ (_Bool)_handleLegacyCoreSpotlightURL:(id)arg1;	// IMP=0x00000001000b93c4
+ (_Bool)_isLegacyCoreSpotlightURL:(id)arg1;	// IMP=0x00000001000b92cc
+ (_Bool)_handleNowPlayingURL:(id)arg1;	// IMP=0x00000001000b9110
+ (id)episodeUrlForPodcastStoreId:(long long)arg1 episodeStoreId:(long long)arg2;	// IMP=0x00000001000b905c
+ (id)podcastUrlForStoreId:(long long)arg1;	// IMP=0x00000001000b8f28
+ (id)searchUrlForSearchText:(id)arg1;	// IMP=0x00000001000b8df8
+ (void)showSearchControllerWithSearchText:(id)arg1;	// IMP=0x00000001000b8d28
+ (void)handlePodcastsUrlScheme:(id)arg1;	// IMP=0x00000001000b88ec
+ (void)handleiTMSUrlScheme:(id)arg1;	// IMP=0x00000001000b84a8
+ (id)appController;	// IMP=0x00000001000b8494

@end

