//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSData, NSDictionary;
@protocol OS_dispatch_queue;

@interface MZKeyValueStoreClampsController : NSObject <NSSecureCoding>
{
    NSDictionary *_transactionClamps;	// 8 = 0x8
    double _dsidCheckTimestamp;	// 16 = 0x10
    double _authenticationNeededTimestamp;	// 24 = 0x18
    double _userAcceptedSyncTimestamp;	// 32 = 0x20
    double _networkingBlockedUntil;	// 40 = 0x28
    double _backOffUntil;	// 48 = 0x30
    double _userCancelledSignInBackOffUntil;	// 56 = 0x38
    double _nextUserCancelBackOffInterval;	// 64 = 0x40
    NSData *_pendingUserDefaultArchivedData;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_queue;	// 80 = 0x50
}

+ (id)_classesForTransactionClampsValues;	// IMP=0x0000000100022460
+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100021c7c
+ (id)sharedClampsController;	// IMP=0x0000000100021758
- (void).cxx_destruct;	// IMP=0x0000000100023418
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) NSData *pendingUserDefaultArchivedData; // @synthesize pendingUserDefaultArchivedData=_pendingUserDefaultArchivedData;
@property double nextUserCancelBackOffInterval; // @synthesize nextUserCancelBackOffInterval=_nextUserCancelBackOffInterval;
@property double userCancelledSignInBackOffUntil; // @synthesize userCancelledSignInBackOffUntil=_userCancelledSignInBackOffUntil;
@property double backOffUntil; // @synthesize backOffUntil=_backOffUntil;
@property double networkingBlockedUntil; // @synthesize networkingBlockedUntil=_networkingBlockedUntil;
@property double userAcceptedSyncTimestamp; // @synthesize userAcceptedSyncTimestamp=_userAcceptedSyncTimestamp;
@property double authenticationNeededTimestamp; // @synthesize authenticationNeededTimestamp=_authenticationNeededTimestamp;
@property double dsidCheckTimestamp; // @synthesize dsidCheckTimestamp=_dsidCheckTimestamp;
@property(retain, nonatomic) NSDictionary *transactionClamps; // @synthesize transactionClamps=_transactionClamps;
- (_Bool)_canScheduleTransactionBasedOnUserCancelledSignIn:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100023234
- (_Bool)_canScheduleTransactionBasedOnBackOff:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100023138
- (_Bool)_canScheduleTransactionBasedOnDSIDCheck:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100023098
- (_Bool)_canScheduleTransactionBasedOfNetworkingBlocked:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002300c
- (_Bool)_canScheduleTransactionBasedOnType:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022e04
- (id)_keyForTransaction:(id)arg1;	// IMP=0x0000000100022d00
- (double)_rightNow;	// IMP=0x0000000100022ca4
- (_Bool)isNetworkingBlocked;	// IMP=0x0000000100022c18
- (void)clearNetworkingBlocked;	// IMP=0x0000000100022c08
- (void)setNetworkingBlocked;	// IMP=0x0000000100022bb8
- (void)clearBackOff;	// IMP=0x0000000100022b80
- (void)backOffForTimeInterval:(double)arg1;	// IMP=0x0000000100022b2c
- (void)clearUserCancelledSignIn;	// IMP=0x0000000100022ae8
- (void)setUserCancelledSignIn;	// IMP=0x0000000100022a4c
- (_Bool)hasUserRecentlyAcceptedSync;	// IMP=0x000000010002299c
- (void)clearUserAcceptedSyncTimestamp;	// IMP=0x0000000100022964
- (void)setUserAcceptedSyncTimestamp;	// IMP=0x0000000100022920
- (_Bool)hasAuthenticatedTooRecentlyForTransaction:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022864
- (void)clearAuthenticationRequest;	// IMP=0x000000010002282c
- (void)setAuthenticationRequest;	// IMP=0x00000001000227e8
- (void)clearDSIDCheckTimestamp;	// IMP=0x00000001000227b0
- (void)setDSIDCheckTimestamp;	// IMP=0x000000010002276c
- (void)clearTimestampForTransaction:(id)arg1;	// IMP=0x00000001000226a0
- (void)setTimestampForTransaction:(id)arg1;	// IMP=0x0000000100022584
- (void)reset;	// IMP=0x00000001000223b4
- (void)accessTransactionClampsWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100022250
- (_Bool)canScheduleTransaction:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002217c
- (id)description;	// IMP=0x0000000100021fcc
- (void)saveToUserDefaults;	// IMP=0x0000000100021c84
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100021a78
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100021944
- (id)init;	// IMP=0x00000001000218b4

@end

