//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (MTAdditions)
- (_Bool)isBefore:(id)arg1;	// IMP=0x000000010010b028
- (_Bool)isAfter:(id)arg1;	// IMP=0x000000010010b004
- (unsigned long long)lastIndex;	// IMP=0x000000010010afa8
- (id)indexPathByChangingSection:(long long)arg1;	// IMP=0x000000010010af44
@end

