//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (MTAdditions)
+ (double)mt_scaledConstantForTextStyle:(id)arg1 defaultConstant:(double)arg2;	// IMP=0x0000000100099c24
+ (id)mt_fontDescriptorForTextStyle:(id)arg1 contentSizeCategoryName:(id)arg2;	// IMP=0x0000000100099bd8
+ (id)mt_fontForTextStyle:(id)arg1 addingSymbolicTraits:(unsigned int)arg2 contentSizeCategoryName:(id)arg3;	// IMP=0x0000000100099b18
+ (id)mt_fontForTextStyle:(id)arg1 contentSizeCategoryName:(id)arg2;	// IMP=0x0000000100099a84
+ (id)mt_preferredFontForTextStyle:(id)arg1 addingSymbolicTraits:(unsigned int)arg2;	// IMP=0x0000000100099a14
+ (id)mt_preferredFontForTextStyle:(id)arg1;	// IMP=0x0000000100099a04
+ (id)headerDetailFont;	// IMP=0x00000001000999ec
+ (id)headerTitleFont;	// IMP=0x00000001000999d4
+ (id)cellDetailFont;	// IMP=0x00000001000999b8
+ (id)cellTitleFont;	// IMP=0x0000000100099998
+ (id)buttonFont;	// IMP=0x0000000100099980
- (double)mt_leftMargin;	// IMP=0x0000000100099cfc
- (double)mt_offsetFromLastBaselineToBottom;	// IMP=0x0000000100099cdc
- (double)mt_offsetFromFirstBaselineToTop;	// IMP=0x0000000100099cd0
- (double)mt_offsetFromCapHeightToAscent;	// IMP=0x0000000100099c88
@end

