//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (MTAdditionsHidden)
+ (id)mt_rootViewController;	// IMP=0x00000001000f4ff4
- (_Bool)hiddenIfEmpty;	// IMP=0x0000000100013068
- (id)mt_topViewControllerExcludingPopovers;	// IMP=0x00000001000f4f38
- (id)mt_topViewController;	// IMP=0x00000001000f4eac
- (_Bool)mt_isVisible;	// IMP=0x00000001000f4e30
- (void)simulateMemoryWarning;	// IMP=0x00000001000f4e2c
- (_Bool)isADescendantOfParentViewController:(id)arg1;	// IMP=0x00000001000f4d58
- (void)visitChildenViewControllers:(CDUnknownBlockType)arg1;	// IMP=0x00000001000f4bfc
- (id)recursiveDescription;	// IMP=0x00000001000f4b90
- (id)_recursiveDescriptionWithLevel:(long long)arg1 result:(id)arg2;	// IMP=0x00000001000f4980
@end

