//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVHomeSharingKit/TVHKMediaEntity.h>

@class NSString;

@interface TVHKMediaEntity (TVHomeSharing)
- (id)tvh_contentDescriptionAttributedStringWithFont:(id)arg1 textColor:(id)arg2;	// IMP=0x000000010003c3ac
- (id)tvh_contentDescriptionAttributedString;	// IMP=0x000000010003c2b0
@property(readonly, copy, nonatomic) NSString *tvh_displayGenreTitle;
@property(readonly, copy, nonatomic) NSString *tvh_displayTitle;
@property(readonly, nonatomic) _Bool tvh_isVideoItem;
@end

