//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVHPreviewingListViewController.h"

@class NSArray, UICollectionViewDiffableDataSource, UIImageView;
@protocol TVHMediaLibraryPickerViewControllerDelegate;

@interface TVHMediaLibraryPickerViewController : TVHPreviewingListViewController
{
    id <TVHMediaLibraryPickerViewControllerDelegate> _mediaLibraryPickerDelegate;	// 8 = 0x8
    NSArray *_mediaLibraries;	// 16 = 0x10
    UIImageView *_imageView;	// 24 = 0x18
    UICollectionViewDiffableDataSource *_diffableDataSource;	// 32 = 0x20
}

+ (id)_sortedMediaLibraries:(id)arg1;	// IMP=0x0000000100056820
- (void).cxx_destruct;	// IMP=0x0000000100056a00
@property(retain, nonatomic) UICollectionViewDiffableDataSource *diffableDataSource; // @synthesize diffableDataSource=_diffableDataSource;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSArray *mediaLibraries; // @synthesize mediaLibraries=_mediaLibraries;
@property(nonatomic) __weak id <TVHMediaLibraryPickerViewControllerDelegate> mediaLibraryPickerDelegate; // @synthesize mediaLibraryPickerDelegate=_mediaLibraryPickerDelegate;
- (void)_updateImageTintColor;	// IMP=0x000000010005675c
- (id)_mediaLibraryForIndexPath:(id)arg1;	// IMP=0x00000001000566c8
- (id)_cellForCollectionView:(id)arg1 withIdentifier:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000565bc
- (void)_mediaLibrariesDidChange:(_Bool)arg1;	// IMP=0x0000000100056440
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100056154
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000560a0
- (void)viewDidLoad;	// IMP=0x0000000100055e7c
- (void)updateWithMediaLibraries:(id)arg1;	// IMP=0x0000000100055dd8
- (id)initWithMediaLibraries:(id)arg1;	// IMP=0x0000000100055b00
- (id)initWithItemSize:(struct CGSize)arg1;	// IMP=0x0000000100055a78
- (id)initWithListViewLayout:(id)arg1;	// IMP=0x00000001000559f0

@end

