//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface TVHPlayedStateGroupTitleValueTransformer : NSValueTransformer
{
}

+ (_Bool)allowsReverseTransformation;	// IMP=0x0000000100069208
+ (Class)transformedValueClass;	// IMP=0x00000001000691fc
- (id)transformedValue:(id)arg1;	// IMP=0x0000000100069210

@end

