//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVHMediaEntitiesFetchViewController.h"

#import "TVHMediaEntitiesFetchViewControllerDelegate-Protocol.h"
#import "TVHMediaEntitiesShelfViewControllerDelegate-Protocol.h"
#import "TVHProductInfoViewDelegate-Protocol.h"
#import "TVHProductViewControllerDelegate-Protocol.h"
#import "TVHSeasonEpisodesViewControllerDelegate-Protocol.h"
#import "TVHShowsInfoCenterObserver-Protocol.h"

@class NSArray, NSString, TVHKMediaEntitiesFetchContext, TVHKMediaEntityCollection, TVHKMediaItem, TVHProductContentSectionItem, TVHProductViewController, TVHShowsInfoCenter;
@protocol TVHSeasonDetailsViewControllerDelegate;

@interface TVHSeasonDetailsViewController : TVHMediaEntitiesFetchViewController <TVHMediaEntitiesFetchViewControllerDelegate, TVHMediaEntitiesShelfViewControllerDelegate, TVHSeasonEpisodesViewControllerDelegate, TVHShowsInfoCenterObserver, TVHProductInfoViewDelegate, TVHProductViewControllerDelegate>
{
    struct {
        unsigned int respondsToDidOverrideUserInterfaceStyle:1;
        unsigned int respondsToDidSelectSeasonPicker:1;
    } _delegateFlags;	// 8 = 0x8
    id <TVHSeasonDetailsViewControllerDelegate> _seasonDetailsDelegate;	// 16 = 0x10
    TVHShowsInfoCenter *_showsInfoCenter;	// 24 = 0x18
    TVHKMediaEntityCollection *_show;	// 32 = 0x20
    TVHKMediaEntitiesFetchContext *_showsFetchContext;	// 40 = 0x28
    NSArray *_episodes;	// 48 = 0x30
    TVHKMediaItem *_nextPlaybackEpisode;	// 56 = 0x38
    TVHProductViewController *_productViewController;	// 64 = 0x40
    TVHProductContentSectionItem *_episodesContentSectionItem;	// 72 = 0x48
    TVHProductContentSectionItem *_genreShowsContentSectionItem;	// 80 = 0x50
    TVHProductContentSectionItem *_seperatorContentSectionItem;	// 88 = 0x58
    TVHProductContentSectionItem *_footerContentSectionItem;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x000000010000687c
@property(retain, nonatomic) TVHProductContentSectionItem *footerContentSectionItem; // @synthesize footerContentSectionItem=_footerContentSectionItem;
@property(retain, nonatomic) TVHProductContentSectionItem *seperatorContentSectionItem; // @synthesize seperatorContentSectionItem=_seperatorContentSectionItem;
@property(retain, nonatomic) TVHProductContentSectionItem *genreShowsContentSectionItem; // @synthesize genreShowsContentSectionItem=_genreShowsContentSectionItem;
@property(retain, nonatomic) TVHProductContentSectionItem *episodesContentSectionItem; // @synthesize episodesContentSectionItem=_episodesContentSectionItem;
@property(retain, nonatomic) TVHProductViewController *productViewController; // @synthesize productViewController=_productViewController;
@property(retain, nonatomic) TVHKMediaItem *nextPlaybackEpisode; // @synthesize nextPlaybackEpisode=_nextPlaybackEpisode;
@property(retain, nonatomic) NSArray *episodes; // @synthesize episodes=_episodes;
@property(retain, nonatomic) TVHKMediaEntitiesFetchContext *showsFetchContext; // @synthesize showsFetchContext=_showsFetchContext;
@property(retain, nonatomic) TVHKMediaEntityCollection *show; // @synthesize show=_show;
@property(readonly, nonatomic) TVHShowsInfoCenter *showsInfoCenter; // @synthesize showsInfoCenter=_showsInfoCenter;
@property(nonatomic) __weak id <TVHSeasonDetailsViewControllerDelegate> seasonDetailsDelegate; // @synthesize seasonDetailsDelegate=_seasonDetailsDelegate;
- (void)_playEpisode:(id)arg1;	// IMP=0x0000000100006644
- (struct CGSize)_genreShowImageSize;	// IMP=0x00000001000065e4
- (void)_updateProductViewControllerContentSectionItems;	// IMP=0x0000000100005f78
- (void)_updateProductViewControllerFooterView;	// IMP=0x0000000100005ab4
- (void)_updatePlayButtonLockup:(id)arg1 withEpisodeNumber:(id)arg2;	// IMP=0x000000010000594c
- (struct CGSize)_showImageSize;	// IMP=0x00000001000058e0
- (void)_updateProductViewControllerBannerView;	// IMP=0x0000000100005278
- (void)_updateWithFetchControllerResultSet:(id)arg1;	// IMP=0x00000001000050ac
- (id)_footerViewController;	// IMP=0x0000000100005058
- (id)_genreShowsViewController;	// IMP=0x0000000100005004
- (id)_episodesViewController;	// IMP=0x0000000100004fb0
- (id)_season;	// IMP=0x0000000100004fa4
- (void)_seasonsButtonLockupSelected;	// IMP=0x0000000100004f40
- (void)_playButtonLockupSelected;	// IMP=0x0000000100004ef4
- (void)productInfoViewDidSelectContentDescription:(id)arg1;	// IMP=0x0000000100004de0
- (void)seasonEpisodesViewController:(id)arg1 didPlayEpisode:(id)arg2;	// IMP=0x0000000100004dd0
- (void)seasonEpisodesViewController:(id)arg1 didSelectEpisode:(id)arg2;	// IMP=0x0000000100004dc0
- (void)mediaEntitiesShelfViewController:(id)arg1 didSelectMediaEntity:(id)arg2;	// IMP=0x0000000100004c94
- (void)mediaEntitiesShelfViewController:(id)arg1 configureLockup:(id)arg2 forMediaEntity:(id)arg3;	// IMP=0x0000000100004be0
- (void)showsInfoCenterDidChange:(id)arg1;	// IMP=0x0000000100004af4
- (void)productViewController:(id)arg1 didOverrideUserInterfaceStyle:(long long)arg2;	// IMP=0x0000000100004ae4
- (void)mediaEntitiesFetchViewController:(id)arg1 purgeSourceMediaEntityBackgroundImagesForContentViewController:(id)arg2;	// IMP=0x0000000100004aa4
- (void)mediaEntitiesFetchViewController:(id)arg1 updateContentViewController:(id)arg2 withSourceMediaEntity:(id)arg3 sourceMediaEntityBackgroundImageInfo:(id)arg4;	// IMP=0x0000000100004a38
- (void)mediaEntitiesFetchViewController:(id)arg1 updateContentViewController:(id)arg2 withFetchControllerResultSet:(id)arg3;	// IMP=0x0000000100004a00
- (id)mediaEntitiesFetchViewController:(id)arg1 contentViewControllerWithFetchControllerResultSet:(id)arg2 sourceMediaEntity:(id)arg3 sourceMediaEntityBackgroundImageInfo:(id)arg4;	// IMP=0x0000000100004758
- (void)setOverrideUserInterfaceStyle:(long long)arg1;	// IMP=0x00000001000046c4
- (void)dealloc;	// IMP=0x00000001000045c0
- (id)initWithSeason:(id)arg1 seasonsFetchContext:(id)arg2 show:(id)arg3 showsFetchContext:(id)arg4 showsInfoCenter:(id)arg5;	// IMP=0x00000001000042a4
- (id)initWithMediaLibrary:(id)arg1 fetchRequests:(id)arg2 mode:(unsigned long long)arg3 sourceMediaEntity:(id)arg4 sourceMediaEntitiesFetchContext:(id)arg5;	// IMP=0x000000010000421c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

