//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVHMediaEntitiesFetchViewController.h"

#import "TVHCatalogueViewControllerDelegate-Protocol.h"
#import "TVHMediaEntitiesFetchViewControllerDelegate-Protocol.h"
#import "TVHMediaLibraryTabBarItemViewController-Protocol.h"

@class NSSet, NSString, TVHCatalogueViewController, TVHShowsDataStore;

@interface TVHShowsTabBarItemViewController : TVHMediaEntitiesFetchViewController <TVHCatalogueViewControllerDelegate, TVHMediaEntitiesFetchViewControllerDelegate, TVHMediaLibraryTabBarItemViewController>
{
    TVHShowsDataStore *_dataStore;	// 8 = 0x8
    TVHCatalogueViewController *_catalogueViewController;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000179f4
@property(retain, nonatomic) TVHCatalogueViewController *catalogueViewController; // @synthesize catalogueViewController=_catalogueViewController;
@property(readonly, nonatomic) TVHShowsDataStore *dataStore; // @synthesize dataStore=_dataStore;
- (void)_updateDataStoreWithFetchControllerResultSet:(id)arg1;	// IMP=0x0000000100017954
- (void)catalogViewController:(id)arg1 didSelectMediaEntity:(id)arg2;	// IMP=0x00000001000176ec
- (void)mediaEntitiesFetchViewController:(id)arg1 updateContentViewController:(id)arg2 withFetchControllerResultSet:(id)arg3;	// IMP=0x00000001000176dc
- (id)mediaEntitiesFetchViewController:(id)arg1 contentViewControllerWithFetchControllerResultSet:(id)arg2 sourceMediaEntity:(id)arg3 sourceMediaEntityBackgroundImageInfo:(id)arg4;	// IMP=0x00000001000175c8
- (void)didLoseSelection;	// IMP=0x00000001000175bc
- (void)didReceiveSelection;	// IMP=0x00000001000175b0
@property(readonly, nonatomic) unsigned long long selectedMediaCategoryType;
@property(readonly, copy, nonatomic) NSSet *mediaCategoryTypes;
@property(readonly, nonatomic) unsigned long long type;
- (id)initWithMediaLibrary:(id)arg1;	// IMP=0x00000001000173f4
- (id)initWithMediaLibrary:(id)arg1 fetchRequests:(id)arg2 mode:(unsigned long long)arg3 sourceMediaEntity:(id)arg4 sourceMediaEntitiesFetchContext:(id)arg5;	// IMP=0x000000010001736c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

