//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSHashTable, TVHKMediaLibrary;

@interface TVHShowsInfoCenter : NSObject
{
    TVHKMediaLibrary *_mediaLibrary;	// 8 = 0x8
    NSArray *_shows;	// 16 = 0x10
    NSDictionary *_showByIdentifier;	// 24 = 0x18
    NSDictionary *_showsByGenreTitle;	// 32 = 0x20
    NSHashTable *_observers;	// 40 = 0x28
}

+ (id)new;	// IMP=0x000000010006758c
- (void).cxx_destruct;	// IMP=0x0000000100067af4
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(copy, nonatomic) NSDictionary *showsByGenreTitle; // @synthesize showsByGenreTitle=_showsByGenreTitle;
@property(copy, nonatomic) NSDictionary *showByIdentifier; // @synthesize showByIdentifier=_showByIdentifier;
@property(copy, nonatomic) NSArray *shows; // @synthesize shows=_shows;
@property(readonly, nonatomic) TVHKMediaLibrary *mediaLibrary; // @synthesize mediaLibrary=_mediaLibrary;
- (void)updateWithFetchResponse:(id)arg1;	// IMP=0x0000000100067800
- (void)removeObserver:(id)arg1;	// IMP=0x0000000100067794
- (void)addObserver:(id)arg1;	// IMP=0x0000000100067728
- (id)initWithMediaLibrary:(id)arg1;	// IMP=0x0000000100067650
- (id)init;	// IMP=0x00000001000675c8

@end

