//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TVHURLHandler : NSObject
{
}

+ (id)_playMediaEntityViewControllerForOpenURL:(id)arg1 mediaLibrary:(id)arg2;	// IMP=0x000000010006097c
+ (id)_displayMediaEntityViewControllerForOpenURL:(id)arg1 mediaLibrary:(id)arg2;	// IMP=0x00000001000605f4
+ (id)viewControllersForURL:(id)arg1 mediaLibrary:(id)arg2;	// IMP=0x00000001000602e4

@end

